### ISSUE TITLE
复合使用函数

### ISSUE THREAD

**Issue by 15715323364** [youseries/ureport#10]
在对数据进行计算时，往往要用到avg（D2）函数，而且要对平均值保留两位小数，用round（）。为什么round（avg（D2））用不了。。。而且，avg（D2），即使值是6.25，显示的也是6.25000000，这是我自己写的问题吗？谢谢

**Comment by lokamir** [comment]
同问，格式化来保留位数数字就成字符串格式了，有没有什么办法可以既保留数值，有能控制小数位数的办法

**Comment by youseries** [comment]
复合函数我要测下。小数位数可使用numberformat函数

**Comment by youseries** [comment]
BUG，已修复，请更新到最新版测试，谢谢。
