### ISSUE TITLE
直接指定报表名分页预览 在线打印报错

### ISSUE THREAD

**Issue by azengqiang** [youseries/ureport#103]
设计的时候 分页预览 在线打印是可以的（http://localhost:8080/ureport/preview?_u=p&_i=1 ） 直接指定报表名分页预览  在线打印 不行 （http://localhost:8080/ureport/preview?_u=database:user.ureport.xml&_i=1 ）
必须先不分页打开 （http://localhost:8080/ureport/preview?_u=database:user.ureport.xml） 然后再分页打开（http://localhost:8080/ureport/preview?_u=database:user.ureport.xml&_i=1）才可以在线打印

**Comment by azengqiang** [comment]
直接指定报表名分页预览 在线打印报错

**Comment by youseries** [comment]
已处理，请更新最新的2.2-SNAPSHOT测试，谢谢！
