### ISSUE TITLE
空白页问题

### ISSUE THREAD

**Issue by wangbatian** [youseries/ureport#105]
获取十条数据   分页五条  会出现第三页为空白页  版本2.1.5

**Comment by youseries** [comment]
本地测了下，没出现你说的问题，请详细描述你是怎么配置的！

**Comment by wangbatian** [comment]
首先弄个标题行并设置为标题行  然后取十条数据  我是ORACLE数据库  select * from X where rownum<11 这样取的   分页设置 行数5  出现第三页空白页

**Comment by youseries** [comment]
将你模板完整截图上来，并加以说明，谢谢！

**Comment by wangbatian** [comment]
![1](https://user-images.githubusercontent.com/33248807/32304309-3e49a24c-bfa9-11e7-8acc-56e4af42acc1.jpg)
![2](https://user-images.githubusercontent.com/33248807/32304313-4d155d48-bfa9-11e7-8add-d5a953f87d7b.jpg)
![3](https://user-images.githubusercontent.com/33248807/32304315-4d71ac10-bfa9-11e7-86f7-6199f0e37083.jpg)
![4](https://user-images.githubusercontent.com/33248807/32304316-4da9af98-bfa9-11e7-940b-d0a0da3ebf83.jpg)

**Comment by wangbatian** [comment]
[kehuureport.zip](https://github.com/youseries/ureport/files/1436120/kehuureport.zip)

**Comment by youseries** [comment]
我这里显示正常，没有多出空白页，不知道你产生的原因！
