### ISSUE TITLE
ie浏览器下导出功能失效

### ISSUE THREAD

**Issue by sonot** [youseries/ureport#115]
版本2.2.1，ie11，工具条上的所有按钮点击都报错，无法使用。
报js脚本异常
SCRIPT5009: “Symbol”未定义
preview.bundle.js (1,3908)

**Comment by youseries** [comment]
ureport什么版本？

**Comment by sonot** [comment]
这个：ureport2-console-2.2.1-20171116.082645-2.jar

**Comment by youseries** [comment]
已处理，请更新最新的2.2.1-SNAPSHOT测试，谢谢。
