### ISSUE TITLE
表达式#号对应的是实际值，但是会出现对应的是显示值的情况

### ISSUE THREAD

**Issue by jamson0409** [youseries/ureport#116]
![image](https://user-images.githubusercontent.com/34023140/33256938-36021476-d38f-11e7-9733-ca76c628da5a.png)
![image](https://user-images.githubusercontent.com/34023140/33256967-4e2999b6-d38f-11e7-82a9-ad297c782617.png)
上图中A2与B2的实际值都是uuid，显示值都是单号，超链接的参数都是(id=#)但是，在点击A2时，出现的超链接中正确的，#代表的是实际值，点击B2的时候，超链接中的#号就代表的是显示值（单号）
![image](https://user-images.githubusercontent.com/34023140/33257303-b2afb252-d390-11e7-8169-7a89de567397.png)
上图是点击A2时的链接
![tim 20171127164149](https://user-images.githubusercontent.com/34023140/33257856-ad61430e-d392-11e7-8572-e0e5ae926373.png)

上图是点击B2时的链接

**Comment by youseries** [comment]
已修复，请更新最新的2.2.1-SNAPSHOT测试，谢谢。
