### ISSUE TITLE
分组统计（Serial）下的字段无法根据sql顺序排序

### ISSUE THREAD

**Issue by yingw** [youseries/ureport#117]
sql查出来排序的，报表预览的时候没效果，最外层category好像也是这个问题。
比如，SQL查出来顺序是 order by year，显示数据顺序是 2015/2016/2017 是正确的；但是在报表预览的时候有可能就变为 2016/2017/2015。

祝 UReport 越来越好！

![image](https://user-images.githubusercontent.com/1177503/33412000-dce43cac-d5c3-11e7-817d-153b1a3a596c.png)

**Comment by youseries** [comment]
已处理，请更新最新的SNAPSHOT测试，谢谢。

**Comment by yingw** [comment]
为你点赞！
