### ISSUE TITLE
报表输出字段没有做 HTML Encoding

### ISSUE THREAD

**Issue by yingw** [youseries/ureport#118]
报表预览的时候可能字段内容是html或xml的，没有做encoding，比如我查报表本身
![image](https://user-images.githubusercontent.com/1177503/33412048-2c76fa8e-d5c4-11e7-9cc3-84480c751c5b.png)

但是到了设计器里，预览就成了这样：
![image](https://user-images.githubusercontent.com/1177503/33412062-370d2ae0-d5c4-11e7-9efd-bff127de539a.png)

后台的 HTML 代码可以看到没有encoding，导致部分数据显示不出来。

祝 UReport 越来越好！

**Comment by youseries** [comment]
已对报表数据中包含的HTML字符做了转义处理，请更新最新的SNAPSHOT测试，谢谢。

**Comment by AlexYY0** [comment]
> 报表预览的时候可能字段内容是html或xml的，没有做encoding，比如我查报表本身
> ![image](https://user-images.githubusercontent.com/1177503/33412048-2c76fa8e-d5c4-11e7-9cc3-84480c751c5b.png)
> 
> 但是到了设计器里，预览就成了这样：
> ![image](https://user-images.githubusercontent.com/1177503/33412062-370d2ae0-d5c4-11e7-9efd-bff127de539a.png)
> 
> 后台的 HTML 代码可以看到没有encoding，导致部分数据显示不出来。
> 
> 祝 UReport 越来越好！

大佬，这个问题怎么解决的，问本内容里面有HTML怎么解决！
