### ISSUE TITLE
序号问题

### ISSUE THREAD

**Issue by ureportor-tao** [youseries/ureport#122]
[
[序号问题.xlsx](https://github.com/youseries/ureport/files/1517093/default.xlsx)
](url)
序号A2表达式为&W2，而W2单元格左父为E2，序号展示按E2内容分组进行排序，与学习文档描述一致。能否不按E2分组排序，单纯按W2排序？

**Comment by youseries** [comment]
这种类型的序号功能实现不了，抱歉！

**Comment by ureportor-tao** [comment]
逻辑为行号-减去分组号。
选A2，表达式为row - &B2，设置左父为C2.
其中报表是按B2进行分组

**Comment by ureportor-tao** [comment]
本例中，通过一系列数据找到y【row-&B2】与正确序号x的对应关系，即x*7 - 6=y，推出x的表达式为：(row() - &B2 + 6) / 7
