### ISSUE TITLE
url参数中，表达式#号对应的是实际值，但是会出现对应的是显示值的情况

### ISSUE THREAD

**Issue by jamson0409** [youseries/ureport#125]
![1](https://user-images.githubusercontent.com/34023140/33544433-b583e734-d915-11e7-878b-fb1d9c9604c9.png)
![2](https://user-images.githubusercontent.com/34023140/33544457-ce824a0a-d915-11e7-9650-c144b790dc60.png)
上图中A2与B2的实际值都是uuid，显示值都是单号，超链接的参数都是(id=#)但是，在点击A2时，出现的超链接中正确的，#代表的是实际值，点击B2的时候，超链接中的#号就代表的是显示值（单号）
![3](https://user-images.githubusercontent.com/34023140/33544484-e505c5fe-d915-11e7-82bd-99e9b6529fac.png)
上图是点击A2时的链接
![4](https://user-images.githubusercontent.com/34023140/33544485-e7341470-d915-11e7-8f7f-9feace805bd0.png)
上图是点击B2时的链接

**Comment by youseries** [comment]
已处理，请更新最新SNAPSHOT测试，谢谢。
