### ISSUE TITLE
图表预览空白

### ISSUE THREAD

**Issue by howell86** [youseries/ureport#126]
设置好图表后，修改“选项”，再次预览，有“选项”发生变更的图表变空白

**Comment by youseries** [comment]
最新版SNAPSHOT已修复，请更新测试，谢谢。

**Comment by howell86** [comment]
更新到Thu Dec 07 2017 16:23:54 GMT+0800上传的版本，测试问题还是一样。

**Comment by youseries** [comment]
这功能我测过的，本地确实OK了，你再更新下，确定更新成功了。
