### ISSUE TITLE
10多个不确定用户会输入值的参数传入到报表时应该如何做

### ISSUE THREAD

**Issue by leo39486** [youseries/ureport#127]
假定有10个参数，用户会选择最少0个，最多10个参数填入值，用目前wiki第8节参数里的SQL表达式似乎难以做到对没有输入的参数忽略where中的条件，目前的if方式逐个判断return一个sql字符串，会有太多种排列了，写起来太啰嗦，尝试了表达式里不支持变量，也不支持sql语法和表达式混用拼接，那么应该如何做呢，希望有对这种需求的支持

**Comment by youseries** [comment]
可以用三元表达式来进行字符串拼接，比如：
${
    "select * from employee where 1=1"+(param("name")!=null ? " and name=:name" : "")
}

**Comment by leo39486** [comment]
建议增加一个函数判断param参数是不是null或者空串，不然每个参数2个判断太冗长

**Comment by youseries** [comment]
最新的SNAPSHOT中已添加emptyparam函数，用于判断参数是否为null或""，这样上述SQL就可以写成：

**Comment by youseries** [comment]
${
"select * from employee where 1=1"+(emptyparam("name")!=null ? " and name=:name" : "")
}
