### ISSUE TITLE
表达式中怎么用数据集中的字段

### ISSUE THREAD

**Issue by wyubaoyuan** [youseries/ureport#13]

**Comment by youseries** [comment]
datasetName.select(fieldName)

**Comment by wyubaoyuan** [comment]
不对，报错了

**Comment by youseries** [comment]
报的什么错？你怎么写的？

**Comment by wyubaoyuan** [comment]
xly_statistics_stock.select(QTY)*0.64
no viable alternative at input 'xly_statistics_stock.select(QTY)'

**Comment by youseries** [comment]
什么版本？

**Comment by youseries** [comment]
BUG，已修复，请更新到最新版测试，谢谢。

**Comment by wyubaoyuan** [comment]
com.bstek.ureport.exception.ConvertException: Can not convert 3,3,3,3,3,3,2,2,2,2,2,2,2,2,2,2,2,2 to BigDecimal.之前的问题是修复了 ，又出现另一个问题

**Comment by youseries** [comment]
新问题开新issue!
