### ISSUE TITLE
建议给 Report 增加 Title 属性

### ISSUE THREAD

**Issue by yingw** [youseries/ureport#130]
建议设置一个报表网页的title属性，现在没有这个，会导致用户在浏览器中浏览不同的报表，title都是一样的“UReport2报表预览”，如果放到收藏夹，也是这样，雷同了。建议设置个页面属性或者直接去设置为标题行的第一个单元格的内容。

**Comment by youseries** [comment]
最新SNAPSHOT中为HTML报表预览添加标题定制功能，可以添加_title参数指定标题，如果不加则以当前预览的报表名为标题
