### ISSUE TITLE
建议支持外部 http url 的图片

### ISSUE THREAD

**Issue by yingw** [youseries/ureport#131]
目前要在 Report 上显示图片，是需要将图片打包到 WEB-INF 里面的，这样外部报表的内容就渗透到平台代码里面了。建议能加上直接支持 http 或 https 开头的 url 处理为外联图片。或者扩展 ImageProvider 实现一个特殊的图片实现。

**Comment by youseries** [comment]
最新版SNAPSHOT中已支持，请下载测试，谢谢。
