### ISSUE TITLE
查询表单“复选框”组件“的选项值支持从数据集中动态加载

### ISSUE THREAD

**Issue by howell86** [youseries/ureport#132]
如题，希望能增加这样的功能~

**Comment by youseries** [comment]
2.2.4-SNAPSHOT中已对列表选择框添加此功能
![s](https://user-images.githubusercontent.com/29193502/33983481-5bbadd20-e0ef-11e7-8432-dc84a47ecdd9.png)

**Comment by howell86** [comment]
谢谢~希望这个开源项目变得越来越有价值

**Comment by howell86** [comment]
测试了下，有些问题：
1、还不支持复选框；
2、支持“单选列表框”，测试配置了两个数据源，第1个数据源3个数据集，第2个数据源1个数据集，发现配置多个“单选列表框”时，可以选择不同数据集，但是“显示值字段名”和“实际值字段名”一直都是第2个数据源数据集的字段名。
