### ISSUE TITLE
建议给单元格设置属性的效果是覆盖当前效果，而不是完全重新设置。

### ISSUE THREAD

**Issue by yingw** [youseries/ureport#134]
解释：
如果单元格设置了字形、大小、背景色、线条，然后希望在特定条件下设置特定的样式（比如选中效果、单双行高亮），需要在条件属性里设置条件及对应的样式。

但是此样式是需要完整设置这个单元格，也就说不需要变化的样式如字形、大小、线条也都需要和原来一样设置一遍，而一般我们可能就是修改一个背景色而已（请参考Excel的条件格式-规则）

建议：
条件格式里面设置的样式是用来覆盖设计器上原来的设置。这样就可以省去很多设置的工作了。

**Comment by youseries** [comment]
没看懂。

**Comment by yingw** [comment]
补充说明：
就是给条件属性设置的属性不是覆盖单元格现有设计器上设置好的属性的，这样设计工作量很大。

比方一个单元格设置了 雅黑、20、蓝底，希望增加一个条件属性在特定情况下显示黄底，需要设置条件属性里：雅黑、20、黄底，而不是只设置一个蓝底，否则字体和大小就会变成默认的，这样调整基础格式的时候不方便。

**Comment by youseries** [comment]
是BUG，前景色和字体因默认值导致，已修复，请更新最新的SNAPSHOT测试，谢谢。

**Comment by yingw** [comment]
嗯，谢谢
