### ISSUE TITLE
定时刷新和页面参数冲突

### ISSUE THREAD

**Issue by yingw** [youseries/ureport#135]
在设置了页面参数到数据集sql上之后，如果设置数据集定时刷新，会出现把参数当成文件名传到后台去读数的bug，导致文件读不到
![image](https://user-images.githubusercontent.com/1177503/33773597-6aabc6bc-dc73-11e7-91a0-d0d808b6365f.png)

**Comment by youseries** [comment]
最新版的SNAPSHOT中已修复，请更新测试，谢谢。
