### ISSUE TITLE
页面自动刷新功能不记录查询表单里面设置的参数

### ISSUE THREAD

**Issue by yingw** [youseries/ureport#138]
1.当前使用的UReport的具体版本号：

2.2.4 snapshot

2.遇到的问题描述：

2.2.4 snapshop 里的查询表单现在下拉列表的确可以作为参数影响sql了（2.2.3不起作用）。但是又出来个老问题就是如果设置了页面刷新频率，就会自动跳回到参数的默认值去了，当前选的值就不起作用了

3.涉及到的异常信息（完整异常信息）：

没有异常

4.相关截图：

**Comment by youseries** [comment]
已修复，请更新最新的SNAPSHOT测试，谢谢。
