### ISSUE TITLE
报表中从数据库获取的值‘‘<hr>’’默认进行了转义，能否不进行转义.

### ISSUE THREAD

**Issue by wuyi5630** [youseries/ureport#139]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

1.当前使用的UReport的具体版本号：

2.2.3

2.遇到的问题描述：

报表中从数据库获取的值‘‘\<hr\>’’默认进行了转义，能否不进行转义,我们就是要hr的效果。

**Comment by youseries** [comment]
必须要转义。
