### ISSUE TITLE
报表导出到word，打开word不能正常显示报表内容，

### ISSUE THREAD

**Issue by simon1026** [youseries/ureport#140]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

1.当前使用的UReport的具体版本号：2.2.4-SNAPSHOT

2.遇到的问题描述：
报表导出到word，打开word不能正常显示报表内容，
导出到pdf却是能正常显示表示的内容

3.涉及到的异常信息（完整异常信息）：

4.相关截图：
office 2007 word 打开
<img width="457" alt="_20171218114928" src="https://user-images.githubusercontent.com/7332436/34089212-87f0d2da-e3e9-11e7-92d4-a6108d337e2d.png">

wps 打开word文件
![1](https://user-images.githubusercontent.com/7332436/34088789-bf9b5e38-e3e6-11e7-99c5-c8b94d952f90.png)
pdf文件打开
![2](https://user-images.githubusercontent.com/7332436/34088796-cc96e95e-e3e6-11e7-8d22-a77192fd3beb.jpg)

**Comment by youseries** [comment]
office需要2012或以上版本，同时不支持wps

**Comment by simon1026** [comment]
测试office2010以上就可以了
