### ISSUE TITLE
浮点数在导出的Excel报表里偏移

### ISSUE THREAD

**Issue by wuyadong** [youseries/ureport#141]
1.当前使用的UReport的具体版本号：
2.2.3

2.遇到的问题描述：
Decimal数据类型求和后，如果小数点后有值，在html预览界面数据正常。在导出的报表中数据发生漂移。
![image](https://user-images.githubusercontent.com/1622276/34098355-eab3b0cc-e416-11e7-81bf-d445fc29f407.png)
![image](https://user-images.githubusercontent.com/1622276/34098361-f8806790-e416-11e7-84fc-49e47845fb80.png)

如果采用格式化，`#.##`可以保证导出的数据显示正确，但格式是字符串的，对后续处理有点麻烦，要手动修改格式。

**Comment by youseries** [comment]
已处理，请更新最新的2.2.4-SNAPSHOT测试，谢谢。
