### ISSUE TITLE
图片 http url 可否支持 https

### ISSUE THREAD

**Issue by yingw** [youseries/ureport#142]
目前图片外联可以支持 http 图片的 url 了，但是对于做了自动 https 跳转的网站图片来说不适用，会报错：

` Unsupport image path :https://www.xxx.cn/yhjl-logo.png`

能否加上 https 的支持，如果我们自己内部解决了跨域问题的话。

**Comment by youseries** [comment]
目前不支持https

**Comment by youseries** [comment]
已添加支持https开头的图片加载功能，请更新最新的SNAPSHOT测试。
