### ISSUE TITLE
Report cells has cyclic dependency.

### ISSUE THREAD

**Issue by yandixuan** [youseries/ureport#147]
*  #### 当前使用的UReport的具体版本号：2.2.3

*  #### 遇到的问题描述：2列相同的sum列 小计 类型小计 总计 上父格都是同一个
    
![image](https://user-images.githubusercontent.com/23276822/34332284-eb5a5b18-e969-11e7-8f22-3455720e6a0c.png)

![image](https://user-images.githubusercontent.com/23276822/34332270-d266191c-e969-11e7-8fbc-75c4f5f9dee0.png)

![image](https://user-images.githubusercontent.com/23276822/34332291-fc5a428e-e969-11e7-948a-a5d35f289734.png)

*  #### 涉及到的异常信息（完整异常信息）：
com.bstek.ureport.exception.CellDependencyException: Report cells has cyclic dependency.

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/23276822/34332301-153d5c82-e96a-11e7-8b42-027aeb526080.png)

**Comment by youseries** [comment]
异常的意思是存在循环依赖。
你模版中除了自定义这几个sum函数所在单元格的父格外，还定义了其它单元格的父格吗？如果有完整截图上来说明。

**Comment by yandixuan** [comment]
@youseries 
就是我每个L,M的SUM 引用的都是同一个上父格L2,M2
后来我把sum(L4)的上父格设置成L3 依此类推 解决了。。

**Comment by youseries** [comment]
好
