### ISSUE TITLE
导出Word格式不正确

### ISSUE THREAD

**Issue by liqiaolin520** [youseries/ureport#148]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.4-SNAPSHOT

*  #### 遇到的问题描述：
批量打印(就是视频中那个主从表的案例)，
导出PDF、直接打印 和 Word的格式不同

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
 这个是直接打印视图的签名栏
![image](https://user-images.githubusercontent.com/32925394/34334076-28d6b784-e97e-11e7-997a-5fda59dfb831.png)
这个是导出PDF的签名栏
![image](https://user-images.githubusercontent.com/32925394/34334101-73192840-e97e-11e7-977d-40a8f2afba0c.png)
这个是Word的..... 很糟糕
只有第一个是好的，其余的签名栏都乱七八糟的
![image](https://user-images.githubusercontent.com/32925394/34334140-dc43ffde-e97e-11e7-8069-4758deff38e9.png)
![image](https://user-images.githubusercontent.com/32925394/34334143-e8f4d262-e97e-11e7-94f8-5d42bf46952f.png)
![image](https://user-images.githubusercontent.com/32925394/34334118-97920b92-e97e-11e7-8476-f56f5bbdf46d.png)

**Comment by youseries** [comment]
word需要2010或以上版本，同时不支持wps，你用的是什么版本？

**Comment by liqiaolin520** [comment]
office 2016 不可能做这种小学生的操作把....就是显示的不好看

**Comment by youseries** [comment]
什么意思？

**Comment by liqiaolin520** [comment]
就是说不可能是这种小毛病啊..... 可能是框架导出时逻辑问题把，反正在这里描述描述不太明白...

**Comment by youseries** [comment]
如果你的word是2010或以上版本那就是对的，word导出来就这样！

**Comment by liqiaolin520** [comment]
行吧，我感觉提Issue没啥用，问题不但没解决，还要等待....
