### ISSUE TITLE
从两个数据集中获取的数据在一个框中显示

### ISSUE THREAD

**Issue by lili1234** [youseries/ureport#149]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.0

*  #### 遇到的问题描述：
从两个数据集查询的出来的count数据想在一个单元格中显示，两个数据集各自的查询条件怎么写

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![qq 20171225154959](https://user-images.githubusercontent.com/20632556/34335644-58369046-e98b-11e7-8101-cdccb5b700fc.png)

**Comment by youseries** [comment]
首先需要搞清楚，phj数据集与qy数据集有什么关系，通过什么字符连接的，请辅以截图描述清楚。
