### ISSUE TITLE
com.bstek.ureport.exception.ConvertException: Can not convert 3,3,3,3,3,3,2,2,2,2,2,2,2,2,2,2,2,2 to BigDecimal.

### ISSUE THREAD

**Issue by wyubaoyuan** [youseries/ureport#15]
com.bstek.ureport.exception.ConvertException: Can not convert 3,3,3,3,3,3,2,2,2,2,2,2,2,2,2,2,2,2 to BigDecimal.

**Comment by youseries** [comment]
你写了什么？截个图上来看看！

**Comment by wyubaoyuan** [comment]
xly_statistics_stock.select(QTY)*C6*0.64

**Comment by youseries** [comment]
说明你的xly_statistics_stock.select(QTY)表达式取到的值有多个，具体来说就是 3,3,3,3,3,3,2,2,2,2,2,2,2,2,2,2,2,2，引擎尝试将这些值转换成数字报错。

**Comment by wyubaoyuan** [comment]
哦，明白了，那就是要用分组xly_statistics_stock.group(QTY)可以了

**Comment by hexiangzhi9423** [comment]
多行的时候，判断父格的A大于B,表达式怎么写？
