### ISSUE TITLE
针对您给的解决方案还是不会配，希望直接把配置文件粘给我

### ISSUE THREAD

**Issue by HyacinthDn** [youseries/ureport#150]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.3

*  #### 遇到的问题描述：
针对您给的解决方案还是不会配，希望直接把配置文件粘给我。

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
导致此问题的原因是你项目中也配置了spring的properties配置文件，同时默认情况下，你项目中配置的这个properties文件加载优化级较高，也就是spring会首先加载这个文件，这样在加载完这个文件后因找不到ureport中需要的属性信息所以就报错，这个spring加载properties文件机制导致，解决办法如下：

关于Properties文件加载
如果你是将UReport配置到一个已存在的Spring项目中，同时项目也要Spring中加载自己的Properties文件，比如通过下面的方式加载自己的Properties文件
<context:property-placeholder location="/WEB-INF/app.properties"/>
这时启动应用，我们会发现启动过程中系统会报各种属性找不到的异常，解决办法就是在上面配置中加上 ignore-unresolvable="true" 以及 order="1" 两个属性即可，其中ignore-unresolvable属性表达忽略当前配置的Properties文件中没有配置的属性，order属性值表示加载优先级，值越小，优先级越高。
当然如果你的项目中Properties文件加载是通过配置PropertyPlaceholderConfigurer为bean的方式加载，那么同样需要为这个bean添加如下两个属性，作用也是一样：
<property name="ignoreUnresolvablePlaceholders" value="true"></property> <property name="order" value="1"></property>
详细描述见文档：http://wiki.bsdn.org/pages/viewpage.action?pageId=76448360

**Comment by youseries** [comment]
我觉得说的很清楚了，如果你还是不懂，可以尝试与我公司销售联系（www.bstek.com），通过购买服务还解决，这里只能帮你这些。
