### ISSUE TITLE
报表导出excel小数点进度过长

### ISSUE THREAD

**Issue by MengFeiF** [youseries/ureport#151]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：2.2.3

*  #### 遇到的问题描述：
报表导出excel小数点显示不正常

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/32830196/34338075-e572ffbc-e99f-11e7-8e72-651986612f54.png)
![image](https://user-images.githubusercontent.com/32830196/34338106-4488df94-e9a0-11e7-8b1f-8fe22b5f3d08.png)

**Comment by youseries** [comment]
更新到最新的2.2.4-SNAPSHOT试试。
