### ISSUE TITLE
按照文档配置修改了ureport2的默认存储路径但是无效

### ISSUE THREAD

**Issue by gaoheng1994** [youseries/ureport#154]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.3

#### 遇到的问题描述：
我是用tomcat启动项目服务的，所以无法自动生成ureportfiles这个文件夹，于是按照文档自己手动添加了配置修改默认的存储报表xml文件的路径，但是启动服务后却无效，文件依然保存在临时工作目录下，该怎么解决

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/34851939/34350547-566ce7e8-ea52-11e7-8537-20fb5211410f.png)

**Comment by youseries** [comment]
你配置的这个目录在运行时就是临时目录，所以需要改成真实存在目录，比如在E盘下创建一个名为ureportfiles目录，然后设置目录为：E:/ureportfiles

**Comment by gaoheng1994** [comment]
我上传的截图是已经改了的，在config.properties里把路径改成了E盘下的项目里的ureportfiles，而且事先我也建好了这个文件夹，在context.xml里也按照文档加了那个bean的配置，但是启动项目后，保存报表文件的时候它还是保存在了tomcat的那个临时目录下面，而不是我的真实目录。
