### ISSUE TITLE
报表设计器界面无法打开

### ISSUE THREAD

**Issue by HyacinthDn** [youseries/ureport#157]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.3

*  #### 遇到的问题描述：
报表设计器界面无法打开

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/27839064/34352489-c8376bea-ea5d-11e7-9e77-e0169f4f5ac3.png)

**Comment by youseries** [comment]
出现这个问题可能性只能两种：

-  一种是ureport的spring配置文件未加载
-  另一种就是ureport的spring配置文件未加载到标准的spring context，这种情况下多出在你项目中使用spring mvc的时候，也就是说你把ureport的spring配置文件加载到spring mvc的context中了，所以导致上述错误。

**Comment by HyacinthDn** [comment]
我知道了！是配置文件没有加载！因为控制台没出现那个ureport的图！



hyacinth_han@163.com
 
发件人： 高杰
发送时间： 2017-12-27 10:11
收件人： youseries/ureport
抄送： HyacinthDn; Author
主题： Re: [youseries/ureport] 报表设计器界面无法打开 (#157)
出现这个问题可能性只能两种：
一种是ureport的spring配置文件未加载
另一种就是ureport的spring配置文件未加载到标准的spring context，这种情况下多出在你项目中使用spring mvc的时候，也就是说你把ureport的spring配置文件加载到spring mvc的context中了，所以导致上述错误。
―
