### ISSUE TITLE
第一个规则中参数赋值后，后面的规则参数和数值比较有问题。

### ISSUE THREAD

**Issue by jianjian0814** [youseries/ureport#158]
![1](https://user-images.githubusercontent.com/24446722/34352618-acf36d06-ea5e-11e7-86c7-ae99cec009d2.png)

第一个规则中参数赋值后，后面的规则参数和数值比较有问题，但是规则输出那可以拿到值。

帮忙给看看，谢谢。

**Comment by youseries** [comment]
urule问题，请提到[urule的issue](https://github.com/youseries/urule/issues)，谢谢。
