### ISSUE TITLE
com.bstek.ureport.Utils无法动态新增BuildinDatasource对象

### ISSUE THREAD

**Issue by wendal** [youseries/ureport#159]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.3

*  #### 遇到的问题描述：
com.bstek.ureport.Utils的buildinDatasources属性是不可修改的集合,没法修改

建议改成:

```java
buildinDatasources= new ArrayList<>(applicationContext.getBeansOfType(BuildinDatasource.class).values());
```
同理,ImageProvider也是

*  #### 涉及到的异常信息（完整异常信息）：
无

*  #### 相关截图：
无

**Comment by youseries** [comment]
最新的2.2.4-SNAPSHOT中已处理，谢谢。
