### ISSUE TITLE
ureport2源码项目里面的ureport2-core包更新不下来

### ISSUE THREAD

**Issue by coolead** [youseries/ureport#161]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.0.4

*  #### 遇到的问题描述：

ureport2-core的2.2.4-SNAPSHOT版本更新不下来

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
SNAPSHOT版本更新见文档：http://wiki.bsdn.org/pages/viewpage.action?pageId=76448360
