### ISSUE TITLE
报表查询表单设计bug

### ISSUE THREAD

**Issue by quqiangsheng** [youseries/ureport#164]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.4-SNAPSHOT

*  #### 遇到的问题描述：

三个问题
1.当设计查询表单时 使用日期选择框 日期格式有两种选择yyyy-mm-dd 和yyyy-mm-dd hh:ii:ss
 当使用后者时更改后退出表单设计器再进去表单设计器 又会被更改为第一种yyyy-mm-dd丢失掉了时分秒信息 
2当只是用第一种yyyy-mm-dd时间选择器时 js控件还要选择时分秒 希望改进下 并且更换一个中文的日期时间选择器，毕竟用户是非常具有中国特色的... 或者做成国际化的 根据地区使用不同的语言风格
3当我有多个数据源时 不同的数据源可能都需要传入一个时间范围参数 在表单设计绑定参数时 没法区分出这个参数是用于哪个数据集的 如果这个参数还是重名的话 看着比较不清晰，还有一种需求，比如查询表单里输入一个时间范围  我的多个数据源的sql语句都想使用这个范围参数  希望这个参数绑定可以一对多 避免重复绑定 建议可以在绑定参数时下拉框中按住ctrl+左键多选 绑定参数 不知可否实现 
调试发现点击查询发送的请求中 后边定义的重名参数 不会被绑定发送给后台 应该把参数归于不同的数据集下吧 我看生成的报表xml也是sql参数在不同的数据集下有定义 但是在请求报表url参数时 并没有限定在哪个数据集下  就成了全局参数了  这应该不是设计的初衷

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

![qq 20171227142446](https://user-images.githubusercontent.com/9816930/34373353-826e2942-eb15-11e7-8083-1f64d9497bc5.jpg)

**Comment by youseries** [comment]
1.日期选择及中文显示问题已处理，可更新最新版snapshot测试。
2.3问题属于同一类，多个数据集在定义参数时参数名要唯一，当初就这么设计的。

**Comment by quqiangsheng** [comment]
1 最新版好像没有发布上 截止到20171230 14:23
Repository Path:
/com/bstek/ureport/ureport2-console/2.2.4-SNAPSHOT/ureport2-console-2.2.4-20171229.045011-10.jar
Uploaded by:
anonymous
Size:
1.68 MB
Uploaded Date:
Fri Dec 29 2017 12:50:20 GMT+0800 (ä¸­å½æ åæ¶é´)
Last Modified:
Fri Dec 29 2017 12:50:20 GMT+0800 (ä¸­å½æ åæ¶é´)

还是没看到效果

2参数名唯一理解了
