### ISSUE TITLE
SQL表达式中使用mysql的IFNULL() 函数时出现异常

### ISSUE THREAD

**Issue by reginfos** [youseries/ureport#166]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：2.2.3

*  #### 遇到的问题描述：
在数据集的SQL表达式中使用mysql的IFNULL() 函数时出现异常，
（该SQL可在MYSQL中正常执行）

*  #### 涉及到的异常信息（完整异常信息）：
HTTP Status 500 – Internal Server Error
Type Exception Report

Message javax.servlet.ServletException: java.lang.reflect.InvocationTargetException

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

javax.servlet.ServletException: javax.servlet.ServletException: java.lang.reflect.InvocationTargetException
	com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:93)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:140)
	org.springframework.web.filter.ResouceEncodingFilter.doFilter(ResouceEncodingFilter.java:146)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
Root Cause

javax.servlet.ServletException: java.lang.reflect.InvocationTargetException
	com.bstek.ureport.console.BaseServletAction.invokeMethod(BaseServletAction.java:79)
	com.bstek.ureport.console.designer.DatasourceServletAction.execute(DatasourceServletAction.java:79)
	com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:81)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:140)
	org.springframework.web.filter.ResouceEncodingFilter.doFilter(ResouceEncodingFilter.java:146)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
Root Cause

java.lang.reflect.InvocationTargetException
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	com.bstek.ureport.console.BaseServletAction.invokeMethod(BaseServletAction.java:77)
	com.bstek.ureport.console.designer.DatasourceServletAction.execute(DatasourceServletAction.java:79)
	com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:81)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:140)
	org.springframework.web.filter.ResouceEncodingFilter.doFilter(ResouceEncodingFilter.java:146)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
Root Cause

com.bstek.ureport.exception.ReportParseException: Unknow context :[64]
	com.bstek.ureport.expression.parse.ExpressionVisitor.parseExprComposite(ExpressionVisitor.java:172)
	com.bstek.ureport.expression.parse.ExpressionVisitor.visitExpression(ExpressionVisitor.java:75)
	com.bstek.ureport.expression.ExpressionUtils.parseExpression(ExpressionUtils.java:139)
	com.bstek.ureport.console.designer.DatasourceServletAction.parseSql(DatasourceServletAction.java:280)
	com.bstek.ureport.console.designer.DatasourceServletAction.previewData(DatasourceServletAction.java:234)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	com.bstek.ureport.console.BaseServletAction.invokeMethod(BaseServletAction.java:77)
	com.bstek.ureport.console.designer.DatasourceServletAction.execute(DatasourceServletAction.java:79)
	com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:81)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:140)
	org.springframework.web.filter.ResouceEncodingFilter.doFilter(ResouceEncodingFilter.java:146)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
Note The full stack trace of the root cause is available in the server logs.

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/34904249/34399752-8a22d024-ebc5-11e7-880b-4495664e2774.png)
![image](https://user-images.githubusercontent.com/34904249/34399760-a16b3410-ebc5-11e7-864b-41fbc50e31f2.png)

**Comment by youseries** [comment]
在表达式中，SQL中的单引号需要使用\进行转义，比如你这里的'无'要写成：\'无\'

**Comment by reginfos** [comment]
已解决，未进行转义导致的
