### ISSUE TITLE
ureport2里选择【SpringBean数据源配置】时，表单设计器没有办法传参数

### ISSUE THREAD

**Issue by wsg215** [youseries/ureport#167]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
   ureport2-2.2.3
*  #### 遇到的问题描述：
ureport2里选择【SpringBean数据源配置】时，表单设计器没有办法传参数。选择【SpringBean数据源配置】选项时，没有添加参数功能，而【表单设计器】里的参数需要绑定查询参数，  导致【SpringBean数据源配置】没有使用【表单设计器】功能，希望群主考虑加下这个功能。

*  #### 涉及到的异常信息（完整异常信息）：

无

*  #### 相关截图：
![qq 20171228194123](https://user-images.githubusercontent.com/33387967/34409806-1e3dfd74-ec07-11e7-8baa-91974a4052a5.png)

**Comment by youseries** [comment]
是的，只支持SQL数据集中配置的参数。
