### ISSUE TITLE
设置分栏时分页页数显示错误

### ISSUE THREAD

**Issue by quqiangsheng** [youseries/ureport#168]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.3

*  #### 遇到的问题描述：

当设置报表分栏时 我测试了分两栏 三栏时 前几页显示正确 后边的几页全部重复显示  而且 共几页 第几页 计算结果是错误的 看图

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![01](https://user-images.githubusercontent.com/9816930/34412245-144fbbe4-ec17-11e7-9951-a980a5f727ef.jpg)
![02](https://user-images.githubusercontent.com/9816930/34412246-14a1391a-ec17-11e7-8358-10c3d458734e.jpg)
![03](https://user-images.githubusercontent.com/9816930/34412248-14da96b0-ec17-11e7-8f5b-f315428936fd.jpg)
![04](https://user-images.githubusercontent.com/9816930/34412250-1517281e-ec17-11e7-95a5-b13050fbc460.jpg)
![05](https://user-images.githubusercontent.com/9816930/34412252-15566f06-ec17-11e7-93b8-77fa3bd7ec6b.jpg)
![06](https://user-images.githubusercontent.com/9816930/34412298-59d2931c-ec17-11e7-97ea-215ab4086138.jpg)

数据集是简单的单表内容展示  第一列是行号 
一共54条数据 设置分两栏 不分页时显示正常  分页时  页码显示错误 最后几页错误

**Comment by youseries** [comment]
BUG,已修复，请下载最新的2.2.4-SNAPSHOT测试。

**Comment by quqiangsheng** [comment]
测试已成功 问题解决
