### ISSUE TITLE
导出报表时的报表命名问题

### ISSUE THREAD

**Issue by quqiangsheng** [youseries/ureport#169]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.3

*  #### 遇到的问题描述：

![11](https://user-images.githubusercontent.com/9816930/34412508-a36dbfdc-ec18-11e7-997b-3de9a9eeb648.png)
fileNmae=ureport  这个默认参数 是否可以优化下
 好像前台 
![12](https://user-images.githubusercontent.com/9816930/34412535-cabd5c1e-ec18-11e7-8be7-1df522ffade8.png)
的这些 默认都没有传这个参数 导致下载下来文件明都是 ureport.xxx  建议默认改成 报表名称.xxx 或者报表名称+时间戳.xxx 更有好点吧  虽然 可以自定义实现 这个头 感觉官方默认 这样会更好 一点 
就是在没有传_n参数时  导出文件名用 报表存储的名字 去掉xml后缀作为 导出名字
可以的话 我发个PR

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
已对导出的报表默认文件名进行重定义，还是保留ureport前缀，可以更新最新的SNAPSHOT测试，具体见源码。

**Comment by quqiangsheng** [comment]
测试成功 问题解决
