### ISSUE TITLE
条件中无法两个变量相加

### ISSUE THREAD

**Issue by 15150762026** [youseries/ureport#171]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

*  #### 遇到的问题描述：

条件里面只能是一个变量＋输入值吗，我需要一个变量+另一个变量

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

![g60 y fo4q _8 q jl pj](https://user-images.githubusercontent.com/34929752/34428583-5cea644a-ec89-11e7-926c-ba95ff76545f.png)

**Comment by youseries** [comment]
请在urule的issue里，不要乱提！
