### ISSUE TITLE
条件属性设置背景颜色，预览时字体变大了

### ISSUE THREAD

**Issue by reginfos** [youseries/ureport#172]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：2.2.3

*  #### 遇到的问题描述：
条件属性设置，背景颜色后，预览的时候，该条件行字体变大了，如下图

*  #### 涉及到的异常信息（完整异常信息）：
无 

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/34904249/34433208-c10f6b30-ecb8-11e7-8155-b4d658adb421.png)

![image](https://user-images.githubusercontent.com/34904249/34433433-3a8d0494-ecba-11e7-9764-d3e24db8b66e.png)

**Comment by youseries** [comment]
可以更新到最新的SNAPSHOT看看这个问题是否还有！

**Comment by reginfos** [comment]
已测试，2.2.4-SNAPSHOT 还是存在此问题

**Comment by youseries** [comment]
请再次更新2.2.4-SNAPSHOT 测试，谢谢。
