### ISSUE TITLE
报表导出Excel,日期字段是数字

### ISSUE THREAD

**Issue by azengqiang** [youseries/ureport#173]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2

*  #### 遇到的问题描述：

报表导出Excel的时候，日期字段在导出的Excel中是一个数字。

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![0 mtjal6b5g5p0n 8 sg8uq](https://user-images.githubusercontent.com/18609489/34433464-7d760bf2-ecba-11e7-88de-a3e93350eaa7.png)
![xl4 q ozxmg mvm86lirz_7](https://user-images.githubusercontent.com/18609489/34433465-7da6c382-ecba-11e7-9054-9a98ee9f21bb.png)

**Comment by youseries** [comment]
请使用对应单元格的格式化属性，对日期字段进行格式输出。
