### ISSUE TITLE
设置了几个or条件，只有第一个生效 和

### ISSUE THREAD

**Issue by reginfos** [youseries/ureport#174]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：2.2.3

*  #### 遇到的问题描述：
和issues #101 同样的问题
设置了几个or条件，只有第一个生效 

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/34904249/34433585-59b08084-ecbb-11e7-873b-bd9b8d1008a9.png)

![image](https://user-images.githubusercontent.com/34904249/34433569-499e6d0a-ecbb-11e7-982f-a5c67e236513.png)

![image](https://user-images.githubusercontent.com/34904249/34433595-66b8e6f4-ecbb-11e7-8d7a-8dbce1ed4426.png)

**Comment by youseries** [comment]
最新的snapshot版中已处理，请更新测试。

**Comment by reginfos** [comment]
已测试，2.2.4-SNAPSHOT 中已解决
