### ISSUE TITLE
ureport访问

### ISSUE THREAD

**Issue by JiangChen123** [youseries/ureport#176]
![2](https://user-images.githubusercontent.com/34642654/34472445-ba67ecc0-ef9d-11e7-906e-2281ea3e822f.png)

## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.3-SNAPSHOT
![2](https://user-images.githubusercontent.com/34642654/34472444-b0e4bfb6-ef9d-11e7-8f34-059912f7e636.png)

*  #### 遇到的问题描述：
ureport能够正常启动,但是访问localhost:8080/projectname/ureport/designer###，后台不报错，页面显示
Handler [/designer] not exist.

*  #### 涉及到的异常信息（完整异常信息）：
后台没有异常，能够显示字体

*  #### 相关截图：
![1](https://user-images.githubusercontent.com/34642654/34472419-49dc557c-ef9d-11e7-9049-eff822ffe9f1.png)

**Comment by youseries** [comment]
这个问题多次回答了，是你的项目中未加载ureport2提供的spring配置文件或这个spring配置文件未加载到标准的spring context中(在项目使用spring MVC时常范的问题)，对象文档或视频，看看你错在哪里！
