### ISSUE TITLE
导出pdf中文文字超过单元格的长度被截断

### ISSUE THREAD

**Issue by PattonMao** [youseries/ureport#177]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.3

*  #### 遇到的问题描述：

如题导出pdf中文文字超过单元格的长度被截断，简单搜索了一下可能是因为itextpdf这个依赖包在生成长中文文本时换行没有根据单个字来分隔计算长度。

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/10829540/34473494-770b3ba6-efae-11e7-9c49-44c806dc9c01.png)
![image](https://user-images.githubusercontent.com/10829540/34473505-8918633c-efae-11e7-9493-9e6c39fa916a.png)

**Comment by youseries** [comment]
如果你输出内容为多行文本，那么需要将自动换行功能打开，这个报表会自动计算行高以适应内容。

**Comment by PattonMao** [comment]
请问如何打开自动换行功能呢，我没有找到

**Comment by PattonMao** [comment]
我指的是表达式的用法，数据集那里可以直接设置

**Comment by youseries** [comment]
表达式是没有，我来加一下

**Comment by youseries** [comment]
请更新最新的2.2.4-SNAPSHOT，在此版本中已为表达式添加换行计算选项开关，谢谢。
