### ISSUE TITLE
导出word图片包括图表生成的图片默认放大133%

### ISSUE THREAD

**Issue by PattonMao** [youseries/ureport#178]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.3

*  #### 遇到的问题描述：

如题，导出word图片包括图表生成的图片默认放大133%导致图片大小超过A4范围。PDF中没有此问题。

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
word里面
![image](https://user-images.githubusercontent.com/10829540/34473521-ca3ded28-efae-11e7-9a9d-df4a21e72e63.png)
pdf里面
![image](https://user-images.githubusercontent.com/10829540/34473530-e9e5454a-efae-11e7-8929-73cad3f65e12.png)

**Comment by youseries** [comment]
BUG，最新版SNAPSHOT中已修复，谢谢。
