### ISSUE TITLE
重复表头的问题

### ISSUE THREAD

**Issue by liqiaolin520** [youseries/ureport#180]
**# 版本号：**

   2.2.4-SNAPSHOT

**# 描述：**
 
  我是用的重复表头，可是这个也太不对了把，麻烦您改完后告诉我

**# 截图：**

![image](https://user-images.githubusercontent.com/32925394/34476444-b9089ea0-efcb-11e7-8137-a85cdb9b2975.png)

![image](https://user-images.githubusercontent.com/32925394/34476473-09ad7f92-efcc-11e7-8e7c-a44598475ea7.png)

**Comment by youseries** [comment]
根据你的需求，应该将下图中蓝色线框内对应的行行类型设置为“标题行”，这样你的重复表头第一页就不会位于最上面了。
![aaa](https://user-images.githubusercontent.com/29193502/34512310-81114af2-f09c-11e7-9258-f424de97b110.jpg)
”标题行“含义与作用见文档：http://wiki.bsdn.org/pages/viewpage.action?pageId=76449197

**Comment by liqiaolin520** [comment]
那如果我这个第几页 共几页 要弄到每一页怎么弄呢？
![image](https://user-images.githubusercontent.com/32925394/34547846-08235732-f139-11e7-819d-a6ba3ccdb88f.png)

附上我得报表设计 
![image](https://user-images.githubusercontent.com/32925394/34547869-2b140278-f139-11e7-9a1d-6c87190ca196.png)

**Comment by youseries** [comment]
设置为标题行的行只会出现在第一页最上面。

**Comment by liqiaolin520** [comment]
这是全是标题行的
![image](https://user-images.githubusercontent.com/32925394/34548467-3a77d74a-f13d-11e7-8f80-e117a0dd80e3.png)
![image](https://user-images.githubusercontent.com/32925394/34548474-432f665a-f13d-11e7-930b-42d9220be844.png)


这是这一行为重复表头的

**Comment by liqiaolin520** [comment]
![image](https://user-images.githubusercontent.com/32925394/34548785-edc1e984-f13e-11e7-9ca2-dd2ff7d1b168.png)

![image](https://user-images.githubusercontent.com/32925394/34548789-f2abd432-f13e-11e7-8afa-308fbc52652a.png)

**Comment by youseries** [comment]
目前总页数只能在页眉页脚定义，不过未来可以改进!
