### ISSUE TITLE
建议添加排名函数

### ISSUE THREAD

**Issue by xiaolipost** [youseries/ureport#183]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

版本号：2.2.3

*  #### 遇到的问题描述：
比如A1列显示积分，需求是在B1列显示A1列对应积分排名（名次）。在文档里没有找到相关的排名函数，只找到了order排序函数，而order函数不符合这个需求。

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![tim 20180104143433](https://user-images.githubusercontent.com/35092663/34552464-899ecddc-f15c-11e7-9ddb-a0391da26868.png)

**Comment by youseries** [comment]
排名只能针对某个未展开的数据集字段排序，而不能对某一列数据排序。
所以你应该在取数据时就把积分字段排好序。
