### ISSUE TITLE
分页中合计栏位无法在表格的最后一行

### ISSUE THREAD

**Issue by liqiaolin520** [youseries/ureport#184]
我有一个合计的栏位，用于统计分页所有的数据的金额

![image](https://user-images.githubusercontent.com/32925394/34554863-f4f4e866-f169-11e7-8158-23dd19b6fa12.png)

应该设置到这里，我尝试过标题行与总结行，标题行不行，总结行呢，又在我这里签名的下面，请问下Jack 有什么办法嘛
![image](https://user-images.githubusercontent.com/32925394/34554919-26a44dac-f16a-11e7-96d7-531ef9754ea8.png)

**Comment by liqiaolin520** [comment]
如果不设置任何类型  则。。。
![image](https://user-images.githubusercontent.com/32925394/34555024-ac6b4cd8-f16a-11e7-9885-8026d1f9d892.png)

**Comment by liqiaolin520** [comment]
合计跑到上面去了

**Comment by youseries** [comment]
你这需求很奇怪，我也没有办法！

**Comment by liqiaolin520** [comment]
这 .....................
