### ISSUE TITLE
汉字参数乱码

### ISSUE THREAD

**Issue by carl1207** [youseries/ureport#186]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.3

*  #### 遇到的问题描述：
系统集成时
页面输入的汉字查询条件，在ureport解析到的参数为乱码

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
中文参数放在URL后面传递需要先进行encode。
