### ISSUE TITLE
select在集合中的过滤条件没起作用

### ISSUE THREAD

**Issue by Janch-Zhaodw** [youseries/ureport#187]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
ureport2-console 2.2.3
*  #### 遇到的问题描述：
主从表通过topic_id关联查询显示名称的时候，在集合中的过滤条件没起作用，只有等于A1的时候起作用了

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
<img width="1130" alt="qq20180104-184939 2x" src="https://user-images.githubusercontent.com/32115566/34560266-1d851ef2-f180-11e7-8cbd-dad96f826359.png">
预览只显示了topic_id值，对应从表的数据没有显示：
<img width="380" alt="qq20180104-185100 2x" src="https://user-images.githubusercontent.com/32115566/34560307-3e837360-f180-11e7-9099-b59b480a07b6.png">

**Comment by youseries** [comment]
我这里是好的，你可以更新最新的SNAPSHOT试试。

**Comment by Janch-Zhaodw** [comment]
已经换成最新的SNAPSHOT的了，还是不行，通过left join或是过滤条件设置为等于A1单位格的时候都是可以，只有条件设置为在集合中不行

**Comment by Janch-Zhaodw** [comment]
设置这种主从关联查询的主从表我刚加了外键关系，然后设置条件为“在集合中”的时候就是对的了

**Comment by youseries** [comment]
好
