### ISSUE TITLE
abs公式异常

### ISSUE THREAD

**Issue by niuey2001** [youseries/ureport#188]
![17e k3wc6dj295rj7uz1v3](https://user-images.githubusercontent.com/28522091/34593626-f9ae474e-f1c3-11e7-949f-b5ac7d3460b2.jpg)
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.1.5

*  #### 遇到的问题描述：
表达式  1- abs( (D4 - B4 ) / B4)  报错
表达式  1-abs(D4/B4 -1 ) 后面的 -1 不生效

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
减号前后要有空格。
