### ISSUE TITLE
是否支持sql嵌套了，例如

### ISSUE THREAD

**Issue by smile2014** [youseries/ureport#189]
$(select * from  a where 1=1
  if(param(xxx)!=null{
   and a.x='xxxx'
  }
}

**Comment by smile2014** [comment]
$(select * from a where 1=1
    if(param(xxx)!=null{
       and a.x='xxxx'
    }
}

**Comment by youseries** [comment]
你写法不对，比如你上面的SQL可以写成下面这样：
select * from a where 1=1
$(if(param(xxx)!=null{and a.x='xxxx'}}

**Comment by smile2014** [comment]
@youseries  谢谢了，这种现在高版本是支持的吧
select * from a where 1=1
$(if(param(xxx)!=null{
return "and a.x='xxxx'"
}}
$(if(param(yyy)!=null{
return "and a.y='yyy'"
}}

**Comment by youseries** [comment]
2.2.4就支持。
