### ISSUE TITLE
图表是否能使用Echart

### ISSUE THREAD

**Issue by siye1103** [youseries/ureport#190]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.4

*  #### 遇到的问题描述：

图表显示美观和地图展示，是否可以使用Echart作为图形展示

*  #### 涉及到的异常信息（完整异常信息）：
无

*  #### 相关截图：

**Comment by youseries** [comment]
不支持echart，抱歉！
