### ISSUE TITLE
工具栏不固定与纸张宽度

### ISSUE THREAD

**Issue by liqiaolin520** [youseries/ureport#191]
![image](https://user-images.githubusercontent.com/32925394/34708717-f692b412-f54e-11e7-8094-047e28113d2c.png)

希望这个工具栏固定，然后那个纸张宽度标识能延长，

**Comment by youseries** [comment]
最新的ureport2-console-2.2.5-SNAPSHOT中已做调整，请更新测试，谢谢。

**Comment by liqiaolin520** [comment]
叼哦，Jack哥
