### ISSUE TITLE
多行合并标题行时，斜线表头的斜线不够美观

### ISSUE THREAD

**Issue by zhangsean** [youseries/ureport#192]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
UReport v2.2.4

*  #### 遇到的问题描述：
多行合并标题行时，斜线表头的斜线不够美观，第二个斜线没有对着表格框线交叉处，压着第二组文字了。
手动点击刷新也不能自动调整。

*  #### 涉及到的异常信息（完整异常信息）：
无

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/2536402/34709401-10bef0a0-f552-11e7-8248-e6bf5c799a31.png)

**Comment by youseries** [comment]
在添加斜表头后，如果对当前单元格进行了合并行列操作，那么需要清空当前单元格的斜表头，重新添加斜表头，否则就会出现你现在的问题。

**Comment by zhangsean** [comment]
我就是先合并两行标题行，然后添加斜线表头的，然而不管有没有手动刷新，斜线的位置都是如图那样的。
