### ISSUE TITLE
如何将某列按照前列的分组规则进行合并

### ISSUE THREAD

**Issue by guolk** [youseries/ureport#193]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

*  #### 遇到的问题描述：
如何将备注这一列按照A列的分组将单元格合并

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![image](https:
![8 byj 2xknb 18x7 ro4by](https://user-images.githubusercontent.com/34366367/34709415-1dcb4000-f552-11e7-863f-6c9f4e478063.png)
//user-images.githubusercontent.com/34366367/34709383-f9e19888-f551-11e7-9714-b27ef5fd7e96.png)

**Comment by youseries** [comment]
那很简单，那就是将这个备注单元格设置左父格设置为a列即可，具体原理看视频，理解了单元格迭代原理，你就懂了。

**Comment by guolk** [comment]
![3_n026 hw z xpo lr xj](https://user-images.githubusercontent.com/34366367/34856161-8fc30f84-f77e-11e7-8f0d-baaf57fb3efe.png)


![sm q x64mhr z u cxrv5](https://user-images.githubusercontent.com/34366367/34856138-6ffa944c-f77e-11e7-97a3-e554bfa5207f.png)
我按照你说的方法试了还是不行

**Comment by YongQiangKuang** [comment]
我也测试了，不行。。。。
