### ISSUE TITLE
两行向右展开的数据，展开位置不正确

### ISSUE THREAD

**Issue by xuexiaoao** [youseries/ureport#196]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.5

*  #### 遇到的问题描述：
两行向右展开的数据，展开的位置不正确，见下图
我设置第二个单元格的上父格为第一个单元格，展开的位置也不正确
我想要的效果是这两行数据的位置是一样的

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![r6_n 0t o6yh y jm1cm_o](https://user-images.githubusercontent.com/18185523/34752526-c63ca184-f5ed-11e7-857b-8413e753339d.png)
![d6rqoxobgs1p0iphck2dmlq](https://user-images.githubusercontent.com/18185523/34752529-cd5e1506-f5ed-11e7-8867-f21a785448d3.png)
![pn 1xi5t 27emvj561x vm](https://user-images.githubusercontent.com/18185523/34752532-d1ae206a-f5ed-11e7-9840-4bccdabcbb25.png)

**Comment by youseries** [comment]
是对的，只是你不理解单元格迭代的模型，所以觉得不对，建议好好完整看看视频教程先。
