### ISSUE TITLE
通过 ExportMananger 导出含图表的PDF报表，图表显示不出来

### ISSUE THREAD

**Issue by yingw** [youseries/ureport#199]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.4

*  #### 遇到的问题描述：
在线预览和下载PDF的时候，都好好的报表，里面含有图表。但是用 ExportMananger 导出来的，就只有表格，没有图表的

部分代码：
```
    @Autowired
    ExportManager exportManager;

exportManager.exportPdf(new ExportConfigureImpl("database:" + job.getReport().getFileName(), new HashMap<>(), outputStream));
```

*  #### 涉及到的异常信息（完整异常信息）：
没有异常

*  #### 相关截图：
正常：（从预览、下载、在线打印预览）
![image](https://user-images.githubusercontent.com/1177503/34791398-cffc3dbe-f67f-11e7-89ac-a1090f3fec08.png)

不正常：（通过 ExportMananger 导出的）
![image](https://user-images.githubusercontent.com/1177503/34791417-dd7ccf76-f67f-11e7-8ba6-748c9e0598c8.png)

**Comment by youseries** [comment]
是的，图表必须要经过浏览器渲染才能导出，这个在文档及视频有均有介绍。
