### ISSUE TITLE
ureport2导出报表时,报表修改默认名字问题

### ISSUE THREAD

**Issue by ljc818** [youseries/ureport#2]
http://host[:port][/context-path]/ureport/excel?_u=报表名称
这个_n加在哪里
预览,导出,这些url在项目中具体是怎么应用的,能不能举个例子.
我们一般会在预览的时候选择导出报表,这个(url)怎么改?我想使用我自己的报表名字

**Comment by youseries** [comment]
给你举个例子，比如导出test.ureport.xml这个模版的excel文件的URL为：http://localhost:8080/ureport2-sample/ureport/excel?_u=file:test.ureport.xml，这样导出的excel的默认文件名为ureport.xlsx，如果你不想采用这个名称，那么可以在这个URL后面加上_n参数，比如：http://localhost:8080/ureport2-sample/ureport/excel?_u=file:test.ureport.xml&_n=myreport.xlsx，这样导出的excel文件名就是myreport.xlsx；依次类推，导出pdf,word也是一样加_n参数。

**Comment by ljc818** [comment]
我们一般会在预览的时候选择导出报表，这个（URL）怎么改？我想使用我自己的报表名字
