### ISSUE TITLE
能直接对 数据集中的字段求和吗？

### ISSUE THREAD

**Issue by wyubaoyuan** [youseries/ureport#20]

**Comment by youseries** [comment]
可以，见：http://wiki.bsdn.org/pages/viewpage.action?pageId=76448569中数据集表达式：sum介绍

**Comment by wyubaoyuan** [comment]
sum(xly_statistics_stock.select(QTY))这样不行

**Comment by wyubaoyuan** [comment]
数值一直是0，但明明这个字段不为0

**Comment by youseries** [comment]
正确的写法是：xly_statistics_stock.sum(QTY)

**Comment by youseries** [comment]
最新的2.0.8-SNAPSHOT也支持sum(xly_statistics_stock.select(QTY))这样的写法，请测试。

**Comment by wyubaoyuan** [comment]
v_warerecord.sum(gradesA*QTY)这样报错

**Comment by youseries** [comment]
v_warerecord.sum(gradesA*QTY) 这是什么意思？两个属性相乘？ureport2可不支持这种写法，如果是，那正解的写法应该是：
`v_warerecord.sum(gradesA) * v_warerecord.sum(QTY)`
还是先好好了解下ureport2表达式语法，不能乱来！

**Comment by wyubaoyuan** [comment]
v_warerecord.sum(gradesA) * v_warerecord.sum(QTY)这样达不到我的需求，我需要每条记录里的gradesA、QTY这两个字段相乘，再求和

**Comment by youseries** [comment]
嗯，UReport2不支持这么做。
不过你可以在SQL里把这两个属性相乘，以别名形式输出，再在报表里对这个别名求和。

**Comment by wyubaoyuan** [comment]
嗯，已经这样处理了

**Comment by xsl9527-didi** [comment]
> 可以，见：[http://wiki.bsdn.org/pages/viewpage.action?pageId=76448569中数据集表达式：sum介绍](http://wiki.bsdn.org/pages/viewpage.action?pageId=76448569%E4%B8%AD%E6%95%B0%E6%8D%AE%E9%9B%86%E8%A1%A8%E8%BE%BE%E5%BC%8F%EF%BC%9Asum%E4%BB%8B%E7%BB%8D)

404
