### ISSUE TITLE
请问下数据集中怎么通过表达式实现动态sql？

### ISSUE THREAD

**Issue by xuanyuan000000** [youseries/ureport#200]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.4

*  #### 遇到的问题描述：
请问下数据集中怎么通过表达式实现动态sql？如id和name都可能不作为参数的。
select * from user where id=:id and name=:name order by id
我希望能根据是否传了参数分别实现
select * from user  order by id
select * from user where id=:id order by id
select * from user where name=:name order by id
select * from user where id=:id and name=:name order by id

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
可以采用嵌入表达式方式进行SQL拼装，比如：
select * from user where 1=1
${empty("id")==true ? "" ? " and id=:id"}
${empty("name")==true ? "" ? " and name=:name"}
 order by id

**Comment by xuanyuan000000** [comment]
在某些低版本的数据库中，1=1是利用不上索引的，会影响性能，所以想看下有无其它办法

**Comment by youseries** [comment]
不想加1=1，你可以在拼SQL层面运动脑子，具体自己弄吧。
