### ISSUE TITLE
UReport2单元格计算总数报错

### ISSUE THREAD

**Issue by liangshuiwang** [youseries/ureport#202]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：2.2.4

*  #### 遇到的问题描述：
比如：单元格C2是单价，D2是数量，现在要计算单价*数量的结果放在B2，我B2的表达式写法为：C2*D2，但是运行时出现如下报错。

*  #### 涉及到的异常信息（完整异常信息）：
![image](https://user-images.githubusercontent.com/30248590/34855570-638e477e-f77b-11e7-9048-90a3d01f9288.png)

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/30248590/34855646-d248bd5c-f77b-11e7-8ea4-ff9dd2b0706e.png)

**Comment by youseries** [comment]
异常提示很明显了，你单元格存在循环依赖的情况，以你这里为例：
你的B2单元格表达式是C2*D2，而C2的左父格就是B2，也就是B2计算完了才能算C2，而B2里又用到C2的值值 ...，所以这就是一个典型的循环依赖配置错误 。
