### ISSUE TITLE
左幅格是合并的继承没用

### ISSUE THREAD

**Issue by wj1222** [youseries/ureport#203]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.4

*  #### 遇到的问题描述：
左幅格是合并的并且是分组的继承没用,

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

![image](https://user-images.githubusercontent.com/15087774/34859371-befafd36-f790-11e7-8d69-9c9093d795d7.png)
![image](https://user-images.githubusercontent.com/15087774/34859378-c7541b3e-f790-11e7-8749-a8eafd0ae53a.png)

**Comment by youseries** [comment]
没看懂。

**Comment by wj1222** [comment]
画红框的（G5）（H5）地方应该是根据前一列进行合并的，但是没有

**Comment by youseries** [comment]
你左父格设置不对，针对你的需求应该将G5左父格设置为无，H5左父格设置为默认，同时A5左父格设置为G5，这样就可以实现你想要的合并效果，但统计值可能又不正确了，这就需要你进一步理解父格依赖关系在做进一步调整。
