### ISSUE TITLE
建议增加功能：设置了报表刷新后，异常后继续刷新并且在数据恢复后关闭提示框

### ISSUE THREAD

**Issue by yingw** [youseries/ureport#204]
*  #### 当前使用的UReport的具体版本号：
2.2.4

*  #### 遇到的问题描述：
建议增加功能：设置了报表刷新后，后台异常时会在前台提示一个错误的提示框，建议异常后继续刷新并且在数据恢复后关闭提示框。

刷新功能在网络有问题的时候就弹出一个错误提示，而且即使网络恢复，这个窗口也不会自动关闭。因为我们现在拿ureport当生产线看板用的，设置了30秒刷新一次，发现只要用户网络稍微有问题，这个报表一旦报错后，就不会再发起刷新数据请求了（F12查看，不再发起 loadData请求，手动关闭提示框后也不会），后面即使网络好了，也一直提示那个错误，就需要管理员去现场手动刷新一下页面或者重新打开。建议在设置自动刷新的报表后台发生异常时，继续读取 loadData 数据，有错误不需要覆盖上一个错误对话框，如果恢复关闭对话框刷新数据。

还有个问题类似的就是每次要发布就要重新刷新页面

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
最新的2.2.5-SNAPSHOT已做处理，请更新测试。
