### ISSUE TITLE
建议增加功能：自动刷新能获取到最新刷新率值。

### ISSUE THREAD

**Issue by yingw** [youseries/ureport#205]
*  #### 当前使用的UReport的具体版本号：
2.2.4

*  #### 遇到的问题描述：
建议增加在自动刷新的报表上能读取到最新设置的刷新频率。目前设置了刷新频率后，一旦打开报表就只能读到最新的报表数据，但是修改了刷新频率是无效的，这在某些场景下就需要重新打开报表显示才能获取刷新率。比如数据库性能压力大，调试，发布的时候。

**Comment by youseries** [comment]
这个实现不了。
