### ISSUE TITLE
多行合并标题行时，斜线表头的斜线不够美观，建议增加自定义斜线角度功能

### ISSUE THREAD

**Issue by zhangsean** [youseries/ureport#209]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
UReport v2.2.4

*  #### 遇到的问题描述：
多行合并标题行时，斜线表头的斜线不够美观，第二个斜线没有对着表格框线交叉处，压着第二组文字了。
就是先合并两行标题行，然后添加斜线表头的，然而不管有没有手动刷新，斜线的位置都是如图那样的。

**建议增加自定义斜线角度的功能，这样就可以自己调整斜线角度了！**

*  #### 涉及到的异常信息（完整异常信息）：
无

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/2536402/34925510-b7d24e82-f9e4-11e7-94ee-f065bdee7b67.png)

**Comment by youseries** [comment]
目前设计就是这样
