### ISSUE TITLE
请问下 ureport2集成至Spring mvc项目后，后台日志打印怎么配置？

### ISSUE THREAD

**Issue by zhanruicc** [youseries/ureport#211]
*  #### 当前使用的UReport的具体版本号：

UReport  @v2.2.4

*  #### 遇到的问题描述：

请问下 ureport2集成至Spring mvc项目后，后台日志打印怎么配置？
之前有红色的打印，花费多少时间等等，现在没有了！

*  #### 涉及到的异常信息（完整异常信息）：

无
*  #### 相关截图：
无截图

**Comment by youseries** [comment]
ureport日志采用是System.out.println输出，不需要配置，如果你没有了，应该是你框架层面拦截，可以好好检查下。
