### ISSUE TITLE
设置前景色无效

### ISSUE THREAD

**Issue by siye1103** [youseries/ureport#212]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.3

*  #### 遇到的问题描述：
单元格设置URL链接后，无法设置前景色，设置背景色正常

*  #### 涉及到的异常信息（完整异常信息）：
无

*  #### 相关截图：
![default](https://user-images.githubusercontent.com/32047486/34970848-b0686208-fab1-11e7-895b-c097ec8f142d.png)
![default](https://user-images.githubusercontent.com/32047486/34970856-be5b0d48-fab1-11e7-9cc0-50a876494773.png)

**Comment by youseries** [comment]
设置链接后不支持前景色配置。
