### ISSUE TITLE
重复表尾的行数计算有误

### ISSUE THREAD

**Issue by yingw** [youseries/ureport#213]
*  #### 当前使用的UReport的具体版本号：
2.2.4

*  #### 遇到的问题描述：
设置一行重复表尾，以及翻页行数设置11，理应显示10条数据和1条行尾。但是实际显示只有9条数据。要设置翻页行数为12才能正确显示10条数据。
设置多行表尾，会成倍影响，感觉一条表尾被计算成了2行。
重复表头功能测试正确。
（另：通过手动加一可以避免，但是该Bug还会影响补充空白行功能）

*  #### 相关截图：
设置11行
![image](https://user-images.githubusercontent.com/1177503/34976057-b8e62b68-facf-11e7-9233-4bab68a55ae5.png)

只能显示9行
![image](https://user-images.githubusercontent.com/1177503/34976081-d622e32e-facf-11e7-85f9-3bc2977bb883.png)

**Comment by youseries** [comment]
最新版的SNAPSHOT中已修复，请更新测试，谢谢。
