### ISSUE TITLE
总结行的顺序问题与取消行类型的问题

### ISSUE THREAD

**Issue by liqiaolin520** [youseries/ureport#214]
***  #### 当前使用的UReport的具体版本号：**
2.2.5-SNAPSHOT

***  #### 遇到的问题描述：**

一、分页报表 后三行 为总结行，但是打印时候这三行顺序乱了。
![image](https://user-images.githubusercontent.com/32925394/34980771-77747232-fae0-11e7-8d4c-40c6af1d5fc1.png)

![image](https://user-images.githubusercontent.com/32925394/34980841-adc7267c-fae0-11e7-8073-b6cb040e3e8d.png)

二、还是顺序的问题....
![image](https://user-images.githubusercontent.com/32925394/34980946-001ad464-fae1-11e7-8165-555223838323.png)

![image](https://user-images.githubusercontent.com/32925394/34980963-0b946d5a-fae1-11e7-99da-9c986588f842.png)

三、取消行类型的时候，取消的不是自己行的类型而是最后从最后一行开始取消，最后一行到自己的行之前行没有行类型的时候才会取消自己行的类型，好了，说了这么多，还是看我的图把....
![image](https://user-images.githubusercontent.com/32925394/34981086-66ec553c-fae1-11e7-8bbf-182706b5f3ed.png)

![image](https://user-images.githubusercontent.com/32925394/34981072-5a573a80-fae1-11e7-9dbf-3e7916e1a9d9.png)

![image](https://user-images.githubusercontent.com/32925394/34981114-851924f4-fae1-11e7-9762-c7d2229a03bc.png)

![image](https://user-images.githubusercontent.com/32925394/34981122-8c66eca0-fae1-11e7-9c2d-87e5c5c2233a.png)

![image](https://user-images.githubusercontent.com/32925394/34981274-f761fe14-fae1-11e7-8a16-13250aa3f565.png)

//  最后才取消到自己

![image](https://user-images.githubusercontent.com/32925394/34981280-fee7c5e2-fae1-11e7-9c41-7e06adcd8e5b.png)

**Comment by liqiaolin520** [comment]
我今天专门还测试了一下

![image](https://user-images.githubusercontent.com/32925394/35023624-77d34640-fb76-11e7-818f-dbac137f45ab.png)

![image](https://user-images.githubusercontent.com/32925394/35023627-7b3c0af6-fb76-11e7-8466-5ec449f55b95.png)

**Comment by youseries** [comment]
最新版SNAPSHOT中已修复，请更新测试，谢谢。

**Comment by liqiaolin520** [comment]
好的，感谢
