### ISSUE TITLE
超链接无法修改字体颜色

### ISSUE THREAD

**Issue by siye1103** [youseries/ureport#218]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.3

*  #### 遇到的问题描述：

超链接无法修改字体颜色，字体、字体大小都可以

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![default](https://user-images.githubusercontent.com/32047486/35033835-1416236c-fba7-11e7-85d3-e72d2a27fabb.png)
![default](https://user-images.githubusercontent.com/32047486/35033909-49566ce4-fba7-11e7-9a3a-dcd47b278003.png)

**Comment by youseries** [comment]
目前设计是这样。
