### ISSUE TITLE
linux环境下创建报表名称乱码问题

### ISSUE THREAD

**Issue by dengchf** [youseries/ureport#219]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.4

*  #### 遇到的问题描述：
Linux环境下创建报表，报表名称乱码。
报表初次打开无异常，切换分页报400。

*  #### 涉及到的异常信息（完整异常信息）：
无

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/31127209/35034178-442a5b3a-fba8-11e7-8273-5780b7b364e5.png)
![image](https://user-images.githubusercontent.com/31127209/35034222-67e3659e-fba8-11e7-974e-123a7f25346c.png)
![image](https://user-images.githubusercontent.com/31127209/35034290-9b57136c-fba8-11e7-9231-469b21e975a6.png)

**Comment by zhoushijin** [comment]
中文乱码是字符集问题，我的环境为centos7，系统字符集为zh_CN.UTF-8，保存后报表界面显示正常，在linux目录下文件名乱码，内容正常，不影响功能使用。想要linux目录下文件不乱码，要将linux系统字符集改为zh_CN.GBK  
我是在环境变量中设置字符集的
```
vi /etc/profile
export LC_ALL="zh_CN.GBK"
export LANG="zh_CN.GBK"
source /etc/profile
```
完成后重启tomcat
