### ISSUE TITLE
希望实现报表数据源和数据库表持久化功能

### ISSUE THREAD

**Issue by github568219115** [youseries/ureport#221]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.4

*  #### 遇到的问题描述：
你好，目前的版本，添加报表数据源和表后，关闭浏览器或者重启服务器添加的数据源和表就不存在了，希望后续版本能实现数据源和表的持久化功能

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
你报表没保存，当然不能持久化。
