### ISSUE TITLE
关于searchform.bundle.js

### ISSUE THREAD

**Issue by wangshaoan** [youseries/ureport#223]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.24

*  #### 遇到的问题描述：
searchform.bundle.js打包的源文件有哪些啊，为啥我没找到searchform.bundle.js的入口文件啊

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
这里不提供源码级支持。
