### ISSUE TITLE
前端怎么去做二次开发？

### ISSUE THREAD

**Issue by 12cm** [youseries/ureport#226]
*  #### 当前使用的UReport的具体版本号：
最新版本

*  #### 遇到的问题描述：

后端同事需要前端这边，对查询表单设计器弹出框，新加模板功能按钮，并实现点击按钮插入自定义的模板，前端如何运行下载下来的dome，如何去修改调式页面，麻烦给点提示，谢谢

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
抱歉，这里不提供二次开发支持。
