### ISSUE TITLE
ureport的xml能不能分目录管理

### ISSUE THREAD

**Issue by tanmingft** [youseries/ureport#227]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：2.2.4

*  #### 遇到的问题描述：配置好ureport存储目录后只能在当前目录下找到XMl,当报表数量多了以后难以管理。能不能还有分子目录存储报表xml文件

![image](https://user-images.githubusercontent.com/28721406/35213586-17b2aaea-ff99-11e7-94bb-a1fd47f36a6c.png)

如上图这样存储

**Comment by tanmingft** [comment]
![image](https://user-images.githubusercontent.com/28721406/35213691-703ce1ee-ff99-11e7-9183-a9b4c7ede9cc.png)

**Comment by tanmingft** [comment]
Firt,Second为XML分类

**Comment by J-cafe** [comment]
实现多个ReportProvider接口。
参考http://wiki.bsdn.org/pages/viewpage.action?pageId=76448468

**Comment by youseries** [comment]
楼上正解！
