### ISSUE TITLE
模板中使用formatnumber函数（格式化数字）,不能进行保存，也不能预览

### ISSUE THREAD

**Issue by wuyi5630** [youseries/ureport#23]
![default](https://user-images.githubusercontent.com/20586263/29152673-2a3ad486-7dbb-11e7-8340-07c336ccbc1a.jpg)

如图，模板中使用formatnumber函数（格式化数字）,不能进行保存，也不能预览。

**Comment by J-cafe** [comment]
格式化 不是函数，只需要写格式即可。比如#,###.00

**Comment by youseries** [comment]
楼上正解👍

**Comment by wuyi5630** [comment]
感谢
