### ISSUE TITLE
ureport2的合并单元格  导出word的时候没有合并到

### ISSUE THREAD

**Issue by 1035818889** [youseries/ureport#231]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
ureport2-console的版本号是2.2.5-SNAPSHOT

*  #### 遇到的问题描述：
ureport2的合并单元格  导出word的时候没有合并到

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
设计表是这样的：
![image](https://user-images.githubusercontent.com/17486239/35322546-ab19f2f6-0125-11e8-9765-fe0d25daddbd.png)
导出word的效果是：
![image](https://user-images.githubusercontent.com/17486239/35322572-bf74483c-0125-11e8-97fb-e836e9af2ed9.png)

**Comment by 1035818889** [comment]
ureport2的合并单元格 导出word的时候没有合并到

**Comment by 1035818889** [comment]
客户端安装的是wps软件的话，上述问题会出现；客户端安装的是Office软件的话，上述问题不会出现

**Comment by youseries** [comment]
不支持WPS，只支持office2010或以上版本。
