### ISSUE TITLE
恒等于无法计算

### ISSUE THREAD

**Issue by wbb18129355955** [youseries/ureport#232]
表达式中的恒等于无法做出比较。

![fireshot capture 4 - jeesite - http___localhost_8080_](https://user-images.githubusercontent.com/24587930/35437554-dbed5a54-02cd-11e8-9a35-7d59158e61e0.png)
![fireshot capture 3 - ureport2 designer_ - http___localhost_8080_ureport_designer](https://user-images.githubusercontent.com/24587930/35437559-e07b0c2e-02cd-11e8-90ac-12fd6ff59f8a.png)

**Comment by youseries** [comment]
刚测试了下，我这里是可以的。所以你这里不行原因应该就是相对当前单元格取到的C6值可能存在多个，从而无法实现这种比较，具体看视频，先去理解单元格迭代原理，理解“相对于当前单元格取其它单元格值”这样或许你就能解决自己的问题。
