### ISSUE TITLE
ureport函数的用法，如sum

### ISSUE THREAD

**Issue by Tyke-Jody** [youseries/ureport#233]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
版本是2.2.4

*  #### 遇到的问题描述：
在使用sum函数统计一列的总和的时候，发现统计出来的只是这一列的第一个值，而不是整列的总和。
而且确认数据集和字段的属性都没写错。

*  #### 涉及到的异常信息（完整异常信息）：
没有异常信息，就是sum函数统计的结果有问题。

*  #### 相关截图：
![aa](https://user-images.githubusercontent.com/35566254/35511226-13d2b990-0536-11e8-89cd-cfb9ee97de8b.png)

显示的结果：这里只显示出第一个数值100，没有算出求和的合计结果。
![image](https://user-images.githubusercontent.com/35566254/35511311-4f0844ee-0536-11e8-90f2-086199522092.png)

![image](https://user-images.githubusercontent.com/35566254/35511399-b18eaaae-0536-11e8-95ea-0a7d29813f67.png)

**Comment by it-noob** [comment]
父格没设置对，建议看下视频

**Comment by Tyke-Jody** [comment]
@it-noob 好的，谢谢。。。问题已经解决。
![image](https://user-images.githubusercontent.com/35566254/35616131-4d0bb44e-06af-11e8-899c-fd01474bcd06.png)
第一次用ureport，感觉不错。
总结一下：关于ureport函数的用法。如，使用sum函数计算一列数值的总和。
1）按照sum函数的用法去设置。
2）需要将显示结果的格子的左父格与上父格设置为无。如图。
