### ISSUE TITLE
sql server 2008报表查询问题

### ISSUE THREAD

**Issue by lllss** [youseries/ureport#234]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：ureport2-console-2.2.4.jar

*  #### 遇到的问题描述：
sql server 2008版本数据库配置报表查询，模糊查询时，拼接字符串查询不出数据

${
	if(param("materialName")==null || param("materialName")==''){
		return "select * from material_info";
    }else{
               return "select * from material_info where name like " + "\'%"+":materialName"+"\'";
    }

}

这样查询查不出数据，这个要怎么拼sql呢？

2008版本没有concat()函数，2012及2012以上的版本可以用concat()函数，where material like CONCAT(':mateiralName','%')，这样写是可以的

*  #### 涉及到的异常信息（完整异常信息）：
[后台打印出的sql：]
![image](https://user-images.githubusercontent.com/31031049/35616334-ee9df844-06af-11e8-9e34-535f892a8987.png)

**Comment by youseries** [comment]
ureport2中SQL查询采用的是spring的NamedParameterJdbcTemplate实现，所以类似这种like查询定义方式可以baidu搜索“NamedParameterJdbcTemplate like查询”查找答案，其它查询也是一样。

**Comment by youseries** [comment]
同时需要注意的是，如果用了'，那么需要采用\进行转义，如：\'

**Comment by lllss** [comment]
已解决，非常感谢！！
