### ISSUE TITLE
希望能增加报表的联动功能或钻取功能

### ISSUE THREAD

**Issue by huanghuafeng0926** [youseries/ureport#235]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.5-SNAPSHOT

*  #### 遇到的问题描述：
希望能增加报表的联动功能或钻取功能

*  #### 涉及到的异常信息（完整异常信息）：
无

*  #### 相关截图：

**Comment by huanghuafeng0926** [comment]
ureport的链接好像不支持同一个页面的联动查询，只能是
1、跳出一个新页面；
2、或替换当前的页面；
联动查询或数据钻取的功能是不是可以改造一下？

**Comment by youseries** [comment]
通过链接就可以实例钻取，因为是报表，所以不支持同一页面内部联动查询。
