### ISSUE TITLE
二维码表达式保存后重新读取为空白

### ISSUE THREAD

**Issue by JustGentle** [youseries/ureport#236]
*  #### 当前使用的UReport的具体版本号：2.2.5

*  #### 遇到的问题描述：
在设计器中插入二维码，设置表达式为参数，或者某个单元格值（比如：A7），保存后报表可以正常使用。但再次打开此报表，选择二维码，查看属性所绑定表达式为空，且无法保存报表，每次编辑该报表，都必须重新设置所有的二维码表达式才能保存。

*  #### 涉及到的异常信息（完整异常信息）：
无异常信息

*  #### 相关截图：
![qrcode](https://user-images.githubusercontent.com/25601771/35714067-b80d7b22-0805-11e8-9bbd-8290c6e16f3e.png)

**Comment by yuxinyin** [comment]
应该是 ZxingValue 这个类的getValue有问题，需要改为：

```
        @Override
	public String getValue() {
		switch (source) {
		case expression:
			return expr;
		case text:
			return text;
		}
		return "";
	}
```

**Comment by youseries** [comment]
BUG，更新最新的SNAPSHOT测试，谢谢。
