### ISSUE TITLE
URL配置只能固定文本，不能设置为当前上下文

### ISSUE THREAD

**Issue by yuxinyin** [youseries/ureport#237]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.4

*  #### 遇到的问题描述：

目前的报表钻取通过配置Url的方式实现，但是这个url不能设置为当前上下文。导致每次都是写固定的路径，不同环境下无法复用，希望能在后续的版本中支持

*  #### 涉及到的异常信息（完整异常信息）：
无

*  #### 相关截图：
无

**Comment by youseries** [comment]
URL支持表达式，格式如下：
${表达式...}

**Comment by yuxinyin** [comment]
请问表达式如何获取报表所在的上下文路径？ 例如 http://localhost:8080/test，这个地址在测试环境，在生产环境都是不一样的

这种表达式要怎么写呢
