### ISSUE TITLE
判断值为空的问题

### ISSUE THREAD

**Issue by lokamir** [youseries/ureport#238]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.4-Release

*  #### 遇到的问题描述：
使用条件格式的时候要判断单元格为空该怎么表达?
尝试了 ''，null，NULL都不行

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
判断为空字符串用''或""，为null则直接用null，如：
A1=='' || A1==null
