### ISSUE TITLE
图表无法正常显示

### ISSUE THREAD

**Issue by siye1103** [youseries/ureport#239]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.5

*  #### 遇到的问题描述：

图标无法显示

*  #### 涉及到的异常信息（完整异常信息）：
1、第一次制作图标显示正常
![default](https://user-images.githubusercontent.com/32047486/35845807-f03a56b8-0b4e-11e8-9ce5-72c7ff3104c9.png)
![default](https://user-images.githubusercontent.com/32047486/35845819-ff998d7c-0b4e-11e8-9750-b18dd9100aad.png)
2、修改参数，再修改回来，预览不显示图标
![default](https://user-images.githubusercontent.com/32047486/35845838-1be0fda8-0b4f-11e8-8c3b-57b2ac9a4a4a.png)
![default](https://user-images.githubusercontent.com/32047486/35845849-26cee4a0-0b4f-11e8-8d83-f9f1c364afcf.png)

*  #### 相关截图：

**Comment by siye1103** [comment]
补充，经测试发现只要xml里面有 chart 上 title 属性（设置为display true or false都有问题），chart就会显示不出来。2.2.4 和 2.2.5测试都是如此。

**Comment by youseries** [comment]
最新版SNAPSHOT已修复此BUG，请下载测试，谢谢。

**Comment by siye1103** [comment]
2.2.8测试正常
