### ISSUE TITLE
报表如果有很多列的话，导出pdf或者word格式时，页面上只有部分数据

### ISSUE THREAD

**Issue by xuexiaoao** [youseries/ureport#24]
![eg8a496 9m81 0 ls3 0u](https://user-images.githubusercontent.com/18185523/29159323-a0e5cb84-7de0-11e7-9b89-66db0564213c.png)

像这种情况，可不可以设置数据全部显示

**Comment by youseries** [comment]
这是因为表格宽度超出页面宽度。
你可以设置页边距，或将页面横向放置，或者选择更大的页面。
