### ISSUE TITLE
列合并，行合并

### ISSUE THREAD

**Issue by lllss** [youseries/ureport#240]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：ureport2-console-2.2.4.jar

*  #### 遇到的问题描述：将分组后组内的某一列数据放到该分组之后的合并单元格中

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
结果界面：
![image](https://user-images.githubusercontent.com/31031049/35895777-eb9a81d2-0bf3-11e8-91fd-75e7e7059163.png)
设计界面：
![image](https://user-images.githubusercontent.com/31031049/35895814-18104d64-0bf4-11e8-8a05-852bfdd09ce9.png)
![image](https://user-images.githubusercontent.com/31031049/35895842-3aacee4a-0bf4-11e8-88a8-35cf653bd62a.png)

**Comment by youseries** [comment]
建议先看视频，理解了基本的单元格迭代原理后再做。
