### ISSUE TITLE
v2.2.5套打设置背景图片被单元格覆盖，无法看着背景图片设计打印

### ISSUE THREAD

**Issue by zhangsean** [youseries/ureport#244]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
v2.2.5

*  #### 遇到的问题描述：
套打设置背景图片被单元格覆盖，无法看着背景图片设计打印。
切换回v2.2.4版本背景图片显示正常。

*  #### 涉及到的异常信息（完整异常信息）：
无

*  #### 相关截图：

![v2 2 5](https://user-images.githubusercontent.com/2536402/36339753-7b12ed16-1407-11e8-85ee-8399b102cad0.png)

**Comment by youseries** [comment]
BUG,最新的2.2.6-SNAPSHOT中已修复，请更新，谢谢。
