### ISSUE TITLE
报表界面怎么访问

### ISSUE THREAD

**Issue by xingchenlian** [youseries/ureport#248]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.5

*  #### 遇到的问题描述：
普通的web项目中加入了ureport2，并且成功启动项目，但是应该怎么访问报表设计界面呢？下面截图访问不了

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![qq 20180226102341](https://user-images.githubusercontent.com/36830514/36650568-306e3cdc-1adf-11e8-99d6-3defbb5ff41f.png)

**Comment by youseries** [comment]
ureport的spring配置文件未加载到标准的spring上下文中（比如在使用springMVC的项目中，将ureport的spring配置文件加载到springmvc的上下文中就会出现这个问题）
