### ISSUE TITLE
数据映射怎么使用

### ISSUE THREAD

**Issue by lile405** [youseries/ureport#25]
在ureport2中 怎么使用将代码转名称，是使用数据映射吗？如果是，怎么使用呢？

**Comment by lile405** [comment]
比如行业代码转成行业名称，大概行业有1000 多个

**Comment by youseries** [comment]
UReport2中数据映射只映射有限的数值，比如性别，婚否等不超过10个的，对于你这里1000多个的建议在SQL层面解决（加join），UReport2不支持动态数据映射。
