### ISSUE TITLE
无依赖关系的 数据集列表展开问题

### ISSUE THREAD

**Issue by yuandigit** [youseries/ureport#251]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：2.2.5

*  #### 遇到的问题描述：假设有两列数据向下展开，分别来自数据集A与数据集B, 业务上想要实现同时展示，来自两数据集的某些字段，由于不同数据集间没有依赖关系，我将父节点置为空（是否正确？），最终结果描述： 如果 A与B的的记录分别是  a与b 条 展示上总行数 不是 a与b的最大值，而是a+b，其余部分各自填充空白行。请问是设置的问题，还是目前不能支持这种展开展示。

*  #### 涉及到的异常信息（完整异常信息）：无异常信息

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/32536946/36824053-6d6b3d34-1d3b-11e8-8b89-9514109c4860.png)

![image](https://user-images.githubusercontent.com/32536946/36823895-7218e850-1d3a-11e8-9ead-9fcce58796da.png)

**Comment by ChallengerDefier** [comment]
我也想知道是否支持，现在要多表拼接，头大！

**Comment by youseries** [comment]
不支持。
