### ISSUE TITLE
 sql中怎么判断集合是否为null或空集合

### ISSUE THREAD

**Issue by ghostman-git** [youseries/ureport#253]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.4

*  #### 遇到的问题描述：
https://gitee.com/youseries/ureport/issues/II18I

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
已解答！
