### ISSUE TITLE
图例无法取消

### ISSUE THREAD

**Issue by bvliang** [youseries/ureport#254]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.3

*  #### 遇到的问题描述：
图表的图例无法取消，在Legend Config中选择Display为No，预览报表时依然会显示图例

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
BUG，最新版SNAPSHOT中已修复，谢谢。
