### ISSUE TITLE
希望支持可以同时解析多个模板文件的方法

### ISSUE THREAD

**Issue by ghostman-git** [youseries/ureport#257]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.4 & 2.2.5

*  #### 遇到的问题描述：
希望支持可以同时解析多个模板文件的方法

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
请详细描述下你的需求，谢谢。

**Comment by ghostman-git** [comment]
业务使用过程中，单据的类型不同，含有的数据也不相同（举例：报销单来说，报销单有主数据，另外，有的报销单有出差明细，有的有医疗明细， 有的可能同时含有出差+医疗明细）。打印的时候，希望主数据做一个模板，出差明细一个模板，医疗明细一个模板。  单据打印的时候，单据有什么明细就打印什么数据。
PS：如果每个单据类型都做一个模板，太繁琐，复用性差

**Comment by youseries** [comment]
你需要的是了个子报表，功能，目前不支持子报表。
