### ISSUE TITLE
序号分组问题

### ISSUE THREAD

**Issue by zhangleizhen2** [youseries/ureport#258]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：2.2.5

*  #### 遇到的问题描述：序号问题，序号列无法根据他的左父格B2一样合并单元格

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
模板如下：

![qq 20180308090108](https://user-images.githubusercontent.com/24260850/37127152-5c0ec21c-22af-11e8-9017-871b4218b8be.png)
B2为A2和C2的左父格，C2后面的左父格为本身左侧一格，B2的属性如下
![1](https://user-images.githubusercontent.com/24260850/37127202-adfd3658-22af-11e8-8f4a-c1af12e35741.png)
A2的属性如下：
![5](https://user-images.githubusercontent.com/24260850/37127335-3ffd9264-22b0-11e8-8146-1ee2fe09934b.png)

下面是要实现的效果图：
![3](https://user-images.githubusercontent.com/24260850/37127343-45888d4c-22b0-11e8-846d-69eae19adb2c.png)

下面为实际展现的效果：
![7](https://user-images.githubusercontent.com/24260850/37127366-5cee190c-22b0-11e8-8977-71b95bb21ef1.png)

**Comment by youseries** [comment]
C2和B2单元格看起来是属于同一个数据集的两个属性（假设你B2单元格用的对象属性是abc，这个后面会用到），之所以出现这个问题是因为你C2单元格左父格未配置，C2左父格设置为A2，同时为C2单元格添加过滤条件：C2单元格中绑定对象的属性abc等于B2。

**Comment by zhangleizhen2** [comment]
@youseries 非常感谢，问题已解决
