### ISSUE TITLE
迭代报表 每张报表的单元格不一样大

### ISSUE THREAD

**Issue by liqiaolin520** [youseries/ureport#259]
*  #### 当前使用的UReport的具体版本号：
ureport-console-2.2.5

*  #### 遇到的问题描述：
  我做了一个批量打印的报表，然后第一页与第二页第三页的格子不一样大，导致后面的报表占用了多页。

 

*  #### 相关截图：
 第一页，没啥问题，挺棒的~
![image](https://user-images.githubusercontent.com/32925394/37128812-bf7e2336-22b6-11e8-9f33-c6e71ece5310.png)

第二页，第三页..... 问题就有了
![image](https://user-images.githubusercontent.com/32925394/37128851-f26e7aac-22b6-11e8-9416-eeaba577de4f.png)
![image](https://user-images.githubusercontent.com/32925394/37128762-8326e094-22b6-11e8-849d-e56bc6615d86.png)

然后第二张报表就越界到第三页了.... 后面的报表更是如此
![image](https://user-images.githubusercontent.com/32925394/37128881-1c58818c-22b7-11e8-9bf2-5753d29d3705.png)

这是我的设计 
![image](https://user-images.githubusercontent.com/32925394/37128908-5620daea-22b7-11e8-8b6b-9edef960361d.png)

这是我打印出来的报表，麻烦Jack 你看一下
[ureport-p (1).pdf](https://github.com/youseries/ureport/files/1791565/ureport-p.1.pdf)

**Comment by youseries** [comment]
你需要用到条件属性里的分页功能，具体使用方法看条件属性相关视频。

**Comment by liqiaolin520** [comment]
不是把，问题还不没解决就close 了,  我把这个格子弄成文本也是这样

**Comment by liqiaolin520** [comment]
我觉得不是分页的问题啊！！！！！！！！！！！！ jack

**Comment by liqiaolin520** [comment]
试了不是分页的问题
