### ISSUE TITLE
设置固定行数分页，固定表尾行时，会输出两次重复表尾行

### ISSUE THREAD

**Issue by simon1026** [youseries/ureport#26]
2.0.8-SNAPSHOT

**Comment by simon1026** [comment]
![2](https://user-images.githubusercontent.com/7332436/29176326-1f35509e-7e1e-11e7-8693-37c3874d7ae8.png)
![3](https://user-images.githubusercontent.com/7332436/29176328-1f49aeb8-7e1e-11e7-84f5-4932f3cd34a7.png)
![4](https://user-images.githubusercontent.com/7332436/29176327-1f3ca9e8-7e1e-11e7-9372-1baae39ed530.png)

**Comment by youseries** [comment]
BUG，已修复，请更新最新版测试。
