### ISSUE TITLE
打印报表时 参数传递后精度丢失的问题

### ISSUE THREAD

**Issue by liqiaolin520** [youseries/ureport#261]
首先呢，我希望问题得以解决后在关闭问题！！

*  #### 当前使用的UReport的具体版本号：
2.2.5

*  #### 遇到的问题描述：
我打印报表时传入了一个小数的参数，精度为小数位3位，传过去后发现精度丢失了。

 我需要查询一个数额，查询达到他这一期数量的时间是那天 取的是result字段
![image](https://user-images.githubusercontent.com/32925394/37239596-c5a561c4-2479-11e8-88e4-fc5aa605b665.png)

我在工具里面测试的时候查询出来的是 BMTJ-1-1这一条数据，这是正常的，第一期的
bill_meter_total只有24306688.100 然后加上第二期的就满足了
![image](https://user-images.githubusercontent.com/32925394/37239626-43688d7a-247a-11e8-94b4-a95dfab28995.png)

然后我在报表打印中，他显示的是 2018年 03月  BMTJ-1-0 很明显 他取了BMTJ-1-0这条数据，可是这条数据比这个参数小了0.100 所以我怀疑这个参数精度可能被丢失了！
![image](https://user-images.githubusercontent.com/32925394/37239659-b942371c-247a-11e8-8a06-fe4c442f6f08.png)

然后我做了个实验，
首先把参数改成 24306688.999 ，  依然如此
![image](https://user-images.githubusercontent.com/32925394/37239691-29f98d16-247b-11e8-9ed5-34410ba7a061.png)

当我把参数改成  24306689
![image](https://user-images.githubusercontent.com/32925394/37239723-6d1b4c24-247b-11e8-8148-b9796431c8e9.png)
就可以了！

写了这么多我发现  有个float .....
悲催。。还是留着给其他人踩坑的人一个小小的帮助把。

**Comment by liqiaolin520** [comment]
当我以为是Float的问题的时候，上帝又为我关上了这一扇窗！！！
![image](https://user-images.githubusercontent.com/32925394/37239899-914ca050-247d-11e8-8c3b-83a136cf9270.png)
  
改完后我发现 不仅仅是 24306688.200 不对了 ，连刚刚24306689 都行了，
![image](https://user-images.githubusercontent.com/32925394/37239906-b41e0682-247d-11e8-89dd-0c89a2696dc8.png)

![image](https://user-images.githubusercontent.com/32925394/37239914-d3ececa8-247d-11e8-9c9d-fa1b55bcde24.png)

但是 24306690 居然可以，这个原理我就搞不清了， 我还是暂时用Integer把，至少他精度只是丢失个小数位，而float就不知道是什么情况了。

希望Jack 你查一查把，早日把Ureport完善。。

**Comment by youseries** [comment]
参数解析精度问题，最新版SNAPSHOT中已修复，你参数类型设置成float类型即可正确解析外部传入的带小数的值，请更新测试，谢谢。

**Comment by liqiaolin520** [comment]
OK 下次在测试吧，问题不是很大
