### ISSUE TITLE
固定式报表，数据覆盖

### ISSUE THREAD

**Issue by ChallengerDefier** [youseries/ureport#262]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.5

*  #### 遇到的问题描述：
制作如图固定式报表:
通过表达式筛选数据（通过过滤条件页存在此问题）
![image](https://user-images.githubusercontent.com/21078181/37389248-8820b6a0-279e-11e8-9d57-07488e91414c.png)

预览时第二行数据就会被覆盖，如图：
![image](https://user-images.githubusercontent.com/21078181/37389346-ed93f57e-279e-11e8-9c85-cd3474e4484c.png)

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by ChallengerDefier** [comment]
这个是具有其他解决方案，还是暂不支持这种固定式报表？

**Comment by youseries** [comment]
条件解析的BUG最新版SNAPSHOT中已修复，请更新测试，谢谢。

**Comment by ChallengerDefier** [comment]
如果表达式结果只有一条数据，选择不展开，依然上一行会覆盖下一行数据，导致下一行显示不出来。

**Comment by youseries** [comment]
第二条数据不是被覆盖，而是父格条件约束导致第二行没有数据，还是先看看视频，理解发单元格父子格原理再做吧，否则这些基本的功能你都不知道如何处理。
