### ISSUE TITLE
图表可以增加更多类型吗？比如地图

### ISSUE THREAD

**Issue by lijuelijue** [youseries/ureport#265]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：2.2.5

*  #### 遇到的问题描述：图表可以增加更多类型吗？比如地图

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
不能。
