### ISSUE TITLE
格式化

### ISSUE THREAD

**Issue by fightAllDay** [youseries/ureport#267]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

不好意思网卡了还没写完就提交到issue了。

*  #### 当前使用的UReport的具体版本号：
版本号为2.2.6。

*  #### 遇到的问题描述：
对金额列进行格式化之后在导出的excel中无法对该列进行求和等计算，需先转化单元格格式；
没有格式化时可以在excel直接进行求和计算。

*  #### 涉及到的异常信息（完整异常信息）：
无异常。

*  #### 相关截图：
![1 q dx n i7xb1 u b mze](https://user-images.githubusercontent.com/31916772/37705026-9db52810-2d35-11e8-88ed-346af7e4f960.png)

**Comment by youseries** [comment]
你要保证你当前单元格对应的数据是数字类型，如果是数字类型的话在导出excel时，ureport会自动将对应单元格设置为NUMERIC。

**Comment by youseries** [comment]
是的，一旦做了格式化，内容就会变成字符串。
