### ISSUE TITLE
查询表单设计器单选列表显示不到对应的数据集

### ISSUE THREAD

**Issue by howell86** [youseries/ureport#270]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

ureport 2.2.7-SNAPSHOT

*  #### 遇到的问题描述：查询表单设计器单选列表显示不到对应的数据集

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

![image](https://user-images.githubusercontent.com/30722476/37882478-381d2288-30d6-11e8-8965-8fb7e40f0b48.png)
![image](https://user-images.githubusercontent.com/30722476/37882489-48573530-30d6-11e8-884f-6e8d0f642a0b.png)

**Comment by youseries** [comment]
刚试了下两个数据集，是可以的。
