### ISSUE TITLE
金额格式化问题，

### ISSUE THREAD

**Issue by ghostman-git** [youseries/ureport#271]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.5

*  #### 遇到的问题描述：

金额格式化，个位数是“0”，会丢失，比如：0.01 格式化后变.01

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
https://gitee.com/youseries/ureport/issues/IIKND

**Comment by youseries** [comment]
你用的格式化模式不对吧，试试：#.##%

**Comment by ghostman-git** [comment]
@youseries  #.##%没有上述问题，但是#.##%对于小数位都是X.00的格式化后小数位00没显示（变成X）

**Comment by youseries** [comment]
格式化采用的是Java的DecimalFormat实现，所以具体你可以看看DecimalFormat支持哪些格式。
