### ISSUE TITLE
dataset的sql语句较长时报错

### ISSUE THREAD

**Issue by bvliang** [youseries/ureport#272]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.3

*  #### 遇到的问题描述：
dataset的sql语句较长时报如下错误：
414 Request-URI Too Large

*  #### 相关截图：
![default](https://user-images.githubusercontent.com/32626378/37956875-171c5f36-31df-11e8-99ca-d24c80d20b9b.JPG)

**Comment by youseries** [comment]
https://blog.csdn.net/hanchao_h/article/details/69945557
