### ISSUE TITLE
URL问题

### ISSUE THREAD

**Issue by ghostman-git** [youseries/ureport#273]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.5

*  #### 遇到的问题描述：

1.URL怎么填写事件呢，这样写${#.INNER_BUDGET_ID=='' ? '' : 'javascript:searchInnerBudgetUsedDetail(\''+ #.INNER_BUDGET_ID +'\');'}的话，参数的引号怎么转义？
2.没有写参数，生成的路径，页面查看会多个"?"

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
1.不支持写事件
2.多“？”问题后面将修正

**Comment by ghostman-git** [comment]
@youseries  建议增加事件的支持。

**Comment by youseries** [comment]
最新版SNAPSHOT中已修复无参数URL后面多个？问题。
