### ISSUE TITLE
下载的pdf表格没有自适应扩大/缩小宽度

### ISSUE THREAD

**Issue by bvliang** [youseries/ureport#274]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.3

*  #### 遇到的问题描述：
报表预览时，表格column宽度会根据内容调整宽度，但下载pdf后发现pdf中的表格没有自适应变化，需要自己调整表格column宽度，而且自动换行有时也不生效。

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
不支持。
