### ISSUE TITLE
报表设计器中同时出现二维码和条码，数据来源都用表达式，修改一个表达式，另外一个也会同时改掉

### ISSUE THREAD

**Issue by orange-wlwang** [youseries/ureport#279]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
  2.2.7-SNAPSHOT

*  #### 遇到的问题描述：
  报表设计器中同时出现二维码和条码，数据来源都用表达式，修改一个表达式，另外一个也会同时改掉

*  #### 涉及到的异常信息（完整异常信息）：
![image](https://user-images.githubusercontent.com/34290800/38456225-cdb2b564-3ab4-11e8-8f87-465dd9de0ec5.png)

*  #### 相关截图：

**Comment by youseries** [comment]
bug,最新版SNAPSHOT中已修复。
