### ISSUE TITLE
报表中如果存在二维码，且二维码获取的内容为空，则会报错

### ISSUE THREAD

**Issue by orange-wlwang** [youseries/ureport#280]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
   2.2.7-SNAPSHOT

*  #### 遇到的问题描述：
   报表中如果存在二维码，且二维码获取的内容为空，则会报错

*  #### 涉及到的异常信息（完整异常信息）：
![image](https://user-images.githubusercontent.com/34290800/38456255-54c61bcc-3ab5-11e8-9dbb-d065e2879367.png)

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/34290800/38456308-e4f19082-3ab5-11e8-8f53-81ab8e2bb559.png)

**Comment by youseries** [comment]
这不是BUG，请确保内容不能不空。
