### ISSUE TITLE
图表中显示具体条目数值的设置

### ISSUE THREAD

**Issue by poeao** [youseries/ureport#281]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.6  

*  #### 遇到的问题描述：
图表中的条目上的数值 默认情况下是鼠标在上面悬停的时候才会显示具体的数据，如何设置默认直接显示？ 谢谢 

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
目前图表不支持此功能
