### ISSUE TITLE
preview.bundle.js 这个js加载很慢

### ISSUE THREAD

**Issue by koftt** [youseries/ureport#282]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：2.2.6

*  #### 遇到的问题描述：
report/res/ureport-asserts/js/preview.bundle.js 这个js加载很慢

*  #### 涉及到的异常信息（完整异常信息）：
preview.bundle.js 这个js有800多kb 放在服务器后去访问报表 光加载这个js就用了7-11秒， 放在本地 localhost 去访问报表 就很快了 看了下加载这个js就只要0.6秒不到

*  #### 相关截图：

**Comment by youseries** [comment]
报表设计器功能决定这个js文件小不了，没法压缩，你需要保证人生产环境网络性能。
