### ISSUE TITLE
分页后psum函数计算错误，格式化后输出也有问题

### ISSUE THREAD

**Issue by simon1026** [youseries/ureport#29]
![1](https://user-images.githubusercontent.com/7332436/29215650-69d19ff2-7ede-11e7-88b9-d306f0799f30.png)
![2](https://user-images.githubusercontent.com/7332436/29215651-6a05985c-7ede-11e7-861a-a09a06dbe249.png)

**Comment by simon1026** [comment]
![4](https://user-images.githubusercontent.com/7332436/29216095-06cc2f42-7ee0-11e7-9add-da2b7eb2cadd.png)

**Comment by youseries** [comment]
是psum(R6)有问题还是sum(R6)有问题？

**Comment by simon1026** [comment]
psum(R6)有问题,图圈错了

**Comment by youseries** [comment]
BUG,已修复，请更新最新版测试，谢谢！
