### ISSUE TITLE
图表预览正常显示，结合业务导出不能正常显示

### ISSUE THREAD

**Issue by peterjiao88** [youseries/ureport#292]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：2.2.6

*  #### 遇到的问题描述：图表预览正常显示但是结合业务使用jsp不能正常显示

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![default](https://user-images.githubusercontent.com/16682360/39103170-ca758a56-46db-11e8-9ec3-fde5c2f700fa.png)
![default](https://user-images.githubusercontent.com/16682360/39103183-d91835f4-46db-11e8-8937-e929daeba966.png
![default](https://user-images.githubusercontent.com/16682360/39103238-2c7d4df6-46dc-11e8-99d8-d42833490cf7.png)

**Comment by youseries** [comment]
图表只支持在ureport提供的页面中预览。

**Comment by peterjiao88** [comment]
意思是不能用于生产环境吗，那这样也不行吗，我用的是你们文档里的代码，也不行吗，就是ureport文件啊
![default](https://user-images.githubusercontent.com/16682360/39110508-f6d27082-4703-11e8-9c9b-c6be5e601233.png)
