### ISSUE TITLE
ureport不能导出word

### ISSUE THREAD

**Issue by castlezhangss** [youseries/ureport#294]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.3

*  #### 遇到的问题描述：

不能导出word

*  #### 涉及到的异常信息（完整异常信息）：
HTTP Status 500 - Servlet execution threw an exception

--------------------------------------------------------------------------------

type Exception report

message Servlet execution threw an exception

description The server encountered an internal error that prevented it from fulfilling this request.

exception 

javax.servlet.ServletException: Servlet execution threw an exception
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)

root cause 

java.lang.NoSuchMethodError: org.apache.poi.xwpf.usermodel.XWPFDocument.close()V
	com.bstek.ureport.export.word.high.WordProducer.produce(WordProducer.java:165)
	com.bstek.ureport.export.ExportManagerImpl.exportWord(ExportManagerImpl.java:109)
	com.bstek.ureport.console.word.ExportWordServletAction.buildWord(ExportWordServletAction.java:93)
	com.bstek.ureport.console.word.ExportWordServletAction.execute(ExportWordServletAction.java:56)
	com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:81)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)

note The full stack trace of the root cause is available in the Apache Tomcat/7.0.64 logs.

--------------------------------------------------------------------------------

Apache Tomcat/7.0.64

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/38709660/39222221-1c4290fc-486e-11e8-960f-816e5ae69988.png)

**Comment by youseries** [comment]
poi需要3.16或以上版本，看看你用的是什么版本！
