### ISSUE TITLE
sql数据集中使用表单式报错

### ISSUE THREAD

**Issue by ghostman-git** [youseries/ureport#296]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
v2.2.5 v2.2.6

*  #### 遇到的问题描述：
https://gitee.com/youseries/ureport/issues/IJD2Y?from=project-issue

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
码云上已回复
