### ISSUE TITLE
曲线图y轴数据有负数时图标直接显示为0，怎么把负数显示出来

### ISSUE THREAD

**Issue by zhou478016373** [youseries/ureport#297]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.2

*  #### 遇到的问题描述：
曲线图y轴数据有负数时图标直接显示为0，怎么把负数显示出来

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/38778600/39348579-4c4e6d44-4a2a-11e8-9d00-6fcd6ac87491.png)

**Comment by youseries** [comment]
BUG，最新的2.2.8-SNAPSHOT中已修复，谢谢。
