### ISSUE TITLE
Y轴的值只能从0开始吗？要是有负数要怎么显示。

### ISSUE THREAD

**Issue by zhou478016373** [youseries/ureport#298]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.5

*  #### 遇到的问题描述：

Y轴的值只能从0开始吗？要是有负数要怎么显示。

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/38778600/39348935-b243f8ca-4a2b-11e8-8667-f3339d20f89f.png)

**Comment by youseries** [comment]
BUG，最新的2.2.8-SNAPSHOT中已修复，谢谢。
