### ISSUE TITLE
通过nginx访问报表设计器（/ureport/designer）报：Hander [t] not exist

### ISSUE THREAD

**Issue by wuyi5630** [youseries/ureport#3]
您好，开发过程中遇到以下问题：

ureport与基于springboot的业务应用结合，通过nginx访问报表设计器（/ureport/designer）报：**Hander [t] not exist**，而不通过nginx访问报表设计器则访问正常。
![bbb](https://user-images.githubusercontent.com/20586263/28707257-4ae7599a-73aa-11e7-893e-8804667b1b11.png)

**Comment by youseries** [comment]
通过nginx访问的完整的URL是什么？nginx内部有没有做forward转发？
另外如果不 通过nginx访问是好的吗？

**Comment by wuyi5630** [comment]
上面那个图就是nginx访问的完整路径，nginx内部已经做了转发，相关程序是正常的.不通过nginx访问是正常的。

**Comment by youseries** [comment]
我需要知道nginx转发的url是什么，这个t肯定来自url

**Comment by wuyi5630** [comment]
1.报表设计器我是部署在10.233.33.22这个机器下，访问路径http://10.233.33.22:9999/alarm/ureport/designer ，并可以正常访问。
2.nginx的地址是10.233.33.55这台机器下,端口是8888，转发的配置是
`        location /alarm {
            proxy_pass http://10.233.33.22:9999/alarm/;
        }`
3.通过以上配置按正常通过nginx访问报表设计器的地址是：http://10.233.33.55:8888/alarm/ureport/designer， 可是发现报Hander [t] not exist错误。

**Comment by youseries** [comment]
我来搭个环境测下

**Comment by youseries** [comment]
刚做了个环境测试下，没发现问题，我的环境如下，ureport2应用地址为：http://192.168.18.176:8080/ureport2-sample
nginx所在服务器IP为:192.168.18.196
nginx转发配置如下：
`        location /ureport2-sample {
            proxy_pass   http://192.168.18.176:8080/ureport2-sample;
        }`
运行nginx，访问http://192.168.18.196/ureport2-sample/ureport/designer，一切正常，效果如下图所示：
![demo](https://user-images.githubusercontent.com/29193502/29015152-6b068282-7b7f-11e7-9482-b5cfeccdcbe5.png)

**Comment by wuyi5630** [comment]
谢谢，我重新检查了解决了
