### ISSUE TITLE
我在用sum（D1+D2）函数报这个错误

### ISSUE THREAD

**Issue by lile405** [youseries/ureport#30]
![1111](https://user-images.githubusercontent.com/30850078/29239805-8b2de43e-7f89-11e7-9057-33d643a5aee4.jpg)

**Comment by youseries** [comment]
那是因为你当前sum（D1+D2）表达式所在单元格，在取到D1或D2单元格时存在多个值，所以导致错误，请仔细看看报表模型介绍视频：http://wiki.bsdn.org/pages/viewpage.action?pageId=76448530
理解单元格之间关系，这样才能避免类似问题发生。
