### ISSUE TITLE
2.2.6 pdf导出有文本数据有缺失情况

### ISSUE THREAD

**Issue by leetoclass** [youseries/ureport#300]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.6

*  #### 遇到的问题描述：
pdf导出文本数据有缺失。

*  #### 涉及到的异常信息（完整异常信息）：

在该版本中，pdf导出时 ，文本字数有缺失。
*  #### 相关截图：
![re 16 s81 b5 bs3 aybi s](https://user-images.githubusercontent.com/31309248/39736528-fb8fb76e-52b2-11e8-83cf-a5c3cba24d42.png)
![pe p w6u2k 49m0 d08vm26](https://user-images.githubusercontent.com/31309248/39736537-0217bc3a-52b3-11e8-8690-dbea879b7948.png)

**Comment by youseries** [comment]
换行计算属性打开了吗？

**Comment by leetoclass** [comment]
![image](https://user-images.githubusercontent.com/31309248/39805374-4cf047a8-53a9-11e8-9a6b-d287b0dbeef5.png)    已经打开

**Comment by leetoclass** [comment]
已经打开了发自我的iPhone------------------ 原始邮件 ------------------发件人: 高杰  <notifications@github.com>发送时间: 2018年5月9日 11:54收件人: youseries/ureport <ureport@noreply.github.com>抄送: leetoclass <leetoclass@gmail.com>, Author <author@noreply.github.com>主题: 回复：[youseries/ureport] 2.2.6 pdf导出有文本数据有缺失情况 (#300)换行计算属性打开了吗？

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/youseries/ureport","title":"youseries/ureport","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/youseries/ureport"}},"updates":{"snippets":[{"icon":"PERSON","message":"@youseries in #300: 换行计算属性打开了吗？"}],"action":{"name":"View Issue","url":"https://github.com/youseries/ureport/issues/300#issuecomment-387612527"}}}
{"@type":"MessageCard","@context":"http://schema.org/extensions","hideOriginalBody":"false","originator":"37567f93-e2a7-4e2a-ad37-a9160fc62647","title":"Re: [youseries/ureport] 2.2.6 pdf导出有文本数据有缺失情况 (#300)","sections":[{"text":"","activityTitle":"**高杰**","activityImage":"https://avatars1.githubusercontent.com/u/29193502?s=160\u0026v=4","activitySubtitle":"@youseries","facts":[]}],"potentialAction":[{"name":"Add a comment","@type":"ActionCard","inputs":[{"isMultiLine":true,"@type":"TextInput","id":"IssueComment","isRequired":false}],"actions":[{"name":"Comment","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueComment\",\"repositoryFullName\":\"youseries/ureport\",\"issueId\":300,\"IssueComment\":\"{{IssueComment.value}}\"}"}]},{"name":"Close issue","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueClose\",\"repositoryFullName\":\"youseries/ureport\",\"issueId\":300}"},{"targets":[{"os":"default","uri":"https://github.com/youseries/ureport/issues/300#issuecomment-387612527"}],"@type":"OpenUri","name":"View on GitHub"},{"name":"Unsubscribe","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"MuteNotification\",\"threadId\":332912772}"}],"themeColor":"26292E"}

**Comment by youseries** [comment]
已合并，同时已提交新版本，请更新测试，谢谢。
