### ISSUE TITLE
使用emptyparam函数条件拼接

### ISSUE THREAD

**Issue by ys-zlb** [youseries/ureport#304]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.6

*  #### 遇到的问题描述：
emptyparam函数里 怎么使用like语句

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![qq 20180510170731](https://user-images.githubusercontent.com/39153668/39861993-0323558a-5475-11e8-996d-eab6b43e74a4.png)

**Comment by youseries** [comment]
ureport中查询是通过Spring中的NamedParameterJdbcTemplate 实现，所以哪个不会用只要查对应的NamedParameterJdbcTemplate 用法即可，比如你这里可以参考下面的方法实现：
https://www.cnblogs.com/fanshuyao/p/7210508.html

**Comment by ys-zlb** [comment]
解决了 谢谢！

**Comment by 1176375587** [comment]
${(emptyparam("beginDate")==false ? "and bb.create_time like concat(:beginDate,'%')" : "")}

这个写法哪里不对哇？咋老是报错呢
