### ISSUE TITLE
请教：安装完成后遇到几个问题

### ISSUE THREAD

**Issue by izombielandgit** [youseries/ureport#305]
环境：eclipse-jee-oxygen-3a-win32-x86_64；jdk-8u171-windows-x64；apache-tomcat-8.5.31；apache-maven-3.5.3-bin

UReport的具体版本号：2.2.7

根据视频教程安装完成后运行成功，进入设计器，有几个问题如下：

1、单元格格式无法设置：合并，设置边框或字体、颜色等点击后没有反应

2、添加了外部数据库连接MSSQL，添加了数据集，双击无法添加字段至单元格（可以在单元格属性中设置字段，预览中可以查看到数据）

新手第一次弄这个，不知道是否能够解决，谢谢

**Comment by izombielandgit** [comment]
试了下，其它不变，UReport版本换为2.2.6，就没有上述的问题。

**Comment by youseries** [comment]
2.2.7版本设计器BUG，请升级到2.2.8-SNAPSHOT，谢谢。
