### ISSUE TITLE
ObjectMap缓存时间太短

### ISSUE THREAD

**Issue by lee-hong** [youseries/ureport#307]
目前默认时间是5分钟，用户html预览时创建了图数据的缓存，一般用户会先阅读报表，再（可能会）导出pdf/word，而不是已进入预览页面就点导出按钮。这样会导致用户导出的时候，HttpSessionReportCache可能已经过期了，图就丢失了。
请问这个问题除了源码调整这个默认时间，还有什么解决方案吗？

**Comment by youseries** [comment]
目前只能修改源码，之所以设定为5min，是为了尽可能快的释放内存，如果你觉得太短改源码吧。
