### ISSUE TITLE
特殊的报表制作，想请问一下怎么UReport2能否做到，实现内容请查看截图，谢谢

### ISSUE THREAD

**Issue by GavinXieYiLin** [youseries/ureport#309]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

UReport2.2.8

*  #### 遇到的问题描述：
特殊的报表制作，想请问一下怎么UReport2能否做到，实现内容请查看截图，谢谢

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/28643735/40092527-4ba3cef0-58f0-11e8-85ce-45b720293040.png)

**Comment by youseries** [comment]
自己看教程去。
