### ISSUE TITLE
表单设计器时间查询问题

### ISSUE THREAD

**Issue by ys-zlb** [youseries/ureport#310]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.6

*  #### 遇到的问题描述：
在报表设计器里，我选择了一个时间查询，时间参数都传对了，而且在服务器复制了查询的sql在数据库里查也能查出一条数据，但是在界面上却查不到。请问时间控件选择的时间格式传入后台服务器的参数格式是：2018-05-16这格式？如果是应该是能查出一条数据来，希望大佬看看哪里有问题！

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![qq 20180517173143](https://user-images.githubusercontent.com/39153668/40169768-51850140-59f9-11e8-9c04-5082ac129665.png)
![qq 20180517173237](https://user-images.githubusercontent.com/39153668/40169770-520a5066-59f9-11e8-9cb7-16e3fcfd8ecc.png)
![qq 20180517173317](https://user-images.githubusercontent.com/39153668/40169772-52540de6-59f9-11e8-8725-ba1aef4deb89.png)
![qq 20180517173459](https://user-images.githubusercontent.com/39153668/40169773-52c20472-59f9-11e8-8568-78646d799bdf.png)

**Comment by youseries** [comment]
后入后台的日期格式就是你定义查询表单时定义的格式。
ureport查询采用的是Spring中的NamedJdbcTemplate实现 ，所以具体传参时可参照NamedJdbcTemplate，所有NamedJdbcTemplate支持的,ureport都支持。
