### ISSUE TITLE
合并单元格错误，无法定位到正确的单元格

### ISSUE THREAD

**Issue by gengzhengtao** [youseries/ureport#311]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.8-SNAPSHOT

*  #### 遇到的问题描述：

合并单元格后，无法定位到正确的单元格，比如合并A1和A2，当点击B2时，显示的依然是A1的属性

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/1639735/40220554-1cdf6846-5aac-11e8-9ed1-303bfca69693.png)
![image](https://user-images.githubusercontent.com/1639735/40220580-2fe7bd76-5aac-11e8-8c38-412531cb3ec9.png)

**Comment by youseries** [comment]
我这里是好的，更新最新的2.2.8-SNAPSHOT试试。
