### ISSUE TITLE
页面js报错

### ISSUE THREAD

**Issue by guomaolin** [youseries/ureport#312]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：2.2.7

*  #### 遇到的问题描述：
报表设计的页面上所有的样式设置按钮都无效果，在浏览器调试窗口看到有js报错，而且选中一个单元格后，双击一个数据集中的字段时也无效，js同样报错

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by guomaolin** [comment]
![default](https://user-images.githubusercontent.com/12597154/40350090-407b588c-5ddb-11e8-85b5-2f05d6919cf1.png)

**Comment by guomaolin** [comment]
@youseries 还有个问题就是，关系数据库作为数据源，如果一张表的数据超过50万条记录，那生成报表的时候就会OOM，我是在我自己的个人电脑上做的，WIN7 + 8核CPU + 8G内存。这个 有没有办法解决？我们要做基于1000万的数据分组统计

**Comment by youseries** [comment]
这种基于单元格迭代模型的报表最大的优点就是基本可以实现任意复杂的报表样式，缺点就是能处理的数据量有限，最好不要超过100万（数据量越大，应用服务器就要配置更大的内存），否则就需要很长的处理时间及内存占用。
对于你的需求如果一定要处理，那就只有加内存，同时要有耐心等待处理完成。
