### ISSUE TITLE
关于火狐打印报错的问题，

### ISSUE THREAD

**Issue by ghostman-git** [youseries/ureport#314]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.5

*  #### 遇到的问题描述：

> 在预览PDF时，Firefox不允许当前frame外通过javascript调用其打印功能（目前来看可能是Firefox的Bug），所以我们需要手工点击其frame内部自带的打印按钮实现打印。

在火狐中使用时，是否考虑给予友好的提示？或者能否触发内部自带的打印？
PS：客户使用过程中，点击后浏览器没任何反应，会造成一种认为无法使用的错觉

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
文档中说的很清楚了，你可以换用chrome或edge.
