### ISSUE TITLE
移动端—查询框显示问题

### ISSUE THREAD

**Issue by siye1103** [youseries/ureport#315]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.6

*  #### 遇到的问题描述：
移动端--查询框显示，每个元素占整行。不能像电脑端，显示一行。
配置是一行

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![1](https://user-images.githubusercontent.com/32047486/40759055-ebc4375c-64c2-11e8-9c65-dad4413d190a.jpg)

**Comment by youseries** [comment]
移动端是自适应的。

**Comment by siye1103** [comment]
在横向分辨率小于992的时候，md的默认每个col 100%。开启浏览器调试，手工改sx，就正常。
