### ISSUE TITLE
可以对生成的报表进行排名吗？像Excel那样=RANK(Y4,$Y$4:$Y$20)

### ISSUE THREAD

**Issue by daishukun** [youseries/ureport#321]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.6

*  #### 遇到的问题描述：

想知道如何像excel那样排名

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
[图片]

**Comment by youseries** [comment]
不支持。
