### ISSUE TITLE
2.2.8版本ie11打印按钮无效

### ISSUE THREAD

**Issue by hyc714** [youseries/ureport#323]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.8

*  #### 遇到的问题描述：
ie11打印按钮无效

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
不支持IE
