### ISSUE TITLE
如何不在控制台打印报表执行的SQL语句

### ISSUE THREAD

**Issue by MengFeiF** [youseries/ureport#326]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.8

*  #### 遇到的问题描述：

报表执行的时候会在日志里打印执行的SQL语句，怎么设置让它不打印在控制台

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
设置属性ureport.debug=false
