### ISSUE TITLE
多层分组序号问题

### ISSUE THREAD

**Issue by castlezhangss** [youseries/ureport#327]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：2.2.3

*  #### 遇到的问题描述：
   多层分组序号问题, 截图详见附件:
[多层分组序号问题.docx](https://github.com/youseries/ureport/files/2126618/default.docx)

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
截图详见附件

**Comment by youseries** [comment]
生成序号是对的，想要变成你要的那样，需要正确配置父格，建议先好好看看视频，理解父格的作用后再配置。
