### ISSUE TITLE
Ureport导出后格式改变

### ISSUE THREAD

**Issue by user200511** [youseries/ureport#328]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.6

*  #### 遇到的问题描述：
报表导出PDF或者EXCEL（2016版本）后，文件显示的行高和在线预览的不一致，

*  #### 涉及到的异常信息（完整异常信息）：
下图分别为在线预览和导出PDF的截图，我在设计器中，行高为默认值，在线预览没有问题，但是导出PDF和Excel中，文字显示不全，Excel可以手动拉宽行高，但是PDF不行能啊，

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/40486931/41765094-a59e4c98-7635-11e8-9b54-60b4695e3604.png)
![image](https://user-images.githubusercontent.com/40486931/41765107-b2c01168-7635-11e8-8b74-dde1c373a473.png)

**Comment by youseries** [comment]
不一致很正常，HTML表达内容会自动撑开，而PDF则不会，对于你这里应该开启单元格自动换行功能。

**Comment by zzhzhengzihao** [comment]
> 

怎么关闭自动换行呀
