### ISSUE TITLE
使用报表内置函数  chn 数字转大写不给力。

### ISSUE THREAD

**Issue by hjzhbb7758** [youseries/ureport#33]
如题，

批发经额合计（小写）： | 20 | 批发经额合计（大写）： | 贰拾零

零售经额合计（小写）： | 22.4 | 零售经额合计（大写）： | 贰拾贰点肆

**Comment by youseries** [comment]
已修复，请更新最新版SNAPSHOT测试，同时增加rmb函数，用于输出符合人民币大写规范的数字对应汉字的大写形式，谢谢。
