### ISSUE TITLE
从数据库里查出来的富文本内容，打印预览显示的是html标签？

### ISSUE THREAD

**Issue by ghostman-git** [youseries/ureport#332]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

v2.2.8

*  #### 遇到的问题描述：
从数据库里查出来的富文本内容，打印预览显示的是html标签？

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/13376074/42607810-5e634d4c-85b7-11e8-8487-10b6efec3dab.png)

![image](https://user-images.githubusercontent.com/13376074/42607824-735c3bc8-85b7-11e8-8db4-4b37aa6d498e.png)

**Comment by youseries** [comment]
HTML会被转义！

**Comment by ghostman-git** [comment]
但结果并没有

**Comment by AlexYY0** [comment]
> 但结果并没有

大佬，这个问题怎么解决的

**Comment by AlexYY0** [comment]
> 但结果并没有

就是输出的内容里面有html应该怎么操作
