### ISSUE TITLE
先制作表内容，后插入表头，显示转换错误

### ISSUE THREAD

**Issue by EugeneDing** [youseries/ureport#333]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.8
*  #### 遇到的问题描述：
**预先**制作表内容的，数据预览正常，**之后**想给其在第一行插入一个表头；
分别给每个单元格写入表头数据：年级、性别、姓名、年龄的四个文本内容，由于插入了新的第一行，原第一行变为第二行，按照逻辑将第二行的父格都有重新定义过；
预览提示错误信息：com.bstek.ureport.exception.ConvertException: Can not convert 年龄 to BigDecimal. 
重新设计以同样的逻辑，先制作表头，再制作表内容，显示正常
期间有尝试将年龄的单元格清除格式，没有启到作用

*  #### 涉及到的异常信息（完整异常信息）：
com.bstek.ureport.exception.ConvertException: Can not convert 年龄 to BigDecimal.

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/34933803/42747452-fc0d5dbc-890e-11e8-83c4-f582ebf545f0.png)
![image](https://user-images.githubusercontent.com/34933803/42747530-59314d6e-890f-11e8-9057-f3bd8efbc88b.png)

**Comment by youseries** [comment]
异常提示很明显！

**Comment by EugeneDing** [comment]
谁不知道提示很明显……！
最起码给个解决的方法吧，如要真想上述问题一样，只能通过重新设计来解决，那这些清除格式的操作有什么意义。
