### ISSUE TITLE
表单时间控件能否提供默认值呢？比如时间控件提供默认值函数

### ISSUE THREAD

**Issue by wangfx** [youseries/ureport#339]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

*  #### 遇到的问题描述：

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
有日期函数，具体看文档。
