### ISSUE TITLE
ureport设置文字字体，是否支持自定义添加字体

### ISSUE THREAD

**Issue by orange-wlwang** [youseries/ureport#340]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

ureport2.2.9

*  #### 遇到的问题描述：
ureport设置文字字体，是否支持自定义添加字体，如果支持，需要怎么配置，如果不支持，以后是否考虑扩展支持

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/34290800/43473905-f155b5a6-9523-11e8-97a4-04ae13ce4c4c.png)

**Comment by youseries** [comment]
目前不支持。
