### ISSUE TITLE
打开报表图表其中包含polarArea 时进行编辑时： 报错，并且无法预览报表

### ISSUE THREAD

**Issue by gengzhengtao** [youseries/ureport#342]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.9

*  #### 遇到的问题描述：

打开报表图表其中包含polarArea 时进行编辑时：
报错，并且无法预览报表
*  #### 涉及到的异常信息（完整异常信息）：
后台无异常

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/1639735/43468080-b11ec62a-9515-11e8-8ee8-a0aed964cb0b.png)

**Comment by youseries** [comment]
最新版SNAPSHOT已修复。
