### ISSUE TITLE
时间显示格式不一致

### ISSUE THREAD

**Issue by siye1103** [youseries/ureport#345]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.8

*  #### 遇到的问题描述：

时间显示格式不一致

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![default](https://user-images.githubusercontent.com/32047486/43560576-bcb1404a-9645-11e8-8eec-2e6abe90bbd5.jpg)

**Comment by youseries** [comment]
是一致的，只是由于换行看起不一致而已。

**Comment by siye1103** [comment]
配置都一样的，字段长度都一样的，为什么显示的会不一样？
