### ISSUE TITLE
sql数据集配置那里的sql查询支持like查询吗？

### ISSUE THREAD

**Issue by github568219115** [youseries/ureport#347]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.3.0

*  #### 遇到的问题描述：

你好，请问下sql查询支持like查询吗？
比如在sql数据集配置那里采用select * from log where title like \'%title\'这种方式采集报错

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

![qq 20180802144050](https://user-images.githubusercontent.com/14368532/43566773-2662a576-9662-11e8-8ccb-1c7b13ee6755.png)

**Comment by youseries** [comment]
支持，刚试了下类似的查询：select * from employee where employee_id like '%A%'
是好的，没问题。
