### ISSUE TITLE
有多条数据情况下，能否实现一页一条有格式的数据

### ISSUE THREAD

**Issue by MengFeiF** [youseries/ureport#352]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.8

*  #### 遇到的问题描述：

![default](https://user-images.githubusercontent.com/32830196/43934339-80f9578a-9c81-11e8-96d0-9ca093ceed3d.jpg)
如上图报表格式，需要实现一次展示多条数据，就是每页都是这个报表格式，但是数据不一样，一页只有一条数据

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
可以，用条件属性里的分页+补充空白行功能实现，具体看视频，里面有类似的例子。
