### ISSUE TITLE
数值型数据设置格式化后，导出EXCEL是字符型，是否在导出EXCEL后，表格中是数值类型。

### ISSUE THREAD

**Issue by bacd25** [youseries/ureport#354]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：2.2.9

*  #### 遇到的问题描述：数值型数据设置格式化后，导出EXCEL是字符型，是否在导出EXCEL后，表格中是数值类型。

*  #### 涉及到的异常信息（完整异常信息）：无

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/42370269/44078368-ded656a0-9fd8-11e8-9b30-24d63f877e44.png)

**Comment by youseries** [comment]
数字格式化后就变成字符串了，所以导出Excel时才会这样。

**Comment by bacd25** [comment]
如果是格式化后，需要在excel中转换为数值型有办法吗，如果没有，是否考虑增加这样的函数呢。


2018-08-20 



　　　　　　　　致
礼！

  


--------------------------------------------------------------  
营收资金稽核系统

公司：深圳市拜特科技股份有限公司
姓名：李文华
电话：13888091656
邮箱：liwh@bytter.com
--------------------------------------------------------------



发件人： 高杰 
发送时间： 2018-08-17  09:30:36 
收件人： youseries/ureport 
抄送： bacd25; Author 
主题： Re:_[youseries/ureport]_数值型数据设置格式化后，导出EXCEL是字符型，是否在导出EXCEL后，表格中是数值类型。_(#354) 
 
数字格式化后就变成字符串了，所以导出Excel时才会这样。
