### ISSUE TITLE
formatdate(param("beginDate"),"yyyyMMdd") 函数报错

### ISSUE THREAD

**Issue by bacd25** [youseries/ureport#355]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：2.2.9

*  #### 遇到的问题描述：报表查询参数格式化函数报错，

*  #### 涉及到的异常信息（完整异常信息）：
![image](https://user-images.githubusercontent.com/42370269/44078637-9ab2217e-9fd9-11e8-9db1-cee6d4ca3c9c.png)

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/42370269/44078869-2e736134-9fda-11e8-94b3-d6560949f2fb.png)

**Comment by youseries** [comment]
formatdate函数是对日期对象进行格式化的函数，也就是对象必须是日期类型，否则就会报错。
