### ISSUE TITLE
表头和横向展开数据对应问题

### ISSUE THREAD

**Issue by lllss** [youseries/ureport#356]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
ureport2-console-2.2.8

*  #### 遇到的问题描述：
表头固定为四列，字段横向展开后的值也为四列，怎么让表头和横向展开的数据一列一列对应起来？

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/31031049/44183304-08f2b180-a13d-11e8-9a12-7f25995c475e.png)
想要的效果：
![image](https://user-images.githubusercontent.com/31031049/44183355-3f303100-a13d-11e8-83cb-b00aac43da91.png)

**Comment by youseries** [comment]
好好看看视频文档，理解后再操作。
