### ISSUE TITLE
数据横纵向同时展开时不能达到预期

### ISSUE THREAD

**Issue by wangshaoan** [youseries/ureport#357]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：2.2.4

*  #### 遇到的问题描述：
数据横纵向同时展开时不能达到预期

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/35585724/44452941-71083280-a62a-11e8-94a7-806467f67d07.png)

**Comment by youseries** [comment]
先好好看看文档视频，理解发父格概念后再操作。

**Comment by wangshaoan** [comment]
这个效果不是我想要的，能达到我想要的效果吗，3q
