### ISSUE TITLE
int 值，报表预览与打印预览结果不一样。 

### ISSUE THREAD

**Issue by hjzhbb7758** [youseries/ureport#36]
如题
![1](https://user-images.githubusercontent.com/5164717/29258568-52a2f946-80ed-11e7-88b5-fcc5b157828b.png)
![2](https://user-images.githubusercontent.com/5164717/29258571-56032a34-80ed-11e7-8e6a-f0c97271ad0d.png)

**Comment by youseries** [comment]
序号怎么产生的？请将问题描述清楚！
