### ISSUE TITLE
报表如何实现批量打开的功能？

### ISSUE THREAD

**Issue by bookboy008** [youseries/ureport#360]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：2.29

*  #### 遇到的问题描述：
比如一个报表，SQL里的 id='{id}',单个打开这个报表预览打印时没有问题的，但是我想实现传入一个Id的集合，能够实现在和个页面，打开多笔数据，这样点击打印时能够全部打印，
类似帆软报表的：
	var reportlets = FR.cjkEncode(paramArr);
			var config = {   
	            url : '/ReportServer',   
	            isPopUp : false,   
	            data : {   
	                reportlets: reportlets   
	            } 
			}
			FR.doURLPDFPrint(config); 

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
不支持。
