### ISSUE TITLE
[question]语法问题

### ISSUE THREAD

**Issue by cobcmw** [youseries/ureport#364]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.9

*  #### 遇到的问题描述：

请问支不支持DISTINCT,IS NOT NULL之类的用法，如果支持的话，详细的文档在哪里？

*  #### 涉及到的异常信息（完整异常信息）：

无

*  #### 相关截图：

无

**Comment by youseries** [comment]
ureport采用的是与spring中NamedParameterJdbcTemplate相同的sql实现方式，具体可以了解NamedParameterJdbcTemplate支持哪些sql.
