### ISSUE TITLE
[bug]设计报表时右侧属性框不显示滚动条

### ISSUE THREAD

**Issue by cobcmw** [youseries/ureport#365]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.9

*  #### 遇到的问题描述：

设计报表时，右侧属性框不能滚动条

*  #### 涉及到的异常信息（完整异常信息）：

在google浏览器，火狐浏览器测试，设计报表时，属性框不能滚动，而数据源框可以，导致属性编辑的时候很累。

*  #### 相关截图：

**属性：**
![image](https://user-images.githubusercontent.com/4659346/44833207-f3fb3f80-ac5f-11e8-9ca4-7a8d73ddf967.png)

**数据源有滚动条**

![image](https://user-images.githubusercontent.com/4659346/44833256-13926800-ac60-11e8-84c6-e071db486708.png)

**Comment by youseries** [comment]
属性面板内容过多时滚动条出现在浏览器右边。

**Comment by cobcmw** [comment]
@youseries 右边是有滚动条不错，但是属性还是展示不完整，火狐和Chrome效果一样，自己试试吧，Chrome:68.0.3440.106 ，不知道你用的什么测试的
