### ISSUE TITLE
取行号问题

### ISSUE THREAD

**Issue by handsomeCLF** [youseries/ureport#367]
![image](https://user-images.githubusercontent.com/20120185/45133831-f1519a80-b1c9-11e8-895c-8a6728284ebe.png)
像我需要第一列配置为序号，但是没办法怎么显示成这样，能和第二列一样合并起来吗
ureport2 使用版本2.1.5 @youseries

**Comment by handsomeCLF** [comment]
已解决

**Comment by nianhua99** [comment]
请问是怎么解决的@handsomeCLF
