### ISSUE TITLE
数据集条件属性新值无效

### ISSUE THREAD

**Issue by handsomeCLF** [youseries/ureport#368]
![image](https://user-images.githubusercontent.com/20120185/45143396-c416e380-b1ed-11e8-90fa-32ba09924406.png)
![image](https://user-images.githubusercontent.com/20120185/45143462-fa546300-b1ed-11e8-9b52-2ee340073b12.png)
该字段为数据集的字段，条件属性配置新值无效果；
![image](https://user-images.githubusercontent.com/20120185/45143494-10faba00-b1ee-11e8-9ecf-84bc30288bb6.png)
![image](https://user-images.githubusercontent.com/20120185/45143510-16580480-b1ee-11e8-946e-47c96df2cb1b.png)
该字段为表达式字段，条件属性配置新值有效果；
![image](https://user-images.githubusercontent.com/20120185/45143562-37205a00-b1ee-11e8-9910-727545bb3175.png)
目前用的ureport2版本为2.2.3，之前用2.1.0是正常的

**Comment by youseries** [comment]
bug，最新版已修复
