### ISSUE TITLE
导出的word跟pdf ，图表类的趋势图和柱状图显示不完全

### ISSUE THREAD

**Issue by leetoclass** [youseries/ureport#370]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.8

*  #### 遇到的问题描述：

[报表在html预览时可以显示完全，但是导出word跟pdf时，图表类的趋势图和柱状图显示不完全

*  #### 涉及到的异常信息（完整异常信息）：
图表类的趋势图和柱状图显示不完全

*  #### 相关截图：
![default](https://user-images.githubusercontent.com/31309248/45291602-3c9ade80-b525-11e8-814b-2c4eecf9453d.png)

**Comment by youseries** [comment]
那是页面宽度不够导致，页面设置修改页面尺寸即可。

**Comment by leetoclass** [comment]
![image](https://user-images.githubusercontent.com/31309248/45334935-a19b1680-b5af-11e8-90f7-08cdc0b7c6f1.png)
修改页面宽度后，文字部分 还是按照原来的宽度排版，显示有些问题。
