### ISSUE TITLE
导出的word跟pdf ，图表类的趋势图和柱状图显示不完全2.0

### ISSUE THREAD

**Issue by leetoclass** [youseries/ureport#371]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.8

*  #### 遇到的问题描述：

[报表在html预览时可以显示完全，但是导出word跟pdf时，图表类的趋势图和柱状图显示不完全,调整页面宽度后，文字部分 还是按照原来的宽度排版，显示有些问题。
*  #### 涉及到的异常信息（完整异常信息）：

图表类的趋势图和柱状图显示不完全
![image](https://user-images.githubusercontent.com/31309248/45335422-e45dee00-b5b1-11e8-978b-bdb1fecbf350.png)

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/31309248/45335443-ffc8f900-b5b1-11e8-93a4-f761f2ac4ab5.png)

**Comment by youseries** [comment]
还是页面宽度问题，对于PDF来说，超出页面宽度的内容会被隐藏，所以你需要增加页面宽度。
