### ISSUE TITLE
隐藏列问题

### ISSUE THREAD

**Issue by handsomeCLF** [youseries/ureport#372]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：2.3.0

*  #### 遇到的问题描述：
问题1：配置隐藏列是否只能用条件属性配置成列宽为0？
问题2：该列用列宽为0配置成隐藏后，子格里的过滤条件有引用该列的话会报空指针,该列设为隐藏后，是不是相当于没有了，而不是隐藏？

*  #### 涉及到的异常信息（完整异常信息）：

![image](https://user-images.githubusercontent.com/20120185/45349646-71219f80-b5e4-11e8-8013-7bb94c6ea77b.png)

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/20120185/45349709-98786c80-b5e4-11e8-9fbb-2459467e2efa.png)

![image](https://user-images.githubusercontent.com/20120185/45350788-3705cd00-b5e7-11e8-9adf-030264c40eab.png)

**Comment by youseries** [comment]
只能用条件属性方式，隐藏后就会从表格中删除该列
