### ISSUE TITLE
v2.2.9 sql 语法中 对三目表达式无效

### ISSUE THREAD

**Issue by ghostman-git** [youseries/ureport#373]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

v.2.29

*  #### 遇到的问题描述：
${emptyparam("departmentId")==true ? "" : "and FBP.DEPARTMENT_ID = :departmentId"}
当参数为null的时候也会执行后边得结果

验证过 v2.2.8正常

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
我这里正常。
