### ISSUE TITLE
浏览器url传参xss攻击

### ISSUE THREAD

**Issue by azengqiang** [youseries/ureport#375]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

Ureport2 2.2

*  #### 遇到的问题描述：

在浏览器url传参进行xss攻击，ureport2有对这种情况做处理吗？

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![xss](https://user-images.githubusercontent.com/18609489/45523984-bcaf9580-b7fe-11e8-8553-a1a8cdbd86ca.jpg)

**Comment by youseries** [comment]
ureport不对此作做处理，你可以在应用层面加个filter，以过滤这些字符。
