### ISSUE TITLE
表格冻结

### ISSUE THREAD

**Issue by howell86** [youseries/ureport#376]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
v2.2.9

*  #### 遇到的问题描述：
表格列比较多的时候，没有冻结查看报表比较吃力，是否能增加冻结的功能。

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
目前不支持，还没有支持的计划。
