### ISSUE TITLE
urule连接mysql数据库，看见的数据都是乱码

### ISSUE THREAD

**Issue by wxb100200** [youseries/ureport#377]
我依赖的是：
<dependency>
            <groupId>com.bstek.urule</groupId>
            <artifactId>urule-console</artifactId>
            <version>2.1.6</version>
        </dependency>
这样配置连接mysql数据库：
urule.repository.dir=
urule.repository.xml=/WEB-INF/mysql.xml
看到数据库里面的数据都是乱码

**Comment by youseries** [comment]
你提错地方了。
