### ISSUE TITLE
sum函数计算精度不对 如图

### ISSUE THREAD

**Issue by simon1026** [youseries/ureport#38]
![4](https://user-images.githubusercontent.com/7332436/29321386-d6898bec-820c-11e7-8b88-428341040e4c.png)
![1](https://user-images.githubusercontent.com/7332436/29321376-cf8a390e-820c-11e7-9cba-375f05fc7d18.png)

**Comment by youseries** [comment]
我这边试了下，没有问题，应该你的format没有加上吧！

**Comment by simon1026** [comment]
你可以试试“74.400000”，这个数值

**Comment by simon1026** [comment]
并且使用sum函数时，格式化无效

**Comment by youseries** [comment]
用你的数据：
![d1](https://user-images.githubusercontent.com/29193502/29353340-6ce52922-829c-11e7-9381-e4f2f7250827.png)
预览效果：
![d1-1](https://user-images.githubusercontent.com/29193502/29353350-76653294-829c-11e7-8001-6146c1e07e0a.png)

我自己的数据：
![d2](https://user-images.githubusercontent.com/29193502/29353456-c07cee1c-829c-11e7-80b3-6caf8d36e5be.png)
预览效果：
![d2-1](https://user-images.githubusercontent.com/29193502/29353463-c8af88d8-829c-11e7-94a4-99dd959edd23.png)

**Comment by youseries** [comment]
没发现有问题！

**Comment by simon1026** [comment]
你把你的数据从数据库读出来，别直接写到A1那，就能重现我的问题了。
![1](https://user-images.githubusercontent.com/7332436/29355707-a765a79a-82a4-11e7-8c1f-2a1a41762e86.png)
![2](https://user-images.githubusercontent.com/7332436/29355710-a7a6a7f4-82a4-11e7-8186-d8212160a4c7.png)
![3](https://user-images.githubusercontent.com/7332436/29355709-a7a1c7f2-82a4-11e7-936d-6daa10352954.png)
![4](https://user-images.githubusercontent.com/7332436/29355712-a7b73b0a-82a4-11e7-966a-dcb31a6bd800.png)

**Comment by simon1026** [comment]
数据要分页，并且sum函数的行为重复表尾行，就会出现这个问题。
![1](https://user-images.githubusercontent.com/7332436/29356021-7dcf0e52-82a5-11e7-9692-ec63ba792559.png)

**Comment by youseries** [comment]
BUG，已修复，请更新最新的ureport2-core-2.0.9-SNAPSHOT测试，谢谢。
