### ISSUE TITLE
floor函数问题

### ISSUE THREAD

**Issue by cqleo** [youseries/ureport#381]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.9

*  #### 遇到的问题描述：
floor函数代码错误

*  #### 涉及到的异常信息（完整异常信息）：
floor(5.22) = 6，应该是等于5

*  #### 相关截图：
![_20180926203202](https://user-images.githubusercontent.com/11845670/46080010-4aaa5980-c1cb-11e8-85c3-8a68f96e4339.jpg)

**Comment by cqleo** [comment]
另外需要纠正wiki文档上函数说明关于ceil与floor的解释与示例。
floor：返回小于或等于一个给定数字的最大整数。floor(32.52)=32
ceil：返回大于或等于一个给定数字的最小整数。ceil(32.32)=33

**Comment by youseries** [comment]
最新版中已修复，请更新测试，谢谢。
