### ISSUE TITLE
IE11下，图表无法渲染，为空白。

### ISSUE THREAD

**Issue by leetoclass** [youseries/ureport#382]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.8

*  #### 遇到的问题描述：

IE11下，图表无法渲染，为空白。

*  #### 涉及到的异常信息（完整异常信息）：

在chorme 预览图表可以正常渲染,IE11下图表为空。
*  #### 相关截图：

![image](https://user-images.githubusercontent.com/31309248/46129918-995b0080-c26a-11e8-9a5f-08bbbb67ca2b.png)
![22](https://user-images.githubusercontent.com/31309248/46130266-6feea480-c26b-11e8-98e2-b4d90d81df63.png)

**Comment by youseries** [comment]
不支持IE
