### ISSUE TITLE
ureport分页查询时后端还是会一次把所有数据都查到内存中

### ISSUE THREAD

**Issue by Debenson** [youseries/ureport#384]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.9

*  #### 遇到的问题描述：
ureport分页查询时后端还是会一次把所有数据都查到内存中，如果报表有大量数据，这会导致查询时间超时，这是故意的行为嘛？

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
报表要实现复杂样式，必须一次性把数据加载到内存。

**Comment by liuluyang06** [comment]
您好 您的问题解决了吗  我也遇到内存溢出的问题了
