### ISSUE TITLE
关于页面加载过慢

### ISSUE THREAD

**Issue by zhanghan2585** [youseries/ureport#385]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.9

*  #### 遇到的问题描述：
页面加载慢 主要集中在 designer.bundle.js 这个js

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/18066720/46602050-b2449b00-cb21-11e8-8ace-171044d4302b.png)

**Comment by youseries** [comment]
目前这个设计器的js是比较大
