### ISSUE TITLE
数据集表达式计算平均数bug

### ISSUE THREAD

**Issue by hug3id** [youseries/ureport#386]
UReport版本：2.2.9

问题描述：
单元格无左上父格，表达式 ds.avg(指标, 年份==2018 and 月份==9) 计算结果错误

经过跟踪发现：
AvgAggregate.java 110行中函数：
buildAvg(List<?> list, String property, Cell cell, DatasetExpression expr, Context context) 
其中 list中数据为未过滤的完整数据，第129行：
int size=list.size(); // 过滤之前的个数
result=result.divide(new BigDecimal(size),8,BigDecimal.ROUND_HALF_UP);

分母没有排除不符合条件的个数，导致计算结果偏低

修复后如下：
private BigDecimal buildAvg(List<?> list, String property, Cell cell, DatasetExpression expr, Context context) {
        Condition condition = getCondition(cell);
        if (condition == null) {
            condition = expr.getCondition();
        }
        
        int size = 0;
        BigDecimal result = new BigDecimal(0);
        for (Object obj : list) {
            if (condition != null) {
                if (!condition.filter(cell, cell, obj, context)) {
                    continue;
                }
            }
            
            Object value = Utils.getProperty(obj, property);
            if (value == null || value.toString().equals("")) {
                continue;
            }
            result = result.add(Utils.toBigDecimal(value));
            size++;
        }

        result = result.divide(new BigDecimal(size), 8, BigDecimal.ROUND_HALF_UP);
        return result;
    }

**Comment by youseries** [comment]
感谢找出BUG，最新的ureport2-core-2.3.0-SNAPSHOT中已修复，谢谢。
