### ISSUE TITLE
绑定查询参数

### ISSUE THREAD

**Issue by shanks-devil** [youseries/ureport#388]
hi~

## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

- 2.2.8
- 2.2.9

*  #### 遇到的问题描述：
数据源使用SpringBean的模式，无法在 **查询表单设计器** 中添加 **查询参数**

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/13478034/46845086-73a62d80-ce0c-11e8-9097-2c1330ffc7e3.png)

**Comment by youseries** [comment]
参数需要在数据集定义的时候定义好后这里才能选择！

**Comment by hesitateDog** [comment]
题主解决了么, SpringBean的模式的数据集没法定义参数
![图片](https://user-images.githubusercontent.com/32887662/147554255-20089d8c-67a6-45f1-9c1a-7d70352f3b19.png)
