### ISSUE TITLE
导出excel数字变文本格式

### ISSUE THREAD

**Issue by MengFeiF** [youseries/ureport#389]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：2.2.8

*  #### 遇到的问题描述：
报表里面的数字，从数据库里面取出来是数字，导出excel会变成下图的样子：

有些会，有些不会，希望可以不要变成文本格式，谢谢！

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by MengFeiF** [comment]
![default](https://user-images.githubusercontent.com/32830196/46900030-44f08b80-cece-11e8-8308-ac5ec1d7abe0.jpg)

**Comment by youseries** [comment]
如果数据库里是数字那么且没有加格式化的时候，那么导出来的就是数字，否则就是字符串
