### ISSUE TITLE
psum函数在预览页没有输出数据，如图

### ISSUE THREAD

**Issue by simon1026** [youseries/ureport#39]
![1](https://user-images.githubusercontent.com/7332436/29321638-a94e8866-820d-11e7-91b7-4d793ca1b8af.png)
![2](https://user-images.githubusercontent.com/7332436/29321639-a975fedc-820d-11e7-8237-5e4add4ca851.png)

**Comment by youseries** [comment]
分页相关函数只有分页预览下有效果。
