### ISSUE TITLE
是否可以采集打印按钮事件

### ISSUE THREAD

**Issue by MengFeiF** [youseries/ureport#390]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.8

*  #### 遇到的问题描述：
需要采集报表界面的打印按钮。下图两个界面，随便采集任何一个都可以

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![1](https://user-images.githubusercontent.com/32830196/46899973-964c4b00-cecd-11e8-9ff5-268b24a48f8f.jpg)

![2](https://user-images.githubusercontent.com/32830196/46899993-cac00700-cecd-11e8-9cf8-8011a2811e12.jpg)

**Comment by youseries** [comment]
做不到
