### ISSUE TITLE
希望能增加Tomcat JNDI的支持

### ISSUE THREAD

**Issue by joy586** [youseries/ureport#408]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.0.6

*  #### 遇到的问题描述：
如果考虑到部署ureport到集成测试环境，用户测试环境，和生产环境，报表模板肯定要尽量一致。
目前的设计需要把密码保存在模板中，导致在多个环境共享模板是困难的。

谢谢！
*  #### 涉及到的异常信息（完整异常信息）：
N/A

*  #### 相关截图：
N/A

**Comment by zhangsean** [comment]
可以使用自定义DataSource数据源，读取配置文件来适应不同环境的数据库地址和密码等。况且生产环境配置报表不能让操作人员知道密码吧，所以自定义数据源是正途！

**Comment by joy586** [comment]
自定义数据源也算是一个折中的解决办法，谢谢。
