### ISSUE TITLE
前端想新增一些个性化功能，怎么调试呢?

### ISSUE THREAD

**Issue by AI-learning** [youseries/ureport#411]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

*  #### 遇到的问题描述：

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
学习js，webpack等。
