### ISSUE TITLE
UReport2报表横向打印

### ISSUE THREAD

**Issue by hlf9420** [youseries/ureport#413]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

UReport2

*  #### 遇到的问题描述：

打印报表的时候能不能点击打印按钮后显示的报表就是横向的

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
报表模版页面配置里，页面横向即可。
