### ISSUE TITLE
数据集查询参数为空的问题

### ISSUE THREAD

**Issue by zsedcbm** [youseries/ureport#42]
select * from employee where area  like :area
此处如果:area参数的默认值为空的时候,将会数据预览失败,无法读取字段. 如果参数传入的值为  上海% 的时候,过滤条件无效
后来此处改为   where area like concat(:area,'%') 之后, area参数默认值%
参数传入值为 上海  时,过滤条件有效
参数传入值为 上海%  时,过滤条件无效

具体的业务需求为 当area为空的时候,显示所有数据,当area为上海的时候,显示所有上海区域的数据.

**Comment by youseries** [comment]
最新版SQL支持表达式，利用表达式就可以实现你的需求，具体使用见：http://wiki.bsdn.org/pages/viewpage.action?pageId=76448802中描述。
