### ISSUE TITLE
单元格减法异常

### ISSUE THREAD

**Issue by LlittleBoy** [youseries/ureport#421]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.9

*  #### 遇到的问题描述：
合同金额，费用登记 是一个数据集合  ， 下单合计是另外一个数据集合的 某个字段的合计 ，这两个集合有关联字段 。 现在 计算  利润 = 合同金额 - 费用登记 - 下单合计    结果无法显示出来 尝试加法没有问题  ；这里 利润 的左父格为 费用登记 所在单元格 其他的都是默认 

*  #### 涉及到的异常信息（完整异常信息）：
减法计算不出结果

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/21997358/53465883-9dde4c00-3a8a-11e9-84c6-ac3672f6500d.png)

![image](https://user-images.githubusercontent.com/21997358/53465911-bbabb100-3a8a-11e9-9111-b05d19c19817.png)

**Comment by LlittleBoy** [comment]
<groupId>com.bstek.ureport</groupId>
<artifactId>ureport2-console</artifactId>
<version>2.2.9</version>

**Comment by youseries** [comment]
减号前后要有空格
