### ISSUE TITLE
ureport如何在后端定时导出结果文件到服务器指定文件夹？

### ISSUE THREAD

**Issue by 1035818889** [youseries/ureport#424]
ureport如何在后端定时导出结果文件到服务器指定文件夹？不用在web界面操作，在后端执行代码就可以把带有查询数据的报表结果文件生成到服务器的指定目录。如：我通过定时job，把某个学生的成绩表查询到了，然后把该学生的成绩表生成到服务器的指定文件。

**Comment by youseries** [comment]
可以，通过ExportManager类实现即可。
