### ISSUE TITLE
表达式pmax()==max()，预览提示报表计算错误：java.lang.NullPointerException

### ISSUE THREAD

**Issue by xiaoei** [youseries/ureport#44]
![image](https://user-images.githubusercontent.com/31120500/29444278-d7fd1452-8410-11e7-97af-7faeee0fc03a.png)
单独求pmax()和max()值显示正常，但是放到判断里就报错了，怎么解决。

**Comment by youseries** [comment]
异常贴上来

**Comment by hjzhbb7758** [comment]
其实你应该问，如何判断显示 a 行  或 b 行

**Comment by xiaoei** [comment]
![image](https://user-images.githubusercontent.com/31120500/29445230-287defc6-8418-11e7-8c3d-27732985d842.png)

**Comment by xiaoei** [comment]
其实是想要：如何让值只在分页的最后一页显示。

**Comment by hjzhbb7758** [comment]
![1](https://user-images.githubusercontent.com/5164717/29445502-c9b24ab2-8419-11e7-8374-e372317763ba.png)
![2](https://user-images.githubusercontent.com/5164717/29445503-cac4bd22-8419-11e7-8daa-1843802a1f4d.png)
控制帧，你看懂了 异常告诉我。这是不是异常

**Comment by hjzhbb7758** [comment]
作者 ，我怎么感觉你跟傻逼一样。 NullPointerException 这不叫异常？

**Comment by xiaoei** [comment]
![image](https://user-images.githubusercontent.com/31120500/29454459-df732206-843f-11e7-829f-696d043c0486.png)

**Comment by youseries** [comment]
BUG,已修复，请更新最新版进行测试，谢谢！

**Comment by xiaoei** [comment]
谢谢~  更新后确实解决了该问题
