### ISSUE TITLE
关于单元格合并

### ISSUE THREAD

**Issue by ttsdmmn** [youseries/ureport#441]
![AXLT4DFT%UD9R4CZUPJ4X`Q](https://user-images.githubusercontent.com/9929415/61019056-6635c800-a3cb-11e9-82ad-587ae2566f71.png)
![@$(%6Z{Q 8{_0G7~2Z}YDAT](https://user-images.githubusercontent.com/9929415/61019094-88c7e100-a3cb-11e9-81cf-7c0fb904114f.png)
第一列序号和最后一列合计的左父格都是B1，怎么配置才能使多行单元格合并成1个单元格显示

**Comment by youseries** [comment]
要理解单元格迭代原理，这样才能做出想要的效果。

**Comment by bajins** [comment]
[demo.zip](https://github.com/youseries/ureport/files/9251621/demo.zip)
主要看B2和D2的左父格
