### ISSUE TITLE
实现ImageProvider接口，加载存在数据库字段中的图片（二进制形式），图片显示不出来

### ISSUE THREAD

**Issue by wangliping0505** [youseries/ureport#444]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.9

*  #### 遇到的问题描述：

实现ImageProvider接口，加载存在数据库中的图片（二进制形式），图片显示不出来；
根据id获取对应的图片的二进制，并以ByteArrayInputStream返回
     实现的getImage接口如下
	@Override
	public InputStream getImage(String id) {
		InputStream in = null;
		if(!StringUtils.isBlank(id)){
			TbReportPdf pdf=dao.selectByReportId(id);
			if(pdf!=null){
				byte [] bytes=pdf.getReportImage();		
				if(bytes!=null){
					 in = new ByteArrayInputStream( bytes); 
				}
							
			}		
		}	
		
	    return in;
	}

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![图片](https://user-images.githubusercontent.com/11640509/61865407-c1a4a180-af05-11e9-9858-472bf7556285.png)
![图片](https://user-images.githubusercontent.com/11640509/61865445-cf5a2700-af05-11e9-923b-9d96d40ea8c8.png)

**Comment by youseries** [comment]
你还不懂ImageProvider用法
