### ISSUE TITLE
条件配置在集合中怎么写

### ISSUE THREAD

**Issue by zDream** [youseries/ureport#449]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：2.2.9

*  #### 遇到的问题描述：
条件配置，操作符为在集合中， 值 表达式如何 写数组？

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
数组是这么写吗？应该怎么写
![image](https://user-images.githubusercontent.com/16067566/63209648-2a062d80-c116-11e9-8090-fb798029e69f.png)

**Comment by youseries** [comment]
去掉双引号：a,b

**Comment by zDream** [comment]
谢谢
