### ISSUE TITLE
中文名称的报表,保存的时候,名称未转码,变成了另存为

### ISSUE THREAD

**Issue by zsedcbm** [youseries/ureport#45]
报表另存为的时候,如果是中文,保存到本地也是中文名称

但是中文名称的报表打开后,再保存,对应的报表名称将变成urlencode 形式的名称.

设计页右上角的名称也是url编码后的文字,有时候又是转码后的文字.

**Comment by youseries** [comment]
报表名暂不支持中文。

**Comment by zsedcbm** [comment]
尝试对 reportTable.js 中的代码进行了一下修改
`        let file=utils.getParameter("_u");
        if(!file || file===null || file===''){
            file='classpath:template/template.ureport.xml';
        }else{
            window._reportFile=file;
        }`
修改为
`        let file=decodeURI(utils.getParameter("_u"));
        if(!file || file===null || file==='' || file === 'null'){
            file='classpath:template/template.ureport.xml';
        }else{
            window._reportFile=file;
        } `
暂时解决了这个问题,不知道对后续有没有影响,待观察.
