### ISSUE TITLE
如何设置拦截器？

### ISSUE THREAD

**Issue by zDream** [youseries/ureport#452]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.9

*  #### 遇到的问题描述：
需求：现需要对设计器url, 预览url 做 权限控制，通过拦截器拦截到用户访问的是哪个url,
所遇问题：如何拦截  **/ureport/designer , **/ureport/preview 这样的url?

写的拦截器可以拦截我写的controller,拦截不了你们的这个url,请问怎么实现？是否支持什么接口配置？

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
在web.xml中配置一个标准的Filter就可以拦截。

**Comment by zDream** [comment]
多谢
