### ISSUE TITLE
ureport图片加载问题

### ISSUE THREAD

**Issue by 18134415595** [youseries/ureport#459]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：2.2.9

*  #### 遇到的问题描述：图片加载设置宽度不设置高度加载还是原图宽高

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by tianyu19900512** [comment]
在web-inf项目放入一个静态图片，只放到根目录下，用/图片名称访问不到，放到resouces用classpath的路径也试了，还是不行，求解

**Comment by tianyu19900512** [comment]
当前UReport版本：2.2.9
遇到的问题描述：在web-inf项目放入一个静态图片，只放到根目录下，用/图片名称访问不到，放到resouces用classpath的路径也试了，还是不行，求解
相关截图：

**Comment by ghost** [comment]
**当前UReport版本：2.2.9**
**遇到的问题描述：**
在web-inf项目放入一个静态图片，只放到根目录下，用/图片名称访问不到，放到resouces用classpath的路径也试了，还是不行，求解
**相关截图：**
<img width="278" alt="360截图181412168195123" src="https://user-images.githubusercontent.com/56626021/66896796-32042000-f028-11e9-95da-9bc1754122e4.png">
<img width="764" alt="360截图174001097794127" src="https://user-images.githubusercontent.com/56626021/66896806-36303d80-f028-11e9-94ff-d993c43f50ec.png">
<img width="374" alt="360截图18141214917469" src="https://user-images.githubusercontent.com/56626021/66896924-83141400-f028-11e9-8236-36d7d8e01718.png">

**Comment by youseries** [comment]
要使用ImageProvider，具体见文件介绍 。
