### ISSUE TITLE
序列化异常

### ISSUE THREAD

**Issue by quqiangsheng** [youseries/ureport#46]
在报表设计器页面设计好预览时提示 报表预览失败
在于我们框架整合后我们框架后台报错
java.io.NotSerializableException: com.bstek.ureport.definition.ColumnDefinition
观察调用栈我分析原因为
预览时会向httpsession中写东西 我们的框架已经由shiro接管了shiro管理 序列化默认使用jdk序列化对象的方式 由于ureport的ColumnDefinition以及com.bstek.ureport.definition.value.Value接口的几个实现没有实现序列化接口 其中有一个实现间接实现了序列化接口 其他实现均没实现序列化接口比如SimpleValue 导致出错
这是一个很常见的问题 希望对jdk序列化保持友好 都添加一下

**Comment by quqiangsheng** [comment]
如果ureport源码不修改的话 可以参考我的解决方案 
使用fst代替jdk序列化机制 高度兼容jdk序列化的包

static FSTConfiguration conf = FSTConfiguration.createDefaultConfiguration();
conf.setForceSerializable(true);
return conf.asByteArray(object);
可以强制序列化 及时不实现序列化接口
读时
// read
Object object = (Object)conf.asObject(bytes);
先凑活用吧 希望官方改进

**Comment by youseries** [comment]
最新版已对基于session的报表存储做了调整，不再存储到session，请更新最新的2.0.9-SNAPSHOT测试，谢谢。
