### ISSUE TITLE
怎么在ureport报表的第一列加一个往下自动递增的序列号

### ISSUE THREAD

**Issue by zengliang0304** [youseries/ureport#461]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

*  #### 遇到的问题描述：

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by zengliang0304** [comment]
![图片](https://user-images.githubusercontent.com/52199140/66693558-c7c44600-ecdc-11e9-9811-96327094bca3.png)

**Comment by hexiangzhi9423** [comment]
我也想知道，如果楼主已经解决，麻烦回应下
