### ISSUE TITLE
在分页报表中如何用函数统计对应目标单元格全部的数量

### ISSUE THREAD

**Issue by light-them-up** [youseries/ureport#464]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
2.2.9

*  #### 遇到的问题描述：
使用count函数只能取到当前分页的统计量

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
count函数依赖于其父格配置，可以看视频，理解单元格迭代时父格原理。
