### ISSUE TITLE
数字格式化失败

### ISSUE THREAD

**Issue by zonghejiankong** [youseries/ureport#47]
![11111](https://user-images.githubusercontent.com/31127016/29451666-191f4a52-8436-11e7-8451-ff6af4588f4e.jpg)
设置了##,###.##，预览界面只有第一行第一列格式化了，导出来的报表只有第一行第一列格式化，但是预览界面跟导出来的还不一致，一个带小数点0一个不带小数点0.

![image](https://user-images.githubusercontent.com/31127016/29451529-98c948ee-8435-11e7-83f6-58e1bc9a12c7.png)
![image](https://user-images.githubusercontent.com/31127016/29451571-b46f51e2-8435-11e7-8c4a-96d97b791dfc.png)

**Comment by youseries** [comment]
请完整贴上模版，并指出是对哪个单元格做的格式化，谢谢。

**Comment by zonghejiankong** [comment]
[35KV.ureport.zip](https://github.com/youseries/ureport/files/1237488/35KV.ureport.zip)

对B4单元格做格式化

**Comment by zonghejiankong** [comment]
另外，数据为空时，迭代展开的数据显示0，最大最小值显示空，平均值显示0，这个能不能统一下？

**Comment by youseries** [comment]
格式化是BUG，目前最新版中已修复，平均值也统一为空。

**Comment by zonghejiankong** [comment]
![image](https://user-images.githubusercontent.com/31127016/29513365-ae7cc468-8697-11e7-96a3-0e0d8586c318.png)

迭代为空的显示是0，平均值也是0

**Comment by youseries** [comment]
更新新版本试试

**Comment by zonghejiankong** [comment]
已更新了2.0.9版，显示空和显示0的问题仍然存在

**Comment by youseries** [comment]
请更新最新的2.1.0-SNAPSHOT测试，谢谢。

**Comment by zonghejiankong** [comment]
2.1.0也没有解决显示空和显示0 的问题

**Comment by zonghejiankong** [comment]
![image](https://user-images.githubusercontent.com/31127016/29601358-b9cf3f86-880d-11e7-9cb2-d1a600775e53.png)
![image](https://user-images.githubusercontent.com/31127016/29601369-c32c6798-880d-11e7-8ada-a5a86baca43f.png)

**Comment by youseries** [comment]
我这里没法重现，你这里值为0是怎么产生的？没有数据就是0？还是只有一条数据值都是0？

**Comment by zonghejiankong** [comment]
没有数据，预览显示0

**Comment by youseries** [comment]
我本地试了下，没有数据显示为空，求平均值、最大值、最小值计算也为空。请确认是否更新到了最新版。

**Comment by zonghejiankong** [comment]
找到原因了，不设置格式化，没有数据、平均值为空；
设置格式化，没有数据、平均值为零；
不管设不设置格式化，最大值、最小值为空。

**Comment by zonghejiankong** [comment]
我觉得应该是这样：不设置格式化，都是空，设置了格式化应该都按照格式化的样子赋值，也就是说没有数据、最大、最小、平均值为零。

**Comment by youseries** [comment]
已做了改进，请更新2.1.1-SNAPSHOT测试，谢谢。

**Comment by zonghejiankong** [comment]
这样吧。
