### ISSUE TITLE
分页预览

### ISSUE THREAD

**Issue by LanYu1210** [youseries/ureport#470]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.9

*  #### 遇到的问题描述：
分页预览下，点击下一页会重新查询一遍数据库速度很慢

*  #### 涉及到的异常信息（完整异常信息）：
速度太慢

*  #### 相关截图：

**Comment by youseries** [comment]
设计如此。
