### ISSUE TITLE
想改下设计器页面,怎么办，能单独分离运行js么

### ISSUE THREAD

**Issue by IOExceptions** [youseries/ureport#473]
*  #### 当前使用的UReport的具体版本号：2.2.3
*  #### 遇到的问题描述：想改设计器的页面一点内容，怎么单独运行js的那个文件夹，使用npm install之后还是不行
*  #### 涉及到的异常信息（完整异常信息）：找不到方法运行
*  #### 相关截图：（公司内网无法上传图片）

**Comment by youseries** [comment]
不提供这种支持。
