### ISSUE TITLE
请问查询表单设计器是否支持日期月份和年份

### ISSUE THREAD

**Issue by zDream** [youseries/ureport#474]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：2.2.9

*  #### 遇到的问题描述：
请问该日期选择框是否支持 yyyy-mm 和 yyyy 等日期格式

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/16067566/68206123-e3361e80-0006-11ea-9877-e328c6dc8aad.png)

**Comment by youseries** [comment]
不支持。
