### ISSUE TITLE
怎样让为空的单元格显示为0问题

### ISSUE THREAD

**Issue by dingwensheng** [youseries/ureport#478]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

*  #### 遇到的问题描述：
例如目标比例，怎样让为空的显示为0
![image](https://user-images.githubusercontent.com/52907281/69203462-5602d600-0b7f-11ea-8cca-9653beb862fc.png)
![image](https://user-images.githubusercontent.com/52907281/69203515-7763c200-0b7f-11ea-9972-c46a86ebd476.png)

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
![image](https://user-images.githubusercontent.com/52907281/69203660-e17c6700-0b7f-11ea-9615-412e851e01e3.png)

**Comment by youseries** [comment]
加条件属性，具体用法看视频教程
