### ISSUE TITLE
点击在线打印报错“Report preview data has expired,can not do load pages for print”

### ISSUE THREAD

**Issue by 308503664** [youseries/ureport#48]
现象就是点击在线打印报错“Report preview data has expired,can not do load pages for print”。
UReport都是最新的2.0.9版本。在线打印仍然报数据过期的这个错误。
调试发现，

1. 当打开报表时ExportManagerImpl.exportHtml中的parameters参数经过reportRender.render之后就被清空了，于是在缓存报表的时候，缓存的键就是file+{};
![qq 20170821150812](https://user-images.githubusercontent.com/11750003/29507439-b00640e4-8682-11e7-8fe4-fe8578530ae4.png)
![qq 20170821150919](https://user-images.githubusercontent.com/11750003/29507444-ba8c4036-8682-11e7-8fe3-7c0ea54817fe.png)

2. 当点击在线打印时，HtmlPreviewServletAction.loadPrintPages(HttpServletRequest, HttpServletResponse)中parameters不为空，此时从缓存中获取报表的键是file+{xxx}，那么肯定是找不到缓存数据的，于是就报错了。

![qq 20170821150938](https://user-images.githubusercontent.com/11750003/29507455-c4b5ef26-8682-11e7-8072-0410d7f06724.png)

总结，就是存的时候的键与获取的时候的键不同。

**Comment by youseries** [comment]
请将问题描述清楚，不用给我贴源码，我看得懂源码！

**Comment by 308503664** [comment]
点击在线打印报错“Report preview data has expired,can not do load pages for print”。
UReport都是最新的2.0.9版本。

**Comment by youseries** [comment]
你传了哪些参数？

**Comment by 308503664** [comment]
预览报表时传的有其他参数，如：ureport/preview?u=my:test.ureport.xml&cachedatakey=adfaoqiwueorqew
在点击在线打印报错“Report preview data has expired,can not do load pages for print”。
UReport都是最新的2.0.9版本。

**Comment by youseries** [comment]
我这边测下来是好的，2.0.9以前的版本没有问题？

**Comment by 308503664** [comment]
2.0.8也有问题。从我第一条ISSUe上的截图上，看出是reportRender.render之后，map里面的参数被清空了导致的

**Comment by 308503664** [comment]
我检查下我这边的数据源吧，可能是数据源处理的问题
