### ISSUE TITLE
pdf 打印预览出现 getOutputStream() has already been called for this response

### ISSUE THREAD

**Issue by WANGJUEYA** [youseries/ureport#481]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.9

*  #### 遇到的问题描述：

pdf 打印预览出现 getOutputStream() has already been called for this response
重现方式:
点击 html 在线预览后, 再点击pdf在线预览则产生上述错误, 或者点击pdf在线打印显示无文件
PS：模板中含有图表的情况下 html在线预览 没有图表->是异常还是不支持?
PPS: 当模板中不含有图表时不会出现上述问题! ->是html图表未及时刷新渲染导致的?

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：

**Comment by youseries** [comment]
试试最新的2.3.0版。

**Comment by WANGJUEYA** [comment]
各大maven库中暂时没有找到 2.3.0的版本
