### ISSUE TITLE
标题栏

### ISSUE THREAD

**Issue by LanYu1210** [youseries/ureport#482]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：

2.2.9

*  #### 遇到的问题描述：
向下滚动时能否浮动标题栏

*  #### 涉及到的异常信息（完整异常信息）：

*  #### 相关截图：
[图片]
![JJ(NT)13@XAH SV2W(I@W(9](https://user-images.githubusercontent.com/53419184/69389850-3a770700-0d08-11ea-8538-97e4ee41ad76.png)

**Comment by youseries** [comment]
不支持。
