### ISSUE TITLE
给条码赋值的时候用表达式emp.select(id),条码的宽度调整不了

### ISSUE THREAD

**Issue by lllss** [youseries/ureport#50]
当宽度为1000的时候会有变化，但是当宽度为100的时候宽度就不会有变化了

**Comment by youseries** [comment]
条码的宽度要受到内容限制的，也就是说，条码会根据内容来显示宽度，如果你给出的宽度已经不能显示条码信息，那么这个宽度将会被忽略。

**Comment by lllss** [comment]
用文本时就可以调整，相同的内容，用表达式就不行，这是怎么回事呢？两者的内容是一模一样的

**Comment by youseries** [comment]
内部处理机制是一样的，你想多了。
