### ISSUE TITLE
怎么实现汇总同时合并单元格的业务

### ISSUE THREAD

**Issue by leo187** [youseries/ureport#505]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：ureport2

*  #### 遇到的问题描述：汇总列未合并单元格

*  #### 相关截图：
![clipboard2](https://user-images.githubusercontent.com/18244455/78955240-3b6ed080-7b11-11ea-857f-dc2bd1ff442b.png)
![clipboard1](https://user-images.githubusercontent.com/18244455/78955243-3d389400-7b11-11ea-882b-844292254a0d.png)

**Comment by calebzhao** [comment]
怎么解决的？

**Comment by llmoe** [comment]
大佬 解决了吗，求教

**Comment by windynet** [comment]
大佬 解决了吗，求教
