### ISSUE TITLE
ureport2  数据集问题

### ISSUE THREAD

**Issue by niuey2001** [youseries/ureport#52]
按照示例里面用${} 表达式方式写数据集，后台报错：出现不支持的 SQL92 标记: 9: return，前台没发显示字段信息

**Comment by youseries** [comment]
你怎么写的？截个图上来看看！

**Comment by niuey2001** [comment]
就完全照着例子里面写的
${ 
if (param("bm")==null || param("bm")==''){
   return "select * from test01"
}else{
return "select * from test01 where bm=:bm"
        }
}

后台提示 出现不支持的 SQL92 标记:

图片传不了，提示can't process that file

**Comment by youseries** [comment]
ureport从2.0.9版本开始才支持SQL数据集表达式（http://wiki.bsdn.org/pages/viewpage.action?pageId=76448802），请查看你采用的什么版本，谢谢。
