### ISSUE TITLE
两个负数相减不合适

### ISSUE THREAD

**Issue by wyubaoyuan** [youseries/ureport#53]
![qq 20170824095126](https://user-images.githubusercontent.com/16440584/29645694-d0fc75a8-88b1-11e7-80d1-ee154462aade.png)
![qq 20170824095133](https://user-images.githubusercontent.com/16440584/29645695-d10a5d1c-88b1-11e7-880c-cdc19cc1b879.png)

**Comment by youseries** [comment]
什么叫不合适？请描述清楚！

**Comment by wyubaoyuan** [comment]
你看不到图片吗？   -3960-（-3080）=-880，可是报表计算的结果是-7040

**Comment by youseries** [comment]
BUG,已修复，请更新最新的2.1.0-SNAPSHOT测试，谢谢。

**Comment by wyubaoyuan** [comment]
更新后，运行不了了，报错

Invalid bean definition with name 'ureport.httpSessionReportCache' defined in class path resource [ureport-console-context.xml]: Could not resolve placeholder 'ureport.disableHttpSessionReportCache' in string value "${ureport.disableHttpSessionReportCache}"
![qq 20170824171819](https://user-images.githubusercontent.com/16440584/29659250-359cdd5c-88f0-11e7-83eb-cc3de109b163.png)
不加这个pom,可以运行，但是之前的问题没解决

**Comment by youseries** [comment]
看来你不懂maven,找个懂maven来帮忙更新吧！

**Comment by wyubaoyuan** [comment]
![qq 20170825150716](https://user-images.githubusercontent.com/16440584/29703219-3715752e-89a7-11e7-8d75-a3ee35f71bb9.png)
没有加载到2.1.0版本
