### ISSUE TITLE
重新打包ureport-js报错

### ISSUE THREAD

**Issue by xuexiaoao** [youseries/ureport#54]
改了一些js，重新打包生成js时报错，没用过webpack，找不到哪里有问题。。。。
![image](https://user-images.githubusercontent.com/18185523/29647566-5caf6c72-88bc-11e7-8011-55e894568f67.png)
![image](https://user-images.githubusercontent.com/18185523/29647579-6b84d6e2-88bc-11e7-9a81-5689d87b15fd.png)

![7rd_9 97 1v 4fuanfpiese](https://user-images.githubusercontent.com/18185523/29647698-2374def0-88bd-11e7-9c87-b24520da71bf.png)
![image](https://user-images.githubusercontent.com/18185523/29647715-3d80cea8-88bd-11e7-8934-ed93af4c27c6.png)
![kzx3pinej j g _md73fux](https://user-images.githubusercontent.com/18185523/29647794-90bca862-88bd-11e7-8f7c-33b238f80178.png)

**Comment by youseries** [comment]
ureport2-js采用的是es6语法，需要熟悉es6语法、npm、webpack才有可能编译成功，如果不了解这些建议先去学习下，否则没法下手！

**Comment by xuexiaoao** [comment]
找到问题的原因了，是打包字体文件的url-loader配置的正则表达式有问题
