### ISSUE TITLE
DatasetUndefinitionException

### ISSUE THREAD

**Issue by njsbq** [youseries/ureport#56]
我使用了手动新建数据连接的方式，设计都没什么问题，但是预览的时候，提示报表计算错误：com.bstek.ureport.exception.DatasetUndefinitionException: Dataset [user] not definition.这个问题可能存在那边？

**Comment by youseries** [comment]
异常的意思是你在报表中用了一个名为"user"的数据集，但这个数据集又没有定义。
检查下你是不是将这个名为“user”的数据集删除了？
