### ISSUE TITLE
多台tomcat问题

### ISSUE THREAD

**Issue by xmushi** [youseries/ureport#57]
你好，我们生产环境有多台tomcat
但是数据源，报表配置都存在tomcat目录下。怎么同步呢？

**Comment by youseries** [comment]
ureport允许用户通过实现ReportProvider接口自定义报表存储，具体见：http://wiki.bsdn.org/pages/viewpage.action?pageId=76448468
对于你的这种需求，可以通过实现ReportProvider接口将报表存储到数据库中，就可以解决类似需求。
