### ISSUE TITLE
斜线表头可以自定义项目个数吗

### ISSUE THREAD

**Issue by sonot** [youseries/ureport#58]
目前斜线表头只能生成3个项目的斜线，如果要生成2个项目的斜线如何处理？

**Comment by youseries** [comment]
目前不支持，该功能将在下一版本实现。

**Comment by youseries** [comment]
已添加斜表头自定义功能，请更新最新的2.1.1-SNAPSHOT测试，谢谢。

**Comment by sonot** [comment]
响应速度太快了，赞一个！

**Comment by sonot** [comment]
测试了一下，功能可以用，但是最好再优化一下，当项目只有两个时，斜线应该是对角线。

**Comment by youseries** [comment]
只能这样啦！

**Comment by sonot** [comment]
Jacky,
　你好，斜线改成对角线我感觉修改一下CrossTabWidget是可以实现的, 遗憾的是我不知道ureport2-js怎么build，在这里我说一下思路，不知道是否可行, 见笑了！
　修改dodraw函数，判断size==2时，path（0，0，this.width,this.height）
　

发送自 Windows 10 版邮件应用

发件人: 高杰
发送时间: 2017年8月28日 15:01
收件人: youseries/ureport
抄送: sonot; Author
主题: Re: [youseries/ureport] 斜线表头可以自定义项目个数吗 (#58)

Closed #58.
