### ISSUE TITLE
打印时，多行数据，第二页出现大量空白只显示一行，其余行数据都在第三页

### ISSUE THREAD

**Issue by 15pkzhaozhu** [youseries/ureport#594]
## 为了您的问题能得到及时准确解答，请认真填写下面各个选项，感谢您的配合。

*  #### 当前使用的UReport的具体版本号：
<version>2.2.9</version>

*  #### 遇到的问题描述：
打印时，多行数据，第二页出现大量空白只显示一行，其余行数据都在第三页

*  #### 涉及到的异常信息（完整异常信息）：

![image](https://github.com/youseries/ureport/assets/12639650/ca05f4d5-c6cd-4fe0-9cf5-d03b6992e7c0)

**Comment by 15pkzhaozhu** [comment]
已通过修改ureport2-core的源码，来解决该问题
![8GC X`DX%XB08M%1E8TQ)8H](https://github.com/youseries/ureport/assets/12639650/6bc990ec-6f94-4142-8952-c84e46028181)

**Comment by wuyuanrui** [comment]
所以改了那部分内容嘞

**Comment by wuyuanrui** [comment]
所以改了那部分内容嘞

**Comment by 15pkzhaozhu** [comment]
> 所以改了那部分内容嘞
com/bstek/ureport/export/pdf/PdfProducer.java

				for(List<Page> pages:list){
					PdfPTable table=new PdfPTable(size);

增加如下代码
					// 给当前的PdfPTable同时设置这两个属性可避免自动分页出现空白的问题
					table.setSplitLate(false);
					table.setSplitRows(true);
