### ISSUE TITLE
数据集sql表达式的问题

### ISSUE THREAD

**Issue by xuexiaoao** [youseries/ureport#61]
这边有这样一个需求，从前台传过来三个参数，我希望根据参数的不同，可以实现类似mybaits的动态拼接sql的能力，而不是像现有的表达式能力一样，每一个if或else条件返回一个sql，这样的弊端在于如果参数很多的话要写的sql实在是太多了
我的需求是这样的
![vbw e9 kbz 8lnog6yu](https://user-images.githubusercontent.com/18185523/29756175-4c904882-8bd4-11e7-8c54-ff81a052d651.png)
现在能实现的是这样的
![test](http://wiki.bsdn.org/download/attachments/76448802/sql-expr.png)
请问下一步是否有实现类似功能的计划，或者说可以指点一下我应该如何修改。。。。

**Comment by youseries** [comment]
实现不了，也没有计划实现，所以也无法指点你实现，谢谢。
