### ISSUE TITLE
是否可以支持这种表头做统计的功能

### ISSUE THREAD

**Issue by bigbeef** [youseries/ureport#63]
![image](https://user-images.githubusercontent.com/17740213/29814686-ce2fbb2c-8ce0-11e7-8012-9f16b170b0a8.png)
是否可以支持这种表头做统计的功能！

**Comment by youseries** [comment]
可以，请完整看完ureport2教学视频，特别是其中关于“报表模型介绍”部分视频，理解了你就知道如何做了。
