### ISSUE TITLE
Spring bean数据集返回值问题

### ISSUE THREAD

**Issue by gsw54188** [youseries/ureport#64]
请问Spring bean数据集的返回值在网站中说明只能支持List集合，那如果要返回一个Map,里面有单个的值和一个List列表，可以处理么？

**Comment by youseries** [comment]
你描述的是一个典型的主从报表结构，主表是个表单，数据在你说的这个Map里，从表有多条记录，在这个List中。
实现时需要两个数据集，一个数据集里是这个Map（返回是个List，里面只有一个Map），另一个是这个List，具体可以看看ureport2提供的教学视频，在关于“报表模型介绍”部分视频，里面有类似的例子，谢谢。
视频地址信息：http://wiki.bsdn.org/pages/viewpage.action?pageId=76448364
