### ISSUE TITLE
报表链接URL传入参数是汉字时候，报表在获取后乱码

### ISSUE THREAD

**Issue by lile405** [youseries/ureport#65]
报表链接URL传入参数是汉字时候，报表在获取后乱码。
浏览器地址: http://127.0.0.1:8080/report/preview?_u=file:th.ureport.xml&bbdw=中国银行
但是在页面通过param("bbdw")获取到的却是乱码。 
![111](https://user-images.githubusercontent.com/30850078/29902676-22e48402-8e32-11e7-8a5d-8736accf4744.png)

**Comment by youseries** [comment]
你需要对中文进行encode，如果在JS中可以用encodeURI实现。
但实际上，在浏览器中，URL后面加上中文会自动进行encode，所以在JS中需要进行两次encode：encodeURI(encodeURI("中国银行"))，编码后的值为：%25E4%25B8%25AD%25E5%259B%25BD%25E9%2593%25B6%25E8%25A1%258C，将这个值作为参数值就可以显示中文了。
