### ISSUE TITLE
请问该如何实现：预览页面点击导出Excel按钮，弹出对话框选择本地路径保存。

### ISSUE THREAD

**Issue by zonghejiankong** [youseries/ureport#66]

**Comment by youseries** [comment]
这个实现不了，导出功能服务端只负责推送导出文件到浏览器，至于浏览器会有什么样的动作响应，我们是不能干预的，所以有些浏览器会直接下载到固定目录（比如chrome）；有些则会像你说的那样弹出框选择保存路径（早期的IE好像就是这样）
