### ISSUE TITLE
以后会不会增加一个查询面板设置功能

### ISSUE THREAD

**Issue by zsedcbm** [youseries/ureport#67]
目前的报表设计功能很强大,有点遗憾的是,不能自定义查询,现在报表设计好了之后,需要另外再做一个查询界面,然后将数据提交到预览页进行过滤显示,报表可以不需要修改代码直接进行编辑.而查询界面需要修改对应的代码.

**Comment by youseries** [comment]
查询实际上也是不需要修改代码的：方法你是做一个页面，比如一个普通的JSP，在这个页面中设计好查询表单，下面放一个iframe，在这个iframe里嵌入报表预览页面URL即可.
