### ISSUE TITLE
多表联查问题

### ISSUE THREAD

**Issue by lllss** [youseries/ureport#68]
1.没有参数时的结果
![default](https://user-images.githubusercontent.com/31031049/29959424-cd6a7c7c-8f29-11e7-9a6f-8e236554b08b.png)
2.通过报表设计器配置得到的结果，查询时，将查询条件加到emp表的sql中，查询出来的结果本来应该只显示财务部，但是人力资源部也显示出来了，就是dep表执行的还是select * from dep,怎么可以只显示相关联的数据，没有关联的不显示
![default](https://user-images.githubusercontent.com/31031049/29959397-ab668490-8f29-11e7-8c1f-95c79e1d3a97.jpg)
3.通过inner join 联表得到的结果（这个是最终想要的效果）
![inner](https://user-images.githubusercontent.com/31031049/29959419-c4e65f30-8f29-11e7-8643-e1e91ceb0a98.png)

**Comment by youseries** [comment]
没太看懂你的问题。
在我看来表连接本来就该用join，否则出现上面的错误现象也不奇怪。
如果你发现出来的数据有问题，那么可以将这个SQL加个这个参数值直接执行下看看查询结果是什么，然后再比较报表中输出，以确认问题出在哪！
