### ISSUE TITLE
round函数（四舍五入）的问题

### ISSUE THREAD

**Issue by xuexiaoao** [youseries/ureport#69]
对于0以下类似0.123456这样的小数，使用round函数都会返回1。查看源码发现是调用了java的Math.ceil导致的。可是现在想对0.1234567这类小数进行四舍五入，请问有没有对应的函数呢

**Comment by youseries** [comment]
round函数bug，最新版2.1.2-SNAPSHOT中已修复，请下载此版本测试，谢谢。
