### ISSUE TITLE
数据量大了后导不出excel？

### ISSUE THREAD

**Issue by lizhongxiang12138** [youseries/ureport#7]
当报表的数据量达到上万条数据后，导出数据到exce时等待了20多分钟还是弹不出下载对话框。
	
	数据在线预览可以预览（速度会比较慢，但是可以预览，导出excel等待了20多分钟还是没有弹出下载对话框）。
       
        服务器内存 32G，tomcat分配内存4G

**Comment by youseries** [comment]
报表预览效果截个图，具体多少条数据？
