### ISSUE TITLE
select的bug

### ISSUE THREAD

**Issue by lygoing** [youseries/ureport#72]
单元格1：sd1.select(s, s == 1)
单元格2：sd1.select(s, s == 2)
列表输出：
单元格1：1
单元格2无数据显示

若改成

单元格1：sd1.select(s, s == 2)
单元格2：sd1.select(s, s == 2)
列表输出：
单元格1：2
单元格2：2

**Comment by youseries** [comment]
这不是bug，是你不懂单元格依赖关系。
单元格1和单元格2是连在一起的，那么，单元格1默认就是单元格2的左父格或上父格（看看你实际的报表是什么样），单元格2的数据就依赖于单元格1，单元格2和单元格1又是同一个数据集，也就是sd1，这样单元格1在取数据是只留下了s==1的数据，所以在单元格2中取不到数据（因为单元格2要取s==2的数据）。
如果还是不理解，再去好好看看视频中关于模型的介绍的，如果实在理解不了，那我也没办法了。

**Comment by lygoing** [comment]
@youseries 谢谢呀，现在明白了
