### ISSUE TITLE
spring 依赖冲突

### ISSUE THREAD

**Issue by lygoing** [youseries/ureport#73]
![image](https://user-images.githubusercontent.com/5944432/30047644-d9757c24-9244-11e7-97eb-8e4d93bac472.png)
spring-jdbc 版本是4.1.5
spring-web 版本是4.1.2

**Comment by youseries** [comment]
已确认，ureport中用的spring版本都是4.1.2，看看是不是你用了其它包的依赖导致。
![d](https://user-images.githubusercontent.com/29193502/30048035-ceb7e4f0-9246-11e7-8036-9e0690f89494.png)
