### ISSUE TITLE
font包引用的core包不是最新版

### ISSUE THREAD

**Issue by lygoing** [youseries/ureport#74]
![image](https://user-images.githubusercontent.com/5944432/30048212-c4ff6e78-9247-11e7-816a-8b50e40d104a.png)
在应用console包时包版本会有冲突

**Comment by youseries** [comment]
font包一直都是这个版本，没必要与core或console保持一致！

**Comment by lygoing** [comment]
@youseries 嗯，确实不会影响正常运行咯，只是在maven中会显示一个冲突，font作为字体包不经常变动，确实没必要每次做版本升级，只是这里引用的core包会有版本迭代

**Comment by lygoing** [comment]
@youseries 感谢百忙中处理 O(∩_∩)O
