### ISSUE TITLE
报表图片问题

### ISSUE THREAD

**Issue by michaelbstek** [youseries/ureport#77]
如果将报表图片的路径存在数据库表的某一个字段中，当这个字段值为空时，报表预览没问题，就是一个空的单元格，但是在导出PDF文件时会报图片转换异常,异常日志如下：

This application has no explicit mapping for /error, so you are seeing this as a fallback.
There was an unexpected error (type=Internal Server Error, status=500).
java.io 
.IOException: The byte array is not a recognized imageformat.

**Comment by youseries** [comment]
更新最新的snapshot试试。
