### ISSUE TITLE
双数据源显示

### ISSUE THREAD

**Issue by tirestay** [youseries/ureport#78]
需求：
用户场景是显示员工的绩效趋势（如图1），按照月份横向展开，其中总分＝调整＋绩效分。这里使用了两个数据源来显示（因为一个数据源实现不了效果），这里的总分，调整分绩效分都是第一个数据源提供，然后绩效分细分到指标1和指标2，指标是个不定长集合，指标的总和等于绩效分，这里用了第二个数据源来显示。

问题：
现在的问题是，两个数据源都根据月份展开，但是跟期望的不一样，展开的列没有对应，如图2.

<img width="463" alt="default" src="https://user-images.githubusercontent.com/6051065/30271743-f5a11b86-9723-11e7-91c2-4bca7a88332d.png">

![default](https://user-images.githubusercontent.com/6051065/30271873-833836d2-9724-11e7-82ec-8fd6eb6014e2.png)

**Comment by youseries** [comment]
报表模版贴上来，并说明你的配置方式，谢谢！

**Comment by tirestay** [comment]
[perf.test.ureport.xml.zip](https://github.com/youseries/ureport/files/1292329/perf.test.ureport.xml.zip)

**Comment by tirestay** [comment]
数据源配置是spring+bean

**Comment by youseries** [comment]
请直接截图上来，谢谢。

**Comment by tirestay** [comment]
第一个数据源bean字段：
private BigDecimal score;
private BigDecimal kpiScore;
private BigDecimal adjustScore;

第二个数据源bean字段：
private String kpiName;
private Integer kpiScore;
private Integer month;

**Comment by tirestay** [comment]
多谢帮忙，顺利解决

**Comment by tirestay** [comment]
第二个数据源的展开格中设置：
1，上父格设置为第一个数据源的展开格。
2，过滤条件添加对应列相等，此例中是month。
