### ISSUE TITLE
报表的列数是动态的列，如何实现

### ISSUE THREAD

**Issue by analywww** [youseries/ureport#79]
目前是否支持 动态列显示？

A,B,C,D 固定列     E,F,G,H,J... 不固定  如何实现 ，需要根据后台配置 ，读取 列 数  后确定 显示几列 ，然后显示到报表 上

**Comment by xmushi** [comment]
数据扩展方向，向右。

**Comment by youseries** [comment]
不支持动态列

**Comment by 1125068334** [comment]
> 不支持动态列

你好，商业版本支持动态列吗？
