### ISSUE TITLE
交叉表数据显示

### ISSUE THREAD

**Issue by fightAllDay** [youseries/ureport#80]
需求：用户场景是显示公司的费用趋势（如图1），各费用按照月份横向展开，费用数据逐级求和。
问题：现在碰到的问题是，各费用按照月份横向展开后，不同费用的数据叠加了（如图2）

**Comment by fightAllDay** [comment]
图1：
![1](https://user-images.githubusercontent.com/31916772/30379184-3d1fb652-98c8-11e7-9006-247ce0d495e5.JPG)

图2：
![2](https://user-images.githubusercontent.com/31916772/30379332-ba2dc9ae-98c8-11e7-9614-3063cddf80e1.JPG)
住宿费那一行的数据把出差费和住宿费的数据叠加了。

**Comment by youseries** [comment]
横向展开费用横向逐级求和这个实现不了，不过可以纵向展开，纵向逐级求和。也就是说将费用名作为列名，日期向下展开，然后逐级求和，具体作法见文档http://wiki.bsdn.org/pages/viewpage.action?pageId=76448569 中“逐层累加”介绍，也可以看对应的视频，谢谢。

**Comment by fightAllDay** [comment]
好的，再请问一下，如果将费用名作为列名，日期横向向右展开，费用纵向展开，然后对费用纵向逐级求和，请问可以实现这种逐层累加吗？谢谢。

**Comment by youseries** [comment]
交叉表不支持逐级求和，也没法逐级求和
