### ISSUE TITLE
条件配置中过滤条件比较

### ISSUE THREAD

**Issue by tanmingft** [youseries/ureport#82]
![image](https://user-images.githubusercontent.com/28721406/30423831-a93e17c6-9976-11e7-8136-1503f2de27a6.png)

**Comment by tanmingft** [comment]
结果报异常报表计算错误：com.bstek.ureport.exception.ConvertException: Can not convert [10] to BigDecimal.

**Comment by tanmingft** [comment]
如果值表达式中我填写数字，预览结果正常。

**Comment by tanmingft** [comment]
![image](https://user-images.githubusercontent.com/28721406/30462615-67d3f0a2-99f9-11e7-8496-52943b704318.png)

**Comment by youseries** [comment]
请更新最新的2.1.3-SNAPSHOT试试，谢谢。
