### ISSUE TITLE
参数传递中文，param取出来乱码

### ISSUE THREAD

**Issue by gsw54188** [youseries/ureport#84]
通过url参数传中文，param函数取出来是乱码

**Comment by youseries** [comment]
URL传递的中文，必须要进行两次encode，比如在JS中需要进行如下操作：
encodeURI(encodeURI("参数值"))
将encode后的值放在URL后面即可取到正确的中文，谢谢。

**Comment by tanmingft** [comment]
tomcat设置字符集也可以
