### ISSUE TITLE
导出pdf时第一列错位

### ISSUE THREAD

**Issue by xuexiaoao** [youseries/ureport#87]
只有导出pdf时有这种情况，word,excel都没有问题
![image](https://user-images.githubusercontent.com/18185523/30798416-271fc1c4-a20c-11e7-9a59-1b073e319f36.png)

**Comment by youseries** [comment]
没看明白，正确的应该是什么样？

**Comment by xuexiaoao** [comment]
表述的有问题，我的意思是我设置的第一列现在导出的时候不清楚为什么移到最后一列了，正常应该是在类型这一列左边的。。。

**Comment by youseries** [comment]
请给出报表模板完整截图，同时附上正常效果的截图，谢谢！
