### ISSUE TITLE
ureport数据集对应的查询sql，可以支持语句的动态拼装吗？

### ISSUE THREAD

**Issue by chenpengGH** [youseries/ureport#9]
比如编辑数据集的sql时，查询出的列不固定，我想通过参数动态传入一串列名，显示不同的结果。
还有sql语句中的其他部分 比如 from 的表名，group by的字段，也可以通过参数拼装。

例：
select  :cols from employee
参数
cols  String  emp_id,dept_id,emp_name

**Comment by youseries** [comment]
不支持，谢谢！

**Comment by chenpengGH** [comment]
哦 那请问以后的版本会实现这个需求吗？

**Comment by youseries** [comment]
目前还没这个计划！

**Comment by chenpengGH** [comment]
好的 谢谢解答！
