### ISSUE TITLE
excel分页导出异常

### ISSUE THREAD

**Issue by sonot** [youseries/ureport#91]
点“分页导出EXCEL”出错。
javax.servlet.ServletException: java.lang.reflect.InvocationTargetException
	com.bstek.ureport.console.BaseServletAction.invokeMethod(BaseServletAction.java:73)
	com.bstek.ureport.console.excel.ExportExcelServletAction.execute(ExportExcelServletAction.java:54)
	com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:76)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:96)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
root cause

java.lang.reflect.InvocationTargetException
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:601)
	com.bstek.ureport.console.BaseServletAction.invokeMethod(BaseServletAction.java:71)
	com.bstek.ureport.console.excel.ExportExcelServletAction.execute(ExportExcelServletAction.java:54)
	com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:76)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:96)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
root cause

com.bstek.ureport.exception.ReportComputeException: java.lang.IndexOutOfBoundsException: Index: 166, Size: 27
	com.bstek.ureport.export.excel.high.builder.ExcelBuilderWithPaging.build(ExcelBuilderWithPaging.java:254)
	com.bstek.ureport.export.excel.high.ExcelProducer.doProduce(ExcelProducer.java:43)
	com.bstek.ureport.export.excel.high.ExcelProducer.produceWithPaging(ExcelProducer.java:32)
	com.bstek.ureport.console.excel.ExportExcelServletAction.buildExcel(ExportExcelServletAction.java:95)
	com.bstek.ureport.console.excel.ExportExcelServletAction.paging(ExportExcelServletAction.java:60)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:601)
	com.bstek.ureport.console.BaseServletAction.invokeMethod(BaseServletAction.java:71)
	com.bstek.ureport.console.excel.ExportExcelServletAction.execute(ExportExcelServletAction.java:54)
	com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:76)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:96)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
root cause

java.lang.IndexOutOfBoundsException: Index: 166, Size: 27
	java.util.ArrayList.rangeCheck(ArrayList.java:604)
	java.util.ArrayList.get(ArrayList.java:382)
	com.bstek.ureport.export.excel.high.builder.ExcelBuilder.getWholeHeight(ExcelBuilder.java:54)
	com.bstek.ureport.export.excel.high.builder.ExcelBuilderWithPaging.build(ExcelBuilderWithPaging.java:211)
	com.bstek.ureport.export.excel.high.ExcelProducer.doProduce(ExcelProducer.java:43)
	com.bstek.ureport.export.excel.high.ExcelProducer.produceWithPaging(ExcelProducer.java:32)
	com.bstek.ureport.console.excel.ExportExcelServletAction.buildExcel(ExportExcelServletAction.java:95)
	com.bstek.ureport.console.excel.ExportExcelServletAction.paging(ExportExcelServletAction.java:60)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:601)
	com.bstek.ureport.console.BaseServletAction.invokeMethod(BaseServletAction.java:71)
	com.bstek.ureport.console.excel.ExportExcelServletAction.execute(ExportExcelServletAction.java:54)
	com.bstek.ureport.console.UReportServlet.service(UReportServlet.java:76)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:96)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)

**Comment by youseries** [comment]
最新版SNAPSHOT中已做处理，请更新试试，谢谢。
