### ISSUE TITLE
ureport2-js 本地编译出错

### ISSUE THREAD

**Issue by zsedcbm** [youseries/ureport#92]
本地编译 ureport2-js的时候提示出错
`
ERROR in ./src/i18n/preview.json
Module parse failed: E:\Testworkspace\ureport\ureport2-js\src\i18n\preview.json Unexpected token(2:12)
You may need an appropriate loader to handle this file type. 
`

**Comment by youseries** [comment]
抱歉，这里不提供源码编译打包支持。

**Comment by zsedcbm** [comment]
webpack.config.js 里面的 module -> loaders  增加
            {
              test: /\.json$/,
              loader: 'json-loader'
            },
