### ISSUE TITLE
SQL参数表达式

### ISSUE THREAD

**Issue by jueding920** [youseries/ureport#96]
SQL参数表达式 过单一，无法满足复杂语句 或者 多条件情况
建议改进表达式，实现可嵌套在SQL中 只对某个Where条件只进行参数判断

**Comment by youseries** [comment]
SQL表达式除了可以使用if else判断外，还可以使用三元表达式，如：
`
select * from employee where 1=1 (param("deptId")==null ? '' : 'dept_id=:deptId')
`
多个条件依次类推。
