### ISSUE TITLE
双数据源求和取值

### ISSUE THREAD

**Issue by fightAllDay** [youseries/ureport#97]
需求：
用户场景是根据收入、成本合计和费用合计显示公司的毛利和利润（如图1），其中毛利=收入-成本合计，利润=收入-成本合计-费用合计，成本合计=成本一+成本二+成本三，费用合计=费用一+费用二+费用三,
即：B7 =B2-B3，B12 = B2-B3-B8，B3=B4+B5+B6，B8=B9+B10+B11。
这里使用了双数据源来显示（一个数据源实现不了效果），这里的收入、费用合计以及费用合计的子级费用一、费用二、费用三都是第一个数据源提供，然后成本合计以及成本合计的子级成本一、成本二、成本三用了第二个数据源来提供。

问题：
现在碰到的问题是，使用公式“毛利=收入-成本合计”时（B7 =B2-B3），没有获取到成本合计的值（即单元格B3）；
使用公式“利润=收入-成本合计-费用合计"时（B12 = B2-B3-B8），没有获取到成本合计和费用合计的值（即单元格B3和B8）。（如图2）

图1：
![1](https://user-images.githubusercontent.com/31916772/31849466-02e58690-b675-11e7-9aba-1f35f8c81e98.png)
图2：
![2](https://user-images.githubusercontent.com/31916772/31849472-247034e0-b675-11e7-8bf7-edabd77af054.png)

**Comment by youseries** [comment]
模板怎么设计的，完整贴上模板截图并详细说明，谢谢

**Comment by fightAllDay** [comment]
您好,非常不好意思，早上再次尝试做模板发现问题是可能单元格设置错误导致的。现今问题已经解决了。非常感谢您的关注，谢谢！
